<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
                <form action="<?php echo $this->url(array("action" => "grupos")); ?>" method="post" id="formulario" class="formulario">
                    <input type="hidden" name="id" id="id" value="<?php echo $this->usuario->getId(); ?>" />
                    <div class="well">
                        <dl class="dl-horizontal">
                            <dt>Usuário:</dt>
                            <dd><?php echo $this->usuario->toString(); ?></dd>
                        </dl>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <table class="table table-striped table-bordered esquerda">
                                <thead>
                                    <tr>
                                        <th width="20px"><input type="checkbox" name="ck_usuarios" id="ck_usuarios" class="ck-marca-todos" rel="lista_usuarios" /></th>
                                        <th>Todos os Grupos do Sistema</th>
                                    </tr>
                                </thead>
                                <tbody>
<?php foreach ($this->grupos as $grupo) { ?> 
                                    <tr>
                                        <td><input type="checkbox" name="lista" id="lista" class="lista_usuarios" /></td>
                                        <td><?php echo $grupo->descricao; ?></td>
                                    </tr>
<?php } ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="span1">
                            <div class="row">
                            <a href="#" id="seta_direita" class="btn btn-block">
                                <i class="icon-arrow-right"></i>
                                <div>
                                Direita
                                </div>
                            </a>
                            </div>
                            <br />
                            <div class="row">
                            <a href="#" id="seta_esquerda" class="btn btn-block">
                                <i class="icon-arrow-left"></i>
                                <div>
                                Esquerda
                                </div>
                            </a>                            
                                </div>
                        </div>
                        <div class="span5">
                            <table class="table table-striped table-bordered direita">
                                <thead>
                                    <tr>
                                        <th width="20px"><input type="checkbox" name="ck_usuarios_grupo" id="ck_usuarios_grupo" class="ck-marca-todos" rel="lista_usuarios_grupo" /></th>
                                        <th><label for="ck_usuarios_grupo">Grupos que Pertencem ao usuário:</label></th>
                                    </tr>
                                </thead>
                                <tbody>
<?php 
if ($this->usuario_grupos) { 
    foreach ($this->usuario_grupos as $grupo) { 
?> 
                                    <tr>
                                        <td><input type="checkbox" name="lista" id="lista" class="lista_usuarios_grupo" /></td>
                                        <td><?php echo $grupo->descricao; ?></td>
                                    </tr>
<?php }} ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</div>