<?php $tb = new TbUsuario(); ?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <div class="well well-small" id="idPesquisa">
                    <fieldset>
                        <legend>Opções de Pesquisa</legend>
                        <div class="control-group">
                            <label for="filtro_cpf" class="control-label">C.P.F.:</label>
                            <div class="controls">
                                <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->getRequest()->getPost("filtro_cpf"); ?>" class="filtro cpf span2"  />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_nome" class="control-label">Nome:</label>
                            <div class="controls">
                                <input type="text" class="filtro span5" name="filtro_nome" id="filtro_nome" value="<?php echo $this->getRequest()->getPost("filtro_nome"); ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                            </div>
                        </div>
                    </fieldset>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>C.P.F.</th>
                            <th>Nome</th>
                            <th>E-Mail</th>
                            <th>Situação</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) {
                    $usuario = $tb->getPorId($registro["id_usuario"]);
                    $pf = $usuario->getPessoaFisica();
            ?>
                        <tr>
                            <td width="40px">
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                                    <?php echo $usuario->getId(); ?>
                                </a>
                            </td>
                            <td width="120px">
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                                <?php echo $this->formatCpf($pf->cpf); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                                <?php echo $pf->nome; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                                <?php echo $pf->getPessoa()->email; ?>
                                </a>
                            </td>
                            <td width="250px">
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $usuario->getId())); ?>">
                                <?php echo $usuario->findParentRow("TbUsuarioSituacao")->descricao; ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $usuario->getId())); ?>" class="btn" title="Visualizar" data-toggle="tooltip">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $usuario->getId())); ?>" class="btn" title="Alterar" data-toggle="tooltip">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "grupos",
                                                                         "id" => $usuario->getId())); ?>" class="btn" title="Grupos" data-toggle="tooltip" >
                                        <i class="icon-group"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            </form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>