<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
<?php
$tvs = $this->transporte->pegaTransporteVeiculoAtivos();
if ($tvs && count($tvs)) {
?>
                        <div class="control-group">
                            <label for="filtro_id_transporte_veiculo" class="control-label">Veículo:</label>
                            <div class="controls">
                                <select name="filtro_id_transporte_veiculo" id="filtro_id_transporte_veiculo" class="span5 filtro">
                                    <option value="" <?php echo (!$this->dados["filtro_id_transporte_veiculo"])?"selected":""; ?>>==> SELECIONE <==</option>
<?php foreach ($tvs as $tv) { ?>
                                    <option value="<?php echo $tv->getId(); ?>" <?php echo ($this->dados["filtro_id_transporte_veiculo"] == $tv->getId())?"selected":""; ?>><?php echo $tv->toString(); ?></option>
<?php } ?>
                                </select>
                            </div>
                        </div>
<?php } ?>
<?php
$ctrl = new Escola_Form_Element_Select_Table("filtro_id_tarifa");
$ctrl->setPkName("id_tarifa");
$ctrl->setModel("TbTarifa");
$ctrl->setValue($this->dados["filtro_id_tarifa"]);
$ctrl->setLabel("Tarifa: ");
$ctrl->setAttrib("class", "span5 filtro");
echo $ctrl->render($this);
?>
                <div class="control-group">
                    <label for="filtro_data_inicio" class="control-label">Data Inicial:</label>
                    <div class="controls">
                        <input type="text" name="filtro_data_inicial" id="filtro_data_inicial" value="<?php echo $this->dados["filtro_data_inicial"]; ?>" class="span2 filtro data" />
                    </div>
                </div>                        
                <div class="control-group">
                    <label for="filtro_data_final" class="control-label">Data Final:</label>
                    <div class="controls">
                        <input type="text" name="filtro_data_final" id="filtro_data_final" value="<?php echo $this->dados["filtro_data_final"]; ?>" class="span2 filtro data" />
                    </div>
                </div>                        
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario">
            <div class="well well-small">
                <dl class="dl-horizontal">
                    <dt>Transporte: </dt>
                    <dd><?php echo $this->transporte->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Rota: </dt>
                    <dd><?php echo $this->rota->toString(); ?></dd>
                </dl>
            </div>
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>BDO</th>
                            <th>Data</th>
                            <th>Veículo</th>
                            <th>Tarifa</th>
                            <th>Hora Saída</th>
                            <th>Hora Chegada</th>
                            <th>Km Inicial</th>
                            <th>Km Final</th>
                            <th>Viagens</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
<?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
<?php 
    foreach ($this->registros as $registro) { 
        $view_url = $this->url(array("action" => "viewbdo", "id" => $registro->getId()));
        $txt_bdo = $txt_data = $txt_veiculo = $txt_tarifa = $txt_hora_saida = $txt_hora_chegada = $txt_km_inicial = $txt_km_final = $txt_viagens = "--";
        $txt_bdo = $registro->bdo;
        $txt_data = Escola_Util::formatData($registro->data_bdo);
        $tv = $registro->findParentRow("TbTransporteVeiculo");
        if ($tv) {
            $txt_veiculo = $tv->toString();
        }
        $to = $registro->findParentRow("TbTarifaOcorrencia");
        if ($to) {
            $txt_tarifa = $to->toString();
        }
        $txt_hora_saida = $registro->hora_saida;
        $txt_hora_chegada = $registro->hora_chegada;
        $txt_km_inicial = Escola_Util::number_format($registro->km_inicial);
        $txt_km_final = Escola_Util::number_format($registro->km_final);
        $txt_viagens = $registro->viagens;
?>
                        <tr>
                            <td><div class="text-center">
                                <a href="<?php echo $view_url; ?>">
                                    <?php echo $txt_bdo; ?>
                                </a></div>
                            </td>
                            <td><div class="text-center">
                                <a href="<?php echo $view_url; ?>">
                                    <?php echo $txt_data; ?>
                                </a></div>
                            </td>
                            <td>
                                <a href="<?php echo $view_url; ?>">
                                    <?php echo $txt_veiculo; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $view_url; ?>">
                                    <?php echo $txt_tarifa; ?>
                                </a>
                            </td>
                            <td><div class="text-center">
                                <a href="<?php echo $view_url; ?>">
                                    <?php echo $txt_hora_saida; ?>
                                </a></div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $view_url; ?>">
                                        <?php echo $txt_hora_chegada; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $view_url; ?>">
                                        <?php echo $txt_km_inicial; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $view_url; ?>">
                                        <?php echo $txt_km_final; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $view_url; ?>">
                                        <?php echo $txt_viagens; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $view_url; ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editarbdo",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirbdo",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
            </form>
        </div>
    </div>
</div>