<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "ocorrencia")); ?>" method="post" id="formulario" class="formulario">
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Transporte: </dt>
                        <dd><?php echo $this->transporte->toString(); ?></dd>
                    </dl>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th width="60px">Foto</th>
                            <th>Tipo</th>
                            <th>Pessoa</th>
                            <th>Status</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
                    <?php if ($this->registros && count($this->registros)) { ?>
                        <tbody>
                            <?php
                            foreach ($this->registros as $registro) {
                                $pessoa = $registro->findParentRow("TbPessoa");
                                $arquivo_foto = $pessoa->getFoto();
                            ?>
                                <input type="hidden" name="id_transporte_pessoa[]" id="id_transporte_pessoa" value="<?php echo $registro->getId(); ?>" />
                                <tr>
                                    <td>
                                        <?php if ($arquivo_foto) { ?>
                                            <a href="<?php echo $this->url(array("action" => "viewpessoa", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                                <img border="0" src="<?php echo $this->url(array("controller" => "arquivo", "action" => "show", "width" => "60", "id" => $arquivo_foto->getId())); ?>" alt="" />
                                            </a>
                                        <?php } ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "viewpessoa", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                            <?php echo $registro->findParentRow("TbTransportePessoaTipo")->toString(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "viewpessoa", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                            <?php echo $pessoa->toString(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "viewpessoa", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                            <?php echo $registro->mostrarStatus(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="<?php echo $this->url(array(
                                                            "controller" => $this->getRequest()->getControllerName(),
                                                            "action" => "viewpessoa",
                                                            "id_transporte" => $this->transporte->getId(), "id" => $registro->getId()
                                                        )); ?>" class="btn" title="Visualizar">
                                                <i class="icon-search"></i>
                                            </a>
                                            <a href="<?php echo $this->url(array(
                                                            "controller" => $this->getRequest()->getControllerName(),
                                                            "action" => "excluirpessoa",
                                                            "id_transporte" => $this->transporte->getId(), "id" => $registro->getId()
                                                        )); ?>" class="btn link_excluir" title="Excluir">
                                                <i class="icon-trash"></i>
                                            </a>

                                            <a href="<?php echo $this->url(array(
                                                            "controller" => $this->getRequest()->getControllerName(),
                                                            "action" => "ativar",
                                                            "id_transporte" => $this->transporte->getId(), "id" => $registro->getId()
                                                        )); ?>" class="btn link_confirma" title="Ativar">
                                                <i class="icon-thumbs-up"></i>
                                            </a>

                                            <a href="<?php echo $this->url(array(
                                                            "controller" => $this->getRequest()->getControllerName(),
                                                            "action" => "desativar",
                                                            "id_transporte" => $this->transporte->getId(), "id" => $registro->getId()
                                                        )); ?>" class="btn link_confirma" title="Desativar">
                                                <i class="icon-thumbs-down"></i>
                                            </a>

                                            <?php //if ($registro->ativo() && !$registro->motorista()) {
                                            if ($registro->ativo()) {
                                                /*
?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "carteira",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn" title="Emitir Carteira">
                                        <i class="icon-print"></i>
                                    </a>
<?php */
                                            } ?>
                                            <a href="<?php echo $this->url(array(
                                                            "controller" => $this->getRequest()->getControllerName(),
                                                            "action" => "licenca",
                                                            "tipo" => "TP", "id_transporte" => $this->transporte->getId(), "chave" => $registro->getId()
                                                        )); ?>" class="btn" title="Serviços">
                                                <i class="icon-copy"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    <?php } ?>
                </table>
                <?php if ($this->registros && count($this->registros)) {
                    echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
                }
                ?>
            </form>
        </div>
    </div>
</div>