<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
                <input type="hidden" name="id_transporte" id="id_transporte" value="<?php echo $this->registro->id_transporte; ?>" />
                <div class="well well-small">
                    <fieldset>
                        <legend>ATRIBUIR PLACA DE VEÍCULO: </legend>
                        <dl class="dl-horizontal">
                            <dt>Transporte:</dt>
                            <dd><?php echo $this->transporte->toString(); ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Veículo:</dt>
                            <dd><?php echo $this->veiculo->toString(); ?></dd>
                        </dl>
                        <div class="control-group">
                            <label for="placa" class="control-label">Número da Placa:</label>
                            <div class="controls">
                                <input type="text" name="placa" id="placa" value="" class="span2" />
                            </div>
                        </div>                        
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>