<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
                <div class="control-group">
                    <label for="filtro_placa" class="control-label">Placa do Veículo:</label>
                    <div class="controls">
                        <input type="text" name="filtro_placa" id="filtro_placa" value="<?php echo $this->dados["filtro_placa"]; ?>" class="span2 filtro" />
                    </div>
                </div>                        
                <div class="control-group">
                    <label for="filtro_chassi" class="control-label">Número do Chassi:</label>
                    <div class="controls">
                        <input type="text" name="filtro_chassi" id="filtro_chassi" value="<?php echo $this->dados["filtro_chassi"]; ?>" class="span3 filtro" />
                    </div>
                </div>                        
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "veiculo")); ?>" method="post" id="formulario" class="formulario">
            <div class="well well-small">
                <dl class="dl-horizontal">
                    <dt>Transporte: </dt>
                    <dd><?php echo $this->transporte->toString(); ?></dd>
                </dl>
            </div>
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Data Cadastro</th>
                            <th>Tipo</th>
                            <th>Chassi</th>
                            <th>Placa</th>
                            <th>Fabricante</th>
                            <th>Modelo</th>
                            <th>Estado</th>
                            <th>Município</th>
                            <th>Status</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
<?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
<?php 
    foreach ($this->registros as $registro) { 
        $veiculo = $registro->findParentRow("TbVeiculo");
?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_cadastro); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->findParentRow("TbVeiculoTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->chassi; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->mostrar_placa(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->findParentRow("TbFabricante")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->modelo; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->findParentRow("TbUf")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $veiculo->findParentRow("TbMunicipio")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewveiculo", "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbTransporteVeiculoStatus")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "viewveiculo",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editarveiculo",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn" title="Alterar Veículo">
                                        <i class="icon-cog"></i>
                                    </a>
<?php if ($registro->ativo()) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirveiculo",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "baixa",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn" title="Baixa">
                                        <i class="icon-thumbs-down"></i>
                                    </a>
<?php if ($veiculo->sem_placa()) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "placa",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn" title="Atribuir Placa do Veículo">
                                        <i class="icon-edit-sign"></i>
                                    </a>
<?php } ?>
<?php } ?>
<?php if ($registro->baixa()) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "cancelarbaixa",
                                                                         "id_transporte" => $this->transporte->getId(), "id" => $registro->getId())); ?>" class="btn link_confirma" title="Cancelar Baixa">
                                        <i class="icon-remove-circle"></i>
                                    </a>
<?php } ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "licenca",
                                                                         "tipo" => "TV", "id_transporte" => $this->transporte->getId(), "chave" => $registro->getId())); ?>" class="btn" title="Serviços">
                                        <i class="icon-copy"></i>
                                    </a>                                    
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
            </form>
        </div>
    </div>
</div>