<?php
$txt_tarifa = "--";
        $tarifa = $this->registro->pega_tarifa();
        if ($tarifa) {
            $txt_tarifa = $tarifa->toString();
        }
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Rota</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Codigo:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Transporte:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbTransporte")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo de Rota:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbRotaTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Linha:</dt>
                    <dd> <?php echo $this->registro->findParentRow("TbLinha")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tarifa:</dt>
                    <dd><?php echo $txt_tarifa; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Km:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->km); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tempo Total:</dt>
                    <dd> <?php echo $this->registro->tempo_total; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Velocidade Média (Km/h):</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->km_velocidade_media); ?></dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="row-fluid">
                  <?php 
        $tb_rd = new TbRotaDia();
        foreach ($this->dts as $dt) { 
            $veiculos = $viagens = 0;
            $rs = $tb_rd->listar(array("id_rota" => $this->registro->getId(), "id_dia_tipo" => $dt->getId()));
            if ($rs && count($rs)) {
                $rd = $rs->current();
                $veiculos = $rd->veiculos;
                $viagens = $rd->viagens;
            }
    ?>
    <div class="span4">
        <div class="well">
            <div class="page-header">
                <h4><?php echo $dt->toString(); ?></h4>
            </div>
            <dl class="dl-horizontal">
                <dt>Veículos:</dt>
                <dd><?php echo $veiculos; ?></dd>
            </dl>
            <dl class="dl-horizontal">
                    <dt>Viagens:</dt>
                    <dd><?php echo $viagens; ?></dd>
            </dl>
        </div>
    </div>
<?php } ?>
    </div>
</div>