<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Ponto de Onibus</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Codigo:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
<?php if ($this->transporte) { ?>
                <dl class="dl-horizontal">
                    <dt>Transporte:</dt>
                    <dd><?php echo $this->transporte->toString(); ?></dd>
                </dl>
<?php } ?>
<?php if ($this->rota) { ?>
                <dl class="dl-horizontal">
                    <dt>Rota:</dt>
                    <dd><?php echo $this->rota->toString(); ?></dd>
                </dl>
<?php } ?>
                <dl class="dl-horizontal">
                    <dt>Ordem:</dt>
                    <dd><?php echo $this->registro->ordem; ?></dd>
                </dl>
<?php
$op = $this->registro->findParentRow("TbOnibusParada");
if ($op) { 
?>
                <dl class="dl-horizontal">
                    <dt>Ponto de Onibus:</dt>
                    <dd><?php echo $op->toString(); ?></dd>
                </dl>
<?php } ?>
            </div>
        </div>
    </div>
</div>