<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Visualização de Transporte > Pessoa</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Id:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Transporte:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbTransporte")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbTransportePessoaTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Pessoa:</dt>
                    <dd><?php echo $this->pessoa->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Status:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbTransportePessoaStatus")->toString(); ?></dd>
                </dl>
            </div>
<?php echo $this->pessoa->mostrarTabelaNotificacao(); ?>
        </div>
    </div>
</div>