<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "setorsalvar")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->chamado_tipo->getId(); ?>" />
                <input type="hidden" name="jan_pagina" id="jan_pagina" />
                <input type="hidden" name="operacao" id="operacao" value="" />
                <input type="hidden" name="id_setor" id="id_setor" value="" />

<div id="janela_setor" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Localizar Setor</h3>
    </div>
    <div class="modal-body">
        <div class="well well-small">
            <fieldset>
                <div class="control-group">
                    <label for="jan_setor_criterio" class="control-label">Procurar Por:</label>
                    <div class="controls">
                        <input type="text" name="jan_setor_criterio" id="jan_setor_criterio" value="" class="span4" />
                    </div>
                </div>
            </fieldset>
        </div>
        <table id="lista_setor_resposta" class="table table-striped table-bordered">
            <thead>
                <th width="50px">ID</th>
                <th width="160px">Sigla</th>
                <th>Descrição</th>
            </thead>
            <tbody class="corpo_setor"></tbody>
        </table>        
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="button" value="Limpar Filtro" id="bt_setor_limpar" class="btn" />
        <input type="submit" value="Procurar" class="btn btn-primary" />
    </div>
</div>
                    
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Tipo de Chamado:</dt>
                        <dd><?php echo $this->chamado_tipo->toString(); ?></dd>
                    </dl>
                </div>
                
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Sigla</th>
                            <th>Descrição</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
            ?>
                        <tr>
                            <td>
                                    <?php echo $registro->sigla; ?>
                            </td>
                            <td>
                                <?php echo $registro->descricao; ?>
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirsetor",
                                                                         "id_setor" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            <?php //echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
            </form>
        </div>
    </div>
</div>