<div class="conteudo_controller">
	<div class="row-fluid">
		<div class="span12">
			<div class="well">
				<dl class="dl-horizontal">
					<dt>Módulo: </dt>
					<dd><?php echo $this->modulo_atual->toString(); ?></dd>
				</dl>
			</div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Descrição</th>
				<th>Action</th>
				<th>Principal</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->acaos) { ?>
		<tbody>
<?php 
	foreach ($this->acaos as $acao) { 
?>
			<tr>
				<td>
					<?php echo $acao->descricao; ?>
				</td>
				<td>
					<?php echo $acao->action; ?>
				</td>
				<td>
					<?php echo $acao->mostrarPrincipal(); ?>
				</td>
				<td width="20px">
					<div class="btn-group">	
						<a href="<?php echo $this->url(array("action" => "viewacao",
															 "id" => $acao->getId())); ?>" title="Visualizar" class="btn" data-toggle="tooltip">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("action" => "editaracao",
															 "id" => $acao->getId())); ?>" title="Editar" class="btn" data-toggle="tooltip">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("action" => "excluiracao",
															 "id" => $acao->getId())); ?>" id="ExcluirAcao" title="Excluir" class="btn link_excluir" data-toggle="tooltip">
							<i class="icon-trash"></i>
						</a>
					</div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
<?php echo $this->paginationControl($this->acaos, "sliding", "minha_paginacao_control.phtml"); ?>
		</div>
	</div>
</div>