<style type="text/css">
.badge-info {
	font-size: 25px;
}
</style>
<div class="conteudo_controller">
	<div class="row-fluid">
		<div class="span12">
			<div class="well">
<form action="<?php echo $this->url(array("controller" => "modulo", "action" => "editaracao")); ?>" method="post" id="formulario" class="formulario form-horizontal">
	<input type="hidden" name="id_modulo" id="id_modulo" value="<?php echo $this->modulo_atual->getId(); ?>" />
	<input type="hidden" name="id" id="id" value="<?php echo $this->acao_atual->getId(); ?>" />
	<fieldset>
		<legend>CADASTRO DE AÇÃO: </legend>
		<div class="well well-small">
			<dl class="dl-horizontal">
				<dt>Módulo</dt>
				<dd><?php echo $this->modulo_atual->toString(); ?></dd>
<?php if ($this->acao_atual->getId()) { ?>
				<dt>Código</dt>
				<dd><?php echo $this->acao_atual->getId(); ?></dd>
<?php } ?>
			</dl>
		</div>
		<div class="control-group">
			<label for="descricao" class="control-label">Descrição.:</label>
			<div class="controls">
				<input type="text" name="descricao" id="descricao" maxlength="60" value="<?php echo $this->acao_atual->descricao; ?>" />
			</div>
		</div>
		<div class="control-group">
			<label for="action" class="control-label">Action:</label>
			<div class="controls">
				<input type="text" name="action" id="action" maxlength="60" value="<?php echo $this->acao_atual->action; ?>" />
			</div>
		</div>
		<div class="control-group">
			<label for="principal" class="control-label">Principal:</label>
			<div class="controls">
				<select name="principal" id="principal">
					<option value="" <?php echo (!$this->acao_atual->principal)?"selected":""; ?> >==> SELECIONE <==</option>
					<option value="S" <?php echo ($this->acao_atual->principal == "S")?"selected":""; ?>>SIM</option>
					<option value="N" <?php echo ($this->acao_atual->principal == "N")?"selected":""; ?>>NÃO</option>
				</select>
			</div>
		</div>
	</fieldset>
</form>
			</div>
		</div>
	</div>
</div>