<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well">
                    <fieldset>
                        <legend>Cadastro de Relatório: </legend>
                <?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>Código:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
                <?php } ?>
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("id_relatorio_tipo");
                $ctrl->setModel("TbRelatorioTipo");
                $ctrl->setPkName("id_relatorio_tipo");
                $ctrl->setValue($this->registro->id_relatorio_tipo);
                $ctrl->setLabel("Tipo");
                echo $ctrl->render($this);
                ?>
                        <div class="control-group">
                            <label for="chave" class="control-label">Chave:</label>
                            <div class="controls">
                                <input type="text" name="chave" id="chave" maxlength="20" value="<?php echo $this->registro->chave; ?>" class="span2" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="descricao" class="control-label">Descrição:</label>
                            <div class="controls">
                                <textarea name="descricao" id="descricao" class="span5" rows="6"><?php echo $this->registro->descricao; ?></textarea>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>