<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
                <div class="control-group">
                    <label for="filtro_caracter" class="control-label">Auto de Infração:</label>
                    <div class="controls">
                        <input type="text" name="filtro_alfa" id="filtro_alfa" class="span1 filtro" value="<?php echo $this->dados["filtro_alfa"]; ?>" /><input type="text" name="filtro_codigo" id="filtro_codigo" size="5" value="<?php echo $this->dados["filtro_codigo"]; ?>" class="span2 filtro" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_placa" class="control-label">Placa:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2" name="filtro_placa" id="filtro_placa" value="<?php echo $this->dados["filtro_placa"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_chassi" class="control-label">Chassi:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2" name="filtro_chassi" id="filtro_chassi" value="<?php echo $this->dados["filtro_chassi"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_pf_nome" class="control-label">Nome do Motorista:</label>
                    <div class="controls">
                        <input type="text" class="filtro span6" name="filtro_pf_nome" id="filtro_pf_nome" value="<?php echo $this->dados["filtro_pf_nome"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_data_infracao" class="control-label">Data da Infração:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2 data" name="filtro_data_infracao" id="filtro_data_infracao" value="<?php echo $this->dados["filtro_data_infracao"]; ?>" />
                    </div>
                </div>
<?php 
$ctrl = new Escola_Form_Element_Select_Table("filtro_id_veiculo_retido_status");
$ctrl->setAttrib("class", "filtro");
$ctrl->setPkName("id_veiculo_retido_status");
$ctrl->setModel("TbVeiculoRetidoStatus");
$ctrl->setValue($this->dados["filtro_id_veiculo_retido_status"]);
$ctrl->setLabel("Status:");
echo $ctrl->render($this);
?>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Veículo</th>
                            <th>Data / Hora</th>
                            <th>Notificação</th>
                            <th>Status</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
<?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
<?php 
    foreach ($this->registros as $registro) { 
        $txt_id = $txt_veiculo = $txt_data_hora = $txt_notificacao = $txt_motorista = $txt_status = "--";
        $txt_id = $registro->getId();
        $veiculo = $registro->pegaVeiculo();
        if ($veiculo) {
            $txt_veiculo = $veiculo->toString();
        }
        $txt_data_hora = Escola_Util::formatData($registro->data_veiculo_retido) . " - " . $registro->hora_veiculo_retido;
        $not = $registro->pegaAutoInfracaoNotificacao();
        if ($not) {
            $txt_notificacao = $not->toString();
            $pf = $not->pegaPessoaFisica();
            if ($pf) {
                $txt_motorista = $pf->toString();
            }
        }
        $vrs = $registro->pegaVeiculoRetidoStatus();
        if ($vrs) {
            $txt_status = $vrs->toString();
        }
?>
                        <tr>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                        <?php echo $txt_id; ?>
                                    </a>
                                </div>
                            </td>                            
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $txt_veiculo; ?>
                                </a>
                            </td>                            
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                        <?php echo $txt_data_hora; ?>
                                    </a>
                                </div>
                            </td>                            
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $txt_notificacao; ?>
                                </a>
                            </td>                            
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $txt_status; ?>
                                </a>
                            </td>                            
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
<?php if ($registro->aguardando_liberacao()) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "liberar",
                                                                         "id" => $registro->getId())); ?>" class="btn link_confirma" title="Liberar Veículo">
                                        <i class="icon-road"></i>
                                    </a>
<?php } ?>
<?php if ($registro->liberado()) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "cancelarliberar",
                                                                         "id" => $registro->getId())); ?>" class="btn link_confirma" title="Cancelar Liberação do Veículo">
                                        <i class="icon-remove-sign"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "emitir",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Emitir Documento de Liberação">
                                        <i class="icon-print"></i>
                                    </a>
<?php } ?>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>