<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
	<input type="hidden" name="ponto_id_funcionario" id="ponto_id_funcionario" value="" />
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Código</th>
				<th>Sigla</th>  
				<th>Descrição</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->codigo; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->sigla; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->descricao; ?>
                    </a>
				</td>
				
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
									 "action" => "editar",
									 "id" => $registro->getId())); ?>" class="btn" title="Alterar">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluir",
															 "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
							<i class="icon-trash"></i>
						</a>
						
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>