<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
                <div class="control-group">
                    <label for="filtro_titulo" class="control-label">Título:</label>
                    <div class="controls">
                        <input type="text" name="filtro_titulo" id="filtro_titulo" class="span5 filtro" value="<?php echo $this->dados["filtro_titulo"]; ?>" />
                    </div>
                </div>
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("filtro_id_pessoa_tipo");
                $ctrl->setAttrib("class", "filtro");
                $ctrl->setPkName("id_pessoa_tipo");
                $ctrl->setModel("TbPessoaTipo");
                $ctrl->setValue($this->dados["filtro_id_pessoa_tipo"]);
                $ctrl->setLabel("Tipo de Pessoa:");
                echo $ctrl->render($this);
                ?>
                <div class="control-group linha_cpf">
                    <label for="filtro_cpf" class="control-label">C.P.F.:</label>
                    <div class="controls">
                        <input type="text" name="filtro_cpf" id="filtro_cpf" class="span2 cpf filtro" value="<?php echo $this->dados["filtro_cpf"]; ?>" />
                    </div>
                </div>
                <div class="control-group linha_cnpj">
                    <label for="filtro_cnpj" class="control-label">C.N.P.J.:</label>
                    <div class="controls">
                        <input type="text" name="filtro_cnpj" id="filtro_cnpj" class="span2 cnpj filtro" value="<?php echo $this->dados["filtro_cnpj"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_nome" class="control-label">Nome:</label>
                    <div class="controls">
                        <input type="text" name="filtro_nome" id="filtro_nome" class="span5 filtro" value="<?php echo $this->dados["filtro_nome"]; ?>" />
                    </div>
                </div>
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("filtro_id_servico_solicitacao_status");
                $ctrl->setAttrib("class", "filtro");
                $ctrl->setPkName("id_servico_solicitacao_status");
                $ctrl->setModel("TbServicoSolicitacaoStatus");
                $ctrl->setValue($this->dados["filtro_id_servico_solicitacao_status"]);
                $ctrl->setLabel("Status:");
                echo $ctrl->render($this);
                ?>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "licenca")); ?>" method="post" id="formulario" class="formulario">
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Serviço: </dt>
                        <dd><?php echo $this->servico->toString(); ?></dd>
                    </dl>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Pessoa</th>
                            <th>Número/Ano</th>
                            <th>Referência</th>
                            <th>Data Solicitação</th>
                            <th>Vencimento</th>
                            <th>Valor</th>
                            <th>Valor Pago</th>
                            <th>Início</th>
                            <th>Validade</th>
                            <th>Status</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
                    <?php if ($this->registros && count($this->registros)) { ?>
                        <tbody>
                            <?php
                            foreach ($this->registros as $registro) {
                                $ss = $registro->pegaSolicitacao();
                                $pessoa = $registro->findParentRow("TbPessoa");
                                $ssp = $ss->pegaPagamento();
                                ?>
                                <tr>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo $registro->titulo; ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo $pessoa->toString(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo $ss->mostrar_numero(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo $ss->mostrar_referencia(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo Escola_Util::formatData($ss->data_solicitacao); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo Escola_Util::formatData($ss->data_vencimento); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo $ss->pega_valor()->toString(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo ($ssp) ? $ssp->pega_valor_pago()->toString() : "--"; ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo Escola_Util::formatData($ss->data_inicio); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo Escola_Util::formatData($ss->data_validade); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                            <?php echo $ss->mostrarStatusHTML(); ?>
                                        </a>
                                    </td>
                                    <td>
                                        <div class="btn-group">	
                                            <a href="<?php
                                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                "action" => "view",
                                                "id" => $registro->getId()));
                                            ?>" class="btn" title="Visualizar">
                                                <i class="icon-search"></i>
                                            </a>
                                            <a href="<?php
                                            echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                "action" => "editar",
                                                "id" => $registro->getId()));
                                            ?>" class="btn" title="Editar">
                                                <i class="icon-cog"></i>
                                            </a>
                                               <?php if ($ss->pago()) { ?>
                                                    <a href="<?php
                                                    echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                        "action" => "emitir",
                                                        "id" => $registro->getId()));
                                                    ?>" class="btn" title="Emitir Documento">
                                                        <i class="icon-print"></i>
                                                    </a>
                                            <?php } else { ?>
                                                <a href="<?php
                                                   echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                       "action" => "excluir",
                                                       "id" => $registro->getId()));
                                                   ?>" class="btn link_excluir" title="Excluir">
                                                    <i class="icon-trash"></i>
                                                </a>
                                                <a target="_blank" href="<?php
                                                   echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                       "action" => "boleto",
                                                       "id" => $registro->getId()));
                                                   ?>" class="btn" title="Gerar Boleto">
                                                    <i class="icon-credit-card"></i>
                                                </a>
                                                <a href="<?php
                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                    "action" => "licencapgto",
                                    "id" => $registro->getId()));
                                ?>" class="btn" title="Confirmar Pagamento">
                                                    <i class="icon-money"></i>
                                                </a>
        <?php } ?>
                                        </div>
                                    </td>
                                </tr>
    <?php } ?>
                        </tbody>
<?php } ?>
                </table>
<?php
if ($this->registros && count($this->registros)) {
    echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
            </form>
        </div>
    </div>
</div>