<?php
$valor_a_pagar = $this->registro->pega_valor();
$tb = new TbMoeda();
$moeda = $tb->pega_padrao();
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "licencapgto")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id_servico_solicitacao" id="id_servico_solicitacao" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well well-small">
                    <fieldset>
                        <legend>CONFIRMAR PAGAMENTO DE SERVIÇO: </legend>
                        <dl class="dl-horizontal">
                            <dt>Informações da Interdição:</dt>
                            <dd><?php echo $this->interdicao->toString(); ?></dd>
                        </dl>
<?php if ($this->pessoa) { ?>
                        <dl class="dl-horizontal">
                            <dt>Pessoa:</dt>
                            <dd><?php echo $this->pessoa->toString(); ?></dd>
                        </dl>
<?php } ?>
                        <dl class="dl-horizontal">
                            <dt>Serviço:</dt>
                            <dd><?php echo $this->stg->findParentRow("TbServico")->toString(); ?></dd>
                        </dl>                        
                        <dl class="dl-horizontal">
                            <dt>Referência:</dt>
                            <dd><?php echo $this->registro->mostrar_referencia(); ?></dd>
                        </dl>                        
                        <dl class="dl-horizontal">
                            <dt>Valor:</dt>
                            <dd><?php echo $valor_a_pagar->toString(); ?></dd>
                        </dl>                        
                        <div class="control-group">
                            <label for="data_pagamento" class="control-label">Data Pagamento:</label>
                            <div class="controls">
                                <input type="text" name="data_pagamento" id="data_pagamento" class="span2 data" value="<?php echo date("d/m/Y"); ?>" />
                            </div>
                        </div>
<?php
$ctrl = new Escola_Form_Element_Valor("valor_pago");
$ctrl->setLabel("Valor Pago:");
$ctrl->setValue($valor_a_pagar->valor);
if ($moeda) {
    $ctrl->set_moeda($moeda);
}
echo $ctrl->render($this);
$ctrl = new Escola_Form_Element_Valor("valor_juros");
$ctrl->setLabel("Juros:");
$ctrl->setValue(0);
if ($moeda) {
    $ctrl->set_moeda($moeda);
}
echo $ctrl->render($this);
$ctrl = new Escola_Form_Element_Valor("valor_desconto");
$ctrl->setLabel("Desconto:");
$ctrl->setValue(0);
if ($moeda) {
    $ctrl->set_moeda($moeda);
}
echo $ctrl->render($this);
?>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>