<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<table class="table table-striped table-bordered">
	<tr>
		<th colspan="8">EMISSÃO DE CONTRA-CHEQUE</th>
	</tr>
				<tr>
					<td rowspan="2" colspan="2" align="center">
						<img src="<?php echo Escola_Util::getBaseUrl(); ?>/img/logo_santana.jpg" alt="" height="100" />
					</td>
					<td colspan="6">
						<div align="center"><strong>COMPROVANTE DE RENDIMENTOS</strong></div>
						<div align="center">PREFEITURA MUNICIPAL DE SANTANA</div>
					</td>
				</tr>
				<tr>
					<td>
						<div>CNPJ</div>
						<div class="negrito">23.066.640/0001-08</div>
					</td>
					<td>REG. JURÍDICO</td>
					<td colspan="2">
						<div>SITUAÇÃO DO SERVIDOR</div>
						<div class="negrito">Ativo</div>
					</td>
					<td>
						<div>UF</div>
						<div class="negrito">AP</div>
					</td>
					<td>
						<div>EXERCÍCIO / LOCAL</div>
						<div class="negrito"><?php echo $this->ano; ?></div>
					</td>
				</tr>
				<tr>
					<td colspan="7">
						<div>NOME DO SERVIDOR</div>
						<div class="negrito"><?php echo $this->funcionario->NOME; ?></div>
					</td>
					<td align="center">
						<div>MATRÍCULA</div>
						<div class="negrito"><?php echo $this->funcionario->FUNCIONARIOS; ?></div>
					</td>
				</tr>
				<tr>
					<td colspan="5">
						<div>CATEGORIA CARREIRA</div>
						<div class="negrito"><?php echo $this->funcionario->NOME_FUNCAO; ?></div>
					</td>
					<td>CLASSE</td>
					<td>
						<div>DATA ADMISSÃO</div>
						<div class="negrito"><?php echo Escola_Util::formatData($this->funcionario->DATAADMISSAO); ?></div>
					</td>
					<td>
						<div>CBO</div>
						<div class="negrito"><?php echo $this->funcionario->CBO; ?></div>
					</td>
				</tr>
				<tr>
					<td>DEP S.F</td>
					<td>DEP I.R</td>
					<td>T.S (%)</td>
					<td>
						<div>CPF</div>
						<div class="negrito"><?php echo Escola_Util::formatCpf($this->funcionario->CPF); ?></div>
					</td>
					<td>
						<div>BANCO</div>
						<div class="negrito"><?php echo ($this->conta)?$this->conta->BANCOS:""; ?></div>
					</td>
					<td>
						<div>AGÊNCIA</div>
						<div class="negrito">
<?php
$agencia = "";
if ($this->conta) { 
	$this->conta->AGENCIA_NUMERO;
	if (trim($this->conta->AGENCIA_DIGITO)) {
		$agencia .= "-" . $this->conta->AGENCIA_DIGITO;
	} 
}
echo $agencia;
?>
						</div>
					</td>
					<td>
						<div>CONTA CORRENTE</div>
						<div class="negrito">
<?php
$conta = "";
if ($this->conta) {
	$conta = $this->conta->CONTA_NUMERO;
	if (trim($this->conta->CONTA_DIGITO)) {
		$conta .= "-" . $this->conta->CONTA_DIGITO;
	} 
}
echo $conta;
?>
						</div>
					</td>
					<td>
						<div>MÊS PAGAMENTO</div>
						<div class="negrito"><?php echo Escola_Util::pegaMes((int)$this->mes); ?> / <?php echo $this->ano; ?></div>
					</td>
				</tr>
				<tr>
					<td colspan="7">
						<div>SETOR</div>
						<div class="negrito"><?php echo $this->funcionario->SETORES; ?>-<?php echo $this->funcionario->SETOR_NOME; ?></div>
					</td>
					<td>
						<div>IDENTIFICAÇÃO ÚNICA</div>
						<div class="negrito"><?php echo $this->funcionario->NUMERORG; ?></div>
					</td>
				</tr>
			</table>
			<table class="table table-striped table-bordered">
				<tr>
					<th width="100px">Tipo</th>
					<th>Discriminação</th>
					<th width="150px">Qtd / Fator</th>
					<th>Valor</th>
				</tr>
<?php 
$dados = array("fgts" => 0, 
			   "bruto" => 0,
			   "desconto" => 0, 
				"irpf" => 0);
$vencimento = 0;
if ($this->items) {
	foreach ($this->items as $item) {
		if ($item->EVENTOS == 1) {
			$vencimento = $item->VALOR;
		}
		if ($item->TIPOEVENTOS == 1) {
			$dados["bruto"] += $item->VALOR;
		} else {
			$dados["desconto"] += $item->VALOR;
		}
?>
				<tr>
					<td align="center" class="negrito"><?php echo $item->TIPOEVENTOS; ?></td>
					<td align="left" class="negrito"><?php echo $item->EVENTO_NOME; ?></td>
					<td align="center" class="negrito"><?php echo $item->QTD; ?>/<?php echo $item->FATOR; ?></td>
					<td align="right" class="negrito"><?php echo Escola_Util::number_format($item->VALOR); ?></td>
				</tr>
<?php }}
$liquido = $dados["bruto"] - $dados["desconto"];
?>
			</table>
			<table class="table table-striped table-bordered">
				<tr>
					<td width="25%">
						<div>BASE DE CÁLCULO DO TETO</div>
						<div class="negrito direita">xxxxxxxxxxxxxxx</div>
					</td>
					<td width="25%">
						<div>DEPÓSITO FGTS</div>
						<div class="negrito direita"><?php echo Escola_Util::number_format($dados["fgts"]); ?></div>
					</td>
					<td class="borda"  width="25%">
						<div>BRUTO</div>
						<div class=" direita"><?php echo Escola_Util::number_format($dados["bruto"]); ?></div>
					</td>
					<td class="borda" width="25%">
						<div>DESCONTO</div>
						<div class=" direita"><?php echo Escola_Util::number_format($dados["desconto"]); ?></div>
					</td>
				</tr>
				<tr>
					<td>
						<div>BASE DE CÁLCULO DO IRPF</div>
						<div class="negrito direita"><?php echo Escola_Util::number_format($dados["bruto"]); ?></div>
					</td>
					<td>
						<div>MARGEM CONSIGNÁVEL 30%</div>
						<div class="negrito direita">
<?php
$margem_30 = (($liquido * 30) / 100);
$margem_70 = (($liquido * 70) / 100);
echo Escola_Util::number_format($margem_30); 
?>
						</div>
					</td>
					<td>
						<div>MARGEM CONSIGNÁVEL 70%</div>
						<div class="negrito direita"><?php echo Escola_Util::number_format($margem_70); ?></div>
					</td>
					<td class="borda cor">
						<div>LÍQUIDO</div>
						<div class="negrito direita"><?php echo Escola_Util::number_format($liquido); ?></div>
					</td>
				</tr>
			</table>
			<table class="table table-striped table-bordered">
				<tr>
					<th colspan="3">DEMONSTRATIVO DE PAGAMENTO DE SALÁRIO</th>
				</tr>
				<tr>
					<td>
						<div>VENCIMENTO BÁSICO</div>
						<div class="negrito direita"><?php echo Escola_Util::number_format($vencimento); ?></div>
					</td>
					<td>
						<div>VANT. CALCULADAS S/VENC. BÁSICO</div>
						<div class="negrito direita">xxxxxxxxxxxxxxx</div>
					</td>
					<td>
						<div>FUNÇÃO (ATIVOS)</div>
						<div class="negrito direita">xxxxxxxxxxxxxxx</div>
					</td>
				</tr>
				<tr>
					<td>
						<div>VANTAGEM PESSOAL (DÉCIMO)</div>
						<div class="negrito direita">xxxxxxxxxxxxxxx</div>
					</td>
					<td>
						<div>VANTAGEM DECISÕES JUDICIAIS</div>
						<div class="negrito direita">xxxxxxxxxxxxxxx</div>
					</td>
					<td>
						<div>OUTRAS VANTAGENS</div>
						<div class="negrito direita">xxxxxxxxxxxxxxx</div>
					</td>
				</tr>
				<tr>
					<td colspan="3" align="center" class="negrito">DPRH - RECURSOS HUMANOS</td>
				</tr>
				<tr>
					<td colspan="3" align="center"> </td>
				</tr>
			</table>
        </div>
    </div>
</div>