<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well well-small">
                <dl class="dl-horizontal">
                    <dt>Nosso Número:</dt>
                    <dd><?php echo $this->registro->pegaNossoNumero(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Cendente:</dt>
                    <dd><?php echo $this->registro->mostrarCedente(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor Total:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->pegaValor()); ?></dd>
                </dl>
<?php
$txt_data_pagamento = "--";
$txt = $this->registro->getDataPagamento();
if ($txt) {
    $txt_data_pagamento = Escola_Util::formatData($txt);

?>
                <dl class="dl-horizontal">
                    <dt>Data de Pagamento:</dt>
                    <dd><?php echo $txt_data_pagamento; ?></dd>
                </dl>
<?php } ?>
            </div>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Tipo</th>
                        <th>Referência</th>
                        <th>Valor</th>
                        <th>Status do Pagamento</th>
                    </tr>
                </thead>
                <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
                        <?php
                        $contador = 0;
                        foreach ($this->registros as $registro) {
                            $contador++;
                            $txt_status_pagamento = $tipo = $referencia = $valor = "--";
                            $bt = $registro->findParentRow("TbBoletoItemTipo");
                            if ($bt) {
                                $tipo = $bt->toString();
                            }
                            $ref = $registro->pegaReferencia();
                            if ($ref) {
                                $referencia = $ref->toString();
                                $sss = $ref->pegaServicoSolicitacaoStatus();
                                if ($sss) {
                                    $txt_status_pagamento = $sss->toString();
                                }
                            }
                            $valor = Escola_Util::number_format($registro->valor);
                            ?>
                            <tr>
                                <td><?php echo $contador; ?></td>
                                <td><?php echo $tipo; ?></td>
                                <td><?php echo $referencia; ?></td>
                                <td><div class="text-center"><?php echo $valor; ?></div></td>
                                <td><?php echo $txt_status_pagamento; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                <?php } ?>
            </table>
        </div>
    </div>
</div>