<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Tarifa</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição:</dt>
                    <dd><?php echo $this->registro->descricao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor da Tarifa :</dt>
                    <dd><?php echo $this->registro->pega_valor()->toString(); ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>