<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
<?php 
$ctrl = new Escola_Form_Element_Select_Table("filtro_id_transporte_grupo");
$ctrl->setAttrib("class", "filtro");
$ctrl->setPkName("id_transporte_grupo");
$ctrl->setModel("TbTransporteGrupo");
$ctrl->setValue($this->dados["filtro_id_transporte_grupo"]);
$ctrl->setLabel("Grupo de Transporte:");
echo $ctrl->render($this);
?>
                <div class="control-group">
                    <label for="filtro_matricula" class="control-label">Matrícula:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2" name="filtro_matricula" id="filtro_matricula" value="<?php echo $this->dados["filtro_matricula"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_cpf" class="control-label">C.P.F.:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2 cpf" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_nome" class="control-label">Nome:</label>
                    <div class="controls">
                        <input type="text" class="filtro span5" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Grupo de Transporte</th>
                            <th>Data Cadastro</th>
                            <th>Matrícula</th>
                            <th>C.P.F.</th>
                            <th>Nome</th>
                            <th>Número CNH</th>
                            <th>Categoria CNH</th>
                            <th>Validade CNH</th>
                            <th>Status</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) {
                    $pm = $registro->findParentRow("TbPessoaMotorista");
                    $pf = $pm->findParentRow("TbPessoaFisica");
                    $cnh_categoria = $pm->findParentRow("TbCnhCategoria");
                    $tg = $registro->findParentRow("TbTransporteGrupo");
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $tg->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_cadastro); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->matricula; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $pf->mostrar_documento(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $pf->mostrar_nome(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $pm->cnh_numero; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $cnh_categoria->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($pm->cnh_validade); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->mostrarStatus(); ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                        "action" => "editar",
                                        "id" => $registro->getId()));
                                    ?>" class="btn" title="Alterar">
                                                <i class="icon-cog"></i>
                                            </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
<!--
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "carteira",
                                                                         "id" => 0, "id_motorista" => $registro->getId())); ?>" class="btn" title="Carteiras">
                                        <i class="icon-list-alt"></i>
                                    </a>
-->
<a href="<?php echo $this->url(array(
                                                                "controller" => "arquivo",
                                                                "action" => "index",
                                                                "id_motorista" => $registro->getId(),
                                                                "id" => 0
                                                            )); ?>" class="btn" title="Arquivos">
                                            <i class="icon-folder-open-alt"></i>
                                        </a>

                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "licenca",
                                                                         "id_motorista" => $registro->getId(),
                                                                         "id" => 0)); ?>" class="btn" title="Serviços">
                                        <i class="icon-copy"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "relatorio",
                                                                         "id_motorista" => $registro->getId(),
                                                                         "id" => 0)); ?>" class="btn" title="Relatórios">
                                        <i class="icon-print"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>