<?php 
$motorista = $this->motorista;
$tg = $motorista->getTransporteGrupo();
if ($tg) {
    $txt_transporte_grupo = $tg->toString();
}
?>
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
    <input type="hidden" name="id_motorista" id="id_motorista" value="<?php echo $this->motorista->getId(); ?>" />
    <?php if ($this->pessoa) { ?>
        <input type="hidden" name="id_pessoa" id="id_pessoa" value="<?php echo $this->pessoa->getId(); ?>" />
    <?php } ?>
    <div class="conteudo_controller">
        <div class="row-fluid">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("filtro_id_servico");
                $ctrl->setAttrib("class", "filtro");
                $ctrl->setPkName("id_servico");
                $ctrl->setModel("TbServico");
                $ctrl->setValue($this->dados["filtro_id_servico"]);
                $ctrl->setLabel("Serviço:");
                echo $ctrl->render($this);
                ?>
                <div class="control-group">
                    <label for="filtro_ano_referencia" class="control-label">Ano Referência:</label>
                    <div class="controls">
                        <input type="text" name="filtro_ano_referencia" id="filtro_ano_referencia" class="span1 filtro" value="<?php echo $this->dados["filtro_ano_referencia"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_mes_referencia" class="control-label">Mês Referência:</label>
                    <div class="controls">
                        <select name="filtro_mes_referencia" id="filtro_mes_referencia" class="filtro">
                            <option value="" <?php echo (!$this->dados["filtro_mes_referencia"]) ? "selected" : ""; ?>>==> SELECIONE <==</option>
                            <?php
                            foreach (Escola_Util::pegaMeses() as $mes => $desc_mes) {
                                ?>
                                <option value="<?php echo $mes; ?>" <?php echo ($mes == $this->dados["filtro_mes_referencia"]) ? "selected" : ""; ?>><?php echo $desc_mes; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <?php
                $ctrl = new Escola_Form_Element_Select_Table("filtro_id_servico_solicitacao_status");
                $ctrl->setAttrib("class", "filtro");
                $ctrl->setPkName("id_servico_solicitacao_status");
                $ctrl->setModel("TbServicoSolicitacaoStatus");
                $ctrl->setValue($this->dados["filtro_id_servico_solicitacao_status"]);
                $ctrl->setLabel("Status:");
                echo $ctrl->render($this);
                ?>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "licenca")); ?>" method="post" id="formulario" class="formulario">
                    <div class="well well-small">
                        <dl class="dl-horizontal">
                            <dt>Transporte: </dt>
                            <dd><?php echo $txt_transporte_grupo; ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Motorista: </dt>
                            <dd><?php echo $this->motorista->toString(); ?></dd>
                        </dl>
                    </div>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th><input type="checkbox" name="ck" id="ck" class="ck-marca-todos" rel="lista" /></th>
                                <th>Referência</th>
                                <th>Serviço</th>
                                <th>Número/Ano</th>
                                <th>Referência</th>
                                <th>Data Solicitação</th>
                                <th>Vencimento</th>
                                <th>Valor</th>
                                <th>Valor Pago</th>
                                <th>Início</th>
                                <th>Validade</th>
                                <th>Status</th>
                                <th width="20px">Operações</th>
                            </tr>
                        </thead>
                        <?php if ($this->registros && count($this->registros)) { ?>
                            <tbody>
                                <?php
                                foreach ($this->registros as $registro) {
                                    $stg = $registro->findParentRow("TbServicoTransporteGrupo");
                                    $tg = $stg->findParentRow("TbTransporteGrupo");
                                    $s = $stg->findParentRow("TbServico");
                                    $ssp = $registro->pegaPagamento();
                                    $ref = $registro->pegaReferencia();
                                    ?>
                                    <tr>
                                        <td>
                                            <?php if ($registro->aguardando_pagamento() && !$registro->vencida()) { ?>
                                                <input type="checkbox" name="lista[]" id="lista" class="lista" value="<?php echo $registro->getId(); ?>" />
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo $ref->toString(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo $s->toString(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo $registro->mostrar_numero(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo $registro->mostrar_referencia(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo Escola_Util::formatData($registro->data_solicitacao); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo Escola_Util::formatData($registro->data_vencimento); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo $registro->pega_valor()->toString(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo ($ssp) ? $ssp->pega_valor_pago()->toString() : "--"; ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo Escola_Util::formatData($registro->data_inicio); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo Escola_Util::formatData($registro->data_validade); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url(array("action" => "viewlicenca", "id" => $registro->getId())); ?>">
                                                <?php echo $registro->mostrarStatusHTML(); ?>
                                            </a>
                                        </td>
                                        <td>
                                            <div class="btn-group">	
                                                <a href="<?php
                                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                    "action" => "viewlicenca",
                                                    "id" => $registro->getId()));
                                                ?>" class="btn" title="Visualizar">
                                                    <i class="icon-search"></i>
                                                </a>
                                                <a href="<?php
                                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                    "action" => "licencaeditar","id" => $registro->getId()));
                                                ?>" class="btn" title="Editar">
                                                    <i class="icon-cog"></i>
                                                </a>
                                                <a target="_blank" href="<?php
                                                echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                    "action" => "solicitacaoservicodelete",
                                                    "id" => $registro->getId()));
                                                ?>" class="btn link_confirma" title="Excluir Solicitação">
                                                    <i class="icon-trash"></i>
                                                </a>
                                                   <?php if ($registro->pago()) { ?>
            <?php if ($registro->valido()) { ?>
                                                        <a href="<?php
                                                        echo $this->url(array("controller" => "transporte",
                                                            "action" => "emitir",
                                                            "id" => $registro->getId()));
                                                        ?>" class="btn" title="Emitir Documento">
                                                            <i class="icon-print"></i>
                                                        </a>
                                                    <?php } ?>
                                                   <?php } else { ?>
            <?php // if ($registro->cancelado() || $registro->aguardando_pagamento()) {  ?>
            <?php //}  ?>
                                                    <?php if ($registro->aguardando_pagamento()) { ?>
                                                        <a target="_blank" href="<?php
                                                           echo $this->url(array("controller" => "transporte",
                                                               "action" => "boleto",
                                                               "id" => $registro->getId()));
                                                           ?>" class="btn" title="Gerar Boleto">
                                                            <i class="icon-credit-card"></i>
                                                        </a>
                                                        <a href="<?php
                                                           echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                               "action" => "licencapgto",
                                                               "id" => $registro->getId()));
                                                           ?>" class="btn" title="Confirmar Pagamento">
                                                            <i class="icon-money"></i>
                                                        </a>
                                <?php } ?>
                            <?php } ?>
                                            </div>
                                        </td>
                                    </tr>
    <?php } ?>
                            </tbody>
<?php } ?>
                    </table>
<?php
if ($this->registros && count($this->registros)) {
    echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
                </form>
            </div>
        </div>
    </div>
</form>