<?php
$stg = $this->registro->findParentRow("TbServicoTransporteGrupo");
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Visualização de Motorista > Serviço</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Id:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Motorista:</dt>
                    <dd><?php echo $this->motorista->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Serviço:</dt>
                    <dd><?php echo $stg->findParentRow("TbServico")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Referência:</dt>
                    <dd><?php echo $this->registro->mostrar_referencia(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Data Solicitação:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_solicitacao); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Vencimento:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_vencimento); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor:</dt>
                    <dd><?php echo $stg->pega_valor()->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Início:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_inicio); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Validade:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_validade); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Status:</dt>
                    <dd><?php echo $this->registro->mostrarStatusHTML(); ?></dd>
                </dl>
            </div>
<?php
$pag = $this->pagamento;
if ($pag) {
?>
            <div class="well">
                <div class="page-header">
                    <h4>Pagamento</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Data do Pagamento:</dt>
                    <dd><?php echo Escola_Util::formatData($this->pagamento->data_pagamento); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor Pago:</dt>
                    <dd><?php echo $this->pagamento->pega_valor_pago()->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Juros:</dt>
                    <dd><?php echo $this->pagamento->pega_valor_juros()->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Desconto:</dt>
                    <dd><?php echo $this->pagamento->pega_valor_desconto()->toString(); ?></dd>
                </dl>
            </div>
<?php } ?>
        </div>
    </div>
</div>