<div class="span12">
    <div class="well">
    <h4>CONSELHO FISCAL</h4>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Profª.Ruth Helena Falesi P. de Moraes</td>
            </tr>
            <tr>
                <td>Prof. Manoel Sebastião Pereira de Carvalho</td>
            </tr>
            <tr>
              <td>Prof. Raimundo Aderson Lobão de Souza</td>
            </tr>
          </tbody>
      </table>
    </div>
</div>