<div class="span6">
    <div class="well">
        <h4>CONSELHO CURADOR</h4>
        <table class="table table-striped">
              <tbody>

                <tr>
                  <td>Moacir Cerqueira da Silva</td>
                </tr>
                <tr>
                    <td>Fernando Antônio Souza Bemerguis</td>
                </tr>
                <tr>
                  <td>Paulo Luiz Contente de Barros</td>
                </tr>
                <tr>
                  <td>José Maria Hesketh Condurú Neto</td>
                </tr>
                <tr>
                  <td>Luiz Gonzaga da Silva Costa</td>
                </tr>
                <tr>
                    <td>Emanuel Leal de Lima</td>
                </tr>
                <tr>
                    <td>Gundisalvo Piratoba Morales</td>
                </tr>

              </tbody>
          </table>
        </div>
</div>
<div class="span6">
    <div class="well">
        <h4>SUPLENTES</h4>
        <table class="table table-striped">
        <tbody>
          <tr>
            <td>Maria Rohane de Lima</td>
          </tr>
          <tr>
              <td>Emir Chaar El Husny</td>
          </tr>
          <tr>
            <td>Selma Tokoyo Ohashi</td>
          </tr>
          <tr>
              <td>Orlando Sigueo Ohashi</td>
          </tr>
          <tr>
              <td>Waldinei Travassos de Queiroz</td>
          </tr>
        </tbody>
    </table>
  </div>
</div>