<div class="span12">
    <div class="well">
    <h4>DIRETORIA EXECUTIVA</h4>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Carlos Albino Figueiredo de Magalhães ? Presidente</td>
            </tr>
            <tr>
                <td>Prof. Dr. Benedito Gomes dos Santos Filho ? Diretor Técnico</td>
            </tr>
            <tr>
              <td>Eng. Wilson José de Mello e Silva Maia ? Diretor Administrativo Financeiro</td>
            </tr>
          </tbody>
      </table>
    </div>
</div>