<div class="span6">
    <div class="well">
    <h4>Equipe</h4>
    <h5>Colaboradores:</h5>
    <table class="table table-striped">
        <tr>
            <td>Idelnir Vaz - Gerente Geral</td>
        </tr>
    </table>
    <h5>Setor Financeiro:</h5>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Jandira Bessa - Gerente Financeira</td>
            </tr>
            <tr>
                <td>Alrenice Machado</td>
            </tr>
            <tr>
              <td>Cleiton Sepeda</td>
            </tr>
            <tr>
              <td>Luziara Cota</td>
            </tr>
            <tr>
              <td>Rivaldo Teixeira</td>
            </tr>
         </tbody>
      </table>
    <h5>Setor jurídico:</h5>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Saulo Calandrini ? Assessor Jurídico</td>
            </tr>
            <tr>
                <td>Angela Fulco</td>
            </tr>
            <tr>
              <td>Nayara Souza</td>
            </tr>
         </tbody>
      </table>
    </div>
</div>
<div class="span6">
    <div class="well">
    <h5>Setor Contábil:</h5>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Allan do Nascimento</td>
            </tr>
            <tr>
                <td>Adriana Moura</td>
            </tr>
            <tr>
              <td>Eduardo Almeida</td>
            </tr>
            <tr>
              <td>Natasha Trindade</td>
            </tr>
         </tbody>
      </table>
    <h5>Setor de Assessoria Técnica e de Projetos:</h5>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Joely Machado ? Gerente de Projetos</td>
            </tr>
            <tr>
                <td>Erykah dos Anjos</td>
            </tr>
            <tr>
              <td>Karin Braga</td>
            </tr>
            <tr>
              <td>Ieda Costa</td>
            </tr>
         </tbody>
      </table>
    <h5>Apoio:</h5>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Leila da Silva</td>
            </tr>
            <tr>
                <td>Osmar Siqueira</td>
            </tr>                          
         </tbody>
      </table>
    </div>
</div>