<div class="span12">
    <div class="well">
    <h4>SÓCIOS COLABORADORES</h4>
    <table class="table table-striped">
          <tbody>

            <tr>
              <td>Sueo Numazawa</td>
            </tr>
            <tr>
                <td>Ruth Helena Falesi P. de Moraes</td>
            </tr>
            <tr>
              <td>Fernando Elias Rodrigues da Silva</td>
            </tr>
            <tr>
              <td>Fernando Sergio Valente Pinheiro</td>
            </tr>
            <tr>
              <td>Walmir Hugo dos Santos</td>
            </tr>

          </tbody>
      </table>
    </div>
</div>