<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <div class="well well-small" id="idPesquisa">
                    <fieldset>
                        <legend>Opções de Pesquisa</legend>
                        <div class="control-group">
                            <label for="filtro_operacao" class="control-label">Operação:</label>
                            <div class="controls">
                                <input type="text" class="filtro span2" name="filtro_operacao" id="filtro_operacao" value="<?php echo $this->dados["filtro_operacao"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_tabela" class="control-label">Tabela:</label>
                            <div class="controls">
                                <input type="text" class="filtro span5" name="filtro_tabela" id="filtro_tabela" value="<?php echo $this->dados["filtro_tabela"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_cpf" class="control-label">C.P.F.:</label>
                            <div class="controls">
                                <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" class="filtro cpf span2" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_nome" class="control-label">Nome:</label>
                            <div class="controls">
                                <input type="text" class="filtro span5" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_id" class="control-label">Identificador do Registro:</label>
                            <div class="controls">
                                <input type="text" class="filtro span1" name="filtro_id" id="filtro_id" value="<?php echo $this->dados["filtro_id"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_data_inicio" class="control-label">Data Início:</label>
                            <div class="controls">
                                <input type="text" class="filtro data span2" name="filtro_data_inicio" id="filtro_data_inicio" value="<?php echo $this->dados["filtro_data_inicio"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_data_final" class="control-label">Data Fim:</label>
                            <div class="controls">
                                <input type="text" class="filtro data span2" name="filtro_data_final" id="filtro_data_final" value="<?php echo $this->dados["filtro_data_final"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <input type="submit" value="Pesquisar" class="acao btn btn-primary"  />
                                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                            </div>
                        </div>
                    </fieldset>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Data / Hora</th>
                            <th>Operação</th>
                            <th>Tabela</th>
                            <th>C.P.F.</th>
                            <th>Usuário</th>
                            <th>Identificador Registro</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
                    $registro = TbLog::pegaPorId($registro["id_log"]);
                    $data = new Zend_Date($registro->data);
                    $txt_cpf = $txt_nome = "--";
                    if ($registro->cpf) {
                        $txt_cpf = Escola_Util::formatCpf($registro->cpf);
                    }
                    if ($registro->nome) {
                        $txt_nome = $registro->nome;
                    }
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $data->get("dd/MM/Y HH:mm:ss"); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbLogOperacao")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->tabela; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $txt_cpf; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $txt_nome; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->id; ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div align="center">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualiar" data-toogle="tooltip">
                                        <i class="icon-search"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            </form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>