<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well">
                    <div class="page-header">
                        <h4>Cadastro de Tipo de Relatório</h4>
                    </div>
                    <dl class="dl-horizontal">
                        <dt>Código:</dt>
                        <dd><?php echo $this->registro->getId(); ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Chave:</dt>
                        <dd><?php echo $this->registro->chave; ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Descrição:</dt>
                        <dd><?php echo $this->registro->descricao; ?></dd>
                    </dl>
                </div>
            </form>
        </div>
    </div>
</div>