<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "arquivo")); ?>" method="post" id="formulario" class="formulario">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Miniatura</th>
                            <th>Data Envio</th>
                            <th>Tamanho</th>
                            <th>Tipo</th>
                            <th>Tipo Documento</th>
                            <th>Número</th>
                            <th>Ano</th>
                            <th>Descrição</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
                    $documento = $registro->findParentRow("TbDocumento");
                    $arquivo = $documento->pega_arquivo();
                    $dt = $documento->findParentRow("TbDocumentoTipo");

                    $txt_numero = $txt_ano = "--";
                    if ($documento->numero) {
                        $txt_numero = $documento->numero;
                    }
                    if ($documento->ano) {
                        $txt_ano = $documento->ano;
                    }
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                    <?php echo $arquivo->miniatura(array("width" => 50, "align" => "left")); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($arquivo->data_upload); ?> <?php echo $arquivo->hora_upload; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo Escola_Util::mostrarTamanho($arquivo->tamanho); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo $dt->findParentRow("TbDocumentoTipoTarget")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo $dt->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo $txt_numero; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo $txt_ano; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo $documento->resumo; ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "viewarquivo",
                                                                         "id_documento_ref" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id_documento_ref" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id_documento_ref" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            <?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
            </form>
        </div>
    </div>
</div>