<div class="conteudo_controller">

    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name="jan_pagina" id="jan_pagina" value="" />
                <input type="hidden" name="operacao" id="operacao" value="<?php echo $this->operacao; ?>" />
            <?php if ($this->registro->getId()) { ?>
                <input type="hidden" name="id_documento_ref" id="id_documento_ref" value="<?php echo $this->registro->getId(); ?>" />
            <?php } ?>
                <div class="well">
                    <fieldset class="fieldset">
                        <legend>ARQUIVO: </legend>

            <?php if ($this->grupo_ano) { ?>
                        <input type="hidden" name="cadastro_ano" id="cadastro_ano" value="<?php echo $this->grupo_ano; ?>" />
            <?php } else { ?>
                        <div class="control-group linha_grupo_ano">
                            <label for="ano" class="control-label">Ano:</label>
                            <div class="controls">
                                <input type="text" name="cadastro_ano" id="cadastro_ano" class="span1" value="<?= $this->ano ?>" />
                            </div>
                        </div>                
            <?php } ?>

                <?php
                $tb = new TbDocumentoTipoTarget();
                $dtts = $tb->listar();
                if ($dtts) {
                    $id_dtt = 0;
                    if (isset($this->dados["id_documento_tipo_target"]) && $this->dados["id_documento_tipo_target"]) {
                        $id_dtt = $this->dados["id_documento_tipo_target"];
                    }
                ?>
                        <div class="control-group">
                            <label for="id_documento_tipo_target" class="control-label">Tipo:</label>
                            <div class="controls">
                                <select name="id_documento_tipo_target" id="id_documento_tipo_target">
                                    <option value="" <?php echo (!$id_dtt)?"selected":""; ?>>==> SELECIONE <==</option>
                    <?php foreach ($dtts as $dtt) { ?>
                    <?php if (!$dtt->normal()) { ?>
                                    <option value="<?php echo $dtt->getId(); ?>" <?php echo ($dtt->getId() == $id_dtt)?"selected":""; ?>><?php echo $dtt->toString(); ?></option>
                    <?php } ?>
                    <?php } ?>
                                </select>
                            </div>
                        </div>
                <?php } ?>
                
                        <div class="linha_documento_tipo control-group" style="display:none">
                            <label for="id_documento_tipo" class="control-label">Tipo de Documento:</label>
                            <div class="controls">
                                <select name="id_documento_tipo" id="id_documento_tipo">
                                </select>
                            </div>
                        </div>
                        
    <div id="janela_documento" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 id="myModalLabel">Localizar Documento</h4>
        </div>
        <div class="modal-body">
            <div class="well well-small">
                <fieldset>
                    <div class="control-group">
                        <label for="filtro_numero" class="control-label">Número / Ano:</label>
                        <div class="controls">
                            <input type="text" name="filtro_numero" id="filtro_numero" value="" class="filtro span1" /> / <input type="text" name="filtro_ano" id="filtro_ano" value="" class="filtro span1" />
                        </div>
                    </div>
                   
                    <div class="control-group">
                        <label for="filtro_resumo" class="control-label">Resumo:</label>
                        <div class="controls">
                            <textarea name="filtro_resumo" id="filtro_resumo" rows="5" class="filtro span5"></textarea>
                        </div>
                    </div>
                </fieldset>
            </div>
            <table id="documento_resposta" class="table table-striped table-bordered">
                <thead class="head_documento">
                    <th>ID</th>
                    <th>Data / Hora Criação</th>
                    <th>Tipo</th>
                    <th>Número</th>
                    <th>Resumo</th>
                </thead>
                <tbody class="corpo_documento"></tbody>
            </table>            
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
            <input type="button" value="ADICIONAR" class="btn" id="bt_documento_novo" />
            <input type="button" value="LIMPAR FILTRO" id="bt_documento_limpar" class="btn" />
            <input type="submit" value="PROCURAR" class="btn btn-primary" />
       </div>
    </div>
                        
                       <input type="hidden" name="id_documento" id="id_documento" value="<?php echo ($this->documento)?$this->documento->getId():""; ?>" />
                       
                        <div class="linha_documento control-group" style="display:none">
                            <label for="procedencia" class="control-label">Documento:</label>
                            <div class="controls">
                                <div class="input-append">
                                    <input type="text" name="show_documento" id="show_documento" value="<?php echo ($this->documento && $this->documento->getId())?$this->documento->toString():""; ?>" disabled class="input-xxlarge" />
                                    <div class="add-on">
                                        <a href="#" id="link_documento" title="Selecionar Documento">
                                            <i class="icon-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="linha_documento_cadastro control-group" style="display:none">
                            <label for="numero" class="control-label">Número:</label>
                            <div class="controls">
                                <input type="text" name="numero" id="numero" class="field span1" /> /             
                        <?php if ($this->grupo_ano) { ?>
                            <input type="hidden" name="ano" id="ano" value="<?php echo $this->grupo_ano; ?>" />
                            <?php echo $this->grupo_ano; ?>
                        <?php } else { ?>
                            <input type="text" name="ano" id="ano" class="field span1" />
                        <?php } ?>

                            <span id="txt_help_numero_ano"></span>
                            
                            </div>
                        </div>
                        <div class="linha_cadastro control-group">
                            <label for="resumo" class="control-label">Observações:</label>
                            <div class="controls">
                                <textarea name="resumo" id="resumo" rows="4" class="field span5"><?php echo ($this->documento)?$this->documento->resumo:""; ?></textarea>
                            </div>
                        </div>
                        <div class="linha_cadastro control-group">
                            <label for="localizacao_fisica" class="control-label">Localização Física:</label>
                            <div class="controls">
                                <textarea name="localizacao_fisica" id="localizacao_fisica" rows="4" class="field span5"><?php echo ($this->documento)?$this->documento->localizacao_fisica:""; ?></textarea>
                            </div>
                        </div>
                        <div class="linha_cadastro control-group">
                            <label for="arquivo" class="control-label">Arquivo:</label>
                            <div class="controls">
                                <input type="file" name="arquivo" id="arquivo" size="50" class="field" />
                            </div>
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

    var ajax_obj = false;

    <?php if (!$this->dtts->count()) { ?>
        var dtts = null;
    <?php } else { ?>
        var dtts = [];
    <?php 
        foreach ($this->dtts as $dtt) {
    ?>
            dtts.push({
                id: <?php echo $dtt->id_documento_tipo_target; ?>,
                chave: "<?php echo $dtt->chave; ?>",
                descricao: "<?php echo $dtt->descricao; ?>",

                normal: <?php echo $dtt->normal() ? "true" : "false"; ?>,
                administrativo: <?php echo $dtt->administrativo() ? "true" : "false"; ?>,
                pessoal: <?php echo $dtt->pessoal() ? "true" : "false"; ?>,
            });
    <?php
        }
    ?>
    <?php } ?>

    <?php if (!$this->dts->count()) { ?>
        var dts = null;
    <?php } else { ?>
        var dts = [];
    <?php 
        foreach ($this->dts as $dt) {
    ?>
            dts.push({
                id: <?php echo $dt->id_documento_tipo; ?>,
                chave: "<?php echo $dt->chave; ?>",
                descricao: "<?php echo $dt->descricao; ?>",
                id_dtt: <?php echo $dt->id_documento_tipo_target; ?>,
                possui_numero: <?php echo strtolower($dt->possui_numero) == "s" ? "true" : "false"; ?>
            });
    <?php
        }
    ?>
    <?php } ?>

    var id_documento_tipo = <?php echo $this->documento->id_documento_tipo ? $this->documento->id_documento_tipo : "null" ?>;
    <?php if ($this->grupo_ano) { ?>
    var grupo_ano = "<?php echo $this->grupo_ano; ?>";
    <?php } else { ?>
    var grupo_ano = "<?php echo $this->ano; ?>";
    <?php } ?>

    $(document).ready(
        function() {

            function _carregaTipoDocs(dtt) {

                if (!(dtt && dtt.id)) {
                    return null;
                }

                if (dtt.normal) {
                    return null;
                }

                var filtros = dts.filter(function(item) {
                    return (item.id_dtt === dtt.id);
                });

                if (!(filtros && filtros.length)) {
                    return null;
                }

                return filtros;

            }

            function _txtHelpNumeroAno() {
                var txt = $("#txt_help_numero_ano");
                txt.text("");

                var numero = $("#numero").val();
                var ano = $("#ano").val();

                if (numero.length && ano.length) {
                    return;
                }

                txt.text(" - Numeração será gerada automaticamente.");
            }

            $("#id_documento_tipo_target").change(
                function() {
                    $(".linha_documento_tipo").hide();
                    $("#id_documento_tipo").children().remove();
                    $(".linha_cadastro, .linha_documento_cadastro, .linha_documento").hide();

                    var id_selecionado = $(this).val();
                    var dtt_selecionado = dtts.find(function(item) {
                       return (item.id.toString() === id_selecionado.toString()) 
                    });

                    if (!dtt_selecionado) {
                        return;
                    }

                    var dts_selecionado = dts.filter(function(item) {
                        return (dtt_selecionado.id.toString() === item.id_dtt.toString())
                    });

                    if (!(dts_selecionado && dts_selecionado.length)) {
                        return;
                    }
                    
                    $('<option value="">==> SELECIONE <== </option>').appendTo($("#id_documento_tipo"));

                    dts_selecionado.forEach(function(item) {
                        var selected = "";
                        if (item.id === id_documento_tipo) {
                            selected = " selected ";
                        }
                        $('<option value="' + item.id + '" ' + selected + '>' + item.descricao + '</option>').appendTo($("#id_documento_tipo"));
                    });

                    $(".linha_documento_tipo").show();
                
                if ($(this).val() == '<?php echo $dtt->getId(); ?>') {
                    $(".linha_cadastro").show();
                }

                }
            ).change();

            $("#id_documento_tipo").change(
                function() {

                    $(".linha_documento, .linha_cadastro, .linha_documento_cadastro").hide();   

                    var id_dt_selecionado = $(this).val();
                    if (!(id_dt_selecionado && id_dt_selecionado.length)) {
                        $(".linha_grupo_ano").show();
                        return;
                    }

                    var obj = dts.find(function(item) {
                        return (id_dt_selecionado.toString() === item.id.toString());
                    });

                    
                    if (!obj) {
                        return;
                    }

                    if  (obj.possui_numero) {
                        $(".linha_grupo_ano").hide();
                    } else {
                        $(".linha_cadastro, .linha_grupo_ano").show();
                        return;
                    }

                    if ($(this).children().length) {
                        $(".linha_documento").show();
                    }

                }
            ).change();

            $("#link_documento").click(
                function() {
                    $("#jan_pagina, #id_documento").val("");
                    $("#show_documento").text("");
                    $("#operacao").val("documento");
                    $("#janela_documento").modal("show");
                    limparFiltro();
                }
            );

            $(".bt_documento_cancelar").click(
                function() {
                    fecharJanela();
                }
            );

            $("#bt_documento_limpar").click(
                function() {
                    limparFiltro();
                }
            );

            $("#formulario").submit(
                function() {
                    if ($("#operacao").val() == "documento") {
                        procurarDocumento();
                        return false;
                    }
                    return true;
                }
            );

            $("#bt_documento_novo").click(
                function() {
                    fecharJanela();
                    $(".linha_documento").hide();
                    $(".linha_cadastro, .linha_documento_cadastro").show();
                    $(".linha_documento_cadastro input").first().focus();
                    $(".field").val("");
                    $("#ano").val(grupo_ano);

                    _txtHelpNumeroAno();
                }
            );

            $("#janela_documento").css( { "width": "1000px", "margin-left": "-500px" } ); 

            $("#janela_documento").modal("hide").on("shown", function() {
                $(".filtro").first().focus();
            });

            $("#janela_documento").keypress(function(event) {
                if (event.which == 13) {
                    event.preventDefault();
                    procurarDocumento();
                }
            });

            $("#numero, #ano").keyup(function() {
                _txtHelpNumeroAno();
            });

            $("#ano").focus();
        }
    );

    function setPage($page) {
        $("#jan_pagina").val($page);
        $("#formulario").submit();
    }

    function limparFiltro() {
        $(".filtro").val("");
        procurarDocumento();
    }

    function fecharJanela() {
        $("#operacao").val("");
        $("#janela_documento").modal("hide");
    }

    function procurarDocumento() {

        if (ajax_obj) {
            ajax_obj.abort();
        }

        $(".linha_resultado, .paginacao_arquivo").remove();
        ajax_obj = $.ajax({
            "url" : "<?php echo Escola_Util::getBaseUrl(); ?>/documento/listarporpagina/format/json/",
            "type" : "POST",
            "data" : { "filtro_numero": $("#filtro_numero").val(),
                    "filtro_ano": $("#filtro_ano").val(),
                    "filtro_resumo": $("#filtro_resumo").val(),
                    "filtro_id_documento_tipo": $("#id_documento_tipo").val(),
                    "pagina_atual": $("#jan_pagina").val(),
                    "qtd_por_pagina": 15 },
            "success" : function(result) {

                if (!(result.items && result.items.length)) {
                    $("<tr class='linha_resultado'><td colspan='5' align='center'>NEHUM REGISTRO LOCALIZADO!</td></tr>").appendTo($("#documento_resposta"));
                    return;
                }

                result.items.forEach(function(item) {

                    var tr = $('<tr class="linha_resultado"></tr>').appendTo($("#documento_resposta"));
                    
                    $('<td><a href="#" class="link_seleciona" id="' + item.id + '">' + item.id + '</a></td>').appendTo(tr);
                    $('<td><a href="#" class="link_seleciona" id="' + item.id + '">' + item.data_hora + '</a></td>').appendTo(tr);
                    $('<td><a href="#" class="link_seleciona" id="' + item.id + '">' + item.tipo + '</a></td>').appendTo(tr);
                    $('<td><a href="#" class="link_seleciona" id="' + item.id + '">' + item.numero+ '</a></td>').appendTo(tr);
                    $('<td><a href="#" class="link_seleciona" id="' + item.id + '">' + item.resumo + '</a></td>').appendTo(tr);

                    tr.appendTo($(".corpo_documento"));

                });

                $(".link_seleciona").bind("click",
                    function(event) {
                        event.preventDefault();
                        var id = $(this).attr("id");

                        $("#id_documento").val(id);
                        $("#operacao").val("set_documento");
                        $("#formulario").submit();
                    }
                );

                var paginacao = new Paginacao();
                paginacao.total_pagina = result.total_pagina;
                paginacao.pagina_atual = result.pagina_atual;
                paginacao.primeira = result.primeira;
                paginacao.ultima = result.ultima;

                var html = paginacao.render();

                $('<div class="paginacao_arquivo">' + html + '</div>').appendTo($("#janela_documento .modal-body"));

            }

        });    
    }    
</script>