<div class="row-fluid">
    <form class="form-horizontal">
    <div class="well">
            <legend>Dados do Beneficiario</legend>
            <div class="control-group">
                <label class="control-label" for="">Nome</label>
                <div class="controls">
                    <input type="text" placeholder="Nome completo" class="span6">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="">RG</label>
                <div class="controls">
                    <input type="text" placeholder="" class="span1">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="">CPF</label>
                <div class="controls">
                    <input type="text" placeholder="___.___.___-__" class="span2">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="">Telefone</label>
                <div class="controls">
                    <input type="text" placeholder="() ____-_____" class="span2">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="">Nome do Pai:</label>
                <div class="controls">
                    <input type="text" placeholder="Nome completo do Pai" class="span6">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="">Nome da Mãe:</label>
                <div class="controls">
                    <input type="text" placeholder="Nome completo da Mãe" class="span6">
                </div>
            </div>
    </div>
    <div class="well">
        <legend>Endereço</legend>
        <div class="control-group">
            <label class="control-label" for="">Rua</label>
            <div class="controls">
                <input type="text" placeholder="">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="">Numero</label>
            <div class="controls">
                <input type="text" placeholder="">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="">Bairro</label>
            <div class="controls">
                <input type="text" placeholder="">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="">UF</label>
            <div class="controls">
                <input type="text" placeholder="">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="">CEP</label>
            <div class="controls">
                <input type="text" placeholder="">
            </div>
        </div>
    </div>
    </form>
</div>