<div class="row-fluid">
    <div class="block span6">
        <p class="block-heading"><i class="icon-list"></i><span class="break"></span>Carteiras Solicitadas - Deferidas</p>
        <div class="block-body">
            <table class="table table-striped table-hover">
                <thead>
                    <td>Id</td>
                    <td>Data</td>
                    <td>Nome</td>
                    <td>Tipo</td>
                    <td>Situação</td>
                    <td>Operações</td>
                </thead>
                <tbody>
                    <tr>
                        <td>001</td>
                        <td>13/04/2015</td>
                        <td>Francivan dos Santos de Castro</td>
                        <td>Idoso</td>
                        <td><span class="text-success">DEFERIDO</span></td>
                        <td>
                            <div class="btn-group">
                                <a href="" class="btn"><i class="icon-print"></i></a>
                                <a href="" class="btn"><i class="icon-search"></i></a>
                                <a href="" class="btn"><i class="icon-edit"></i></a>
                                <a href="" class="btn"><i class="icon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>002</td>
                        <td>15/04/2015</td>
                        <td>José Luis Soares Batista</td>
                        <td>Deficiente</td>
                        <td><span class="text-success">DEFERIDO</span></td>
                        <td>
                            <div class="btn-group">
                                <a href="" class="btn"><i class="icon-print"></i></a>
                                <a href="" class="btn"><i class="icon-search"></i></a>
                                <a href="" class="btn"><i class="icon-edit"></i></a>
                                <a href="" class="btn"><i class="icon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="block span6">
        <p class="block-heading"><i class="icon-list"></i><span class="break"></span>Carteiras Solicitadas - Indeferidas</p>
        <div class="block-body">
            <table class="table table-striped table-hover">
                <thead>
                    <td>Id</td>
                    <td>Data</td>
                    <td>Nome</td>
                    <td>Tipo</td>
                    <td>Situação</td>
                    <td>Operações</td>
                </thead>
                <tbody>
                    <tr>
                        <td>001</td>
                        <td>13/04/2015</td>
                        <td>Francivan dos Santos de Castro</td>
                        <td>Idoso</td>
                        <td><span class="text-error">INDEFERIDO</span></td>
                        <td>
                            <div class="btn-group">
                                <a href="" class="btn"><i class="icon-search"></i></a>
                                <a href="" class="btn"><i class="icon-edit"></i></a>
                                <a href="" class="btn"><i class="icon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>002</td>
                        <td>15/04/2015</td>
                        <td>José Luis Soares Batista</td>
                        <td>Deficiente</td>
                        <td><span class="text-error">INDEFERIDO</span></td>
                        <td>
                            <div class="btn-group">
                                <a href="" class="btn"><i class="icon-search"></i></a>
                                <a href="" class="btn"><i class="icon-edit"></i></a>
                                <a href="" class="btn"><i class="icon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>