<div id="topo">
                <div id="logo"><img src="<?php echo Escola_Util::getBaseUrl(); ?>/img/logo.png"></div>
                <div id="publicidade">
                    <img src="<?php echo Escola_Util::getBaseUrl(); ?>/img/banner.png">
                </div>
                <div id="formulario_login">
                    <form>
                        <table>
                            <tr>
                                <td>E-mail:</td>
                                <td><input class="text" type="text" name="login"></td>
                            </tr>
                            <tr>
                                <td>Senha:</td>
                                <td><input  class="text" type="text" name="senha">
                                    <input class="btn" type="submit" name="logar" value="Entrar">
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="rec_senha">Recuperar Senha</span></td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
            <div class="clear"></div>