<?php
	/*
	$acl = Escola_Acl::getInstance();
	$usuario = $acl->getUsuarioLogado();
	$grupos = $usuario->pegaTbGrupo();
?>
<div class="navegacao">
	<div class="identificacao">
		<strong>Último Login</strong>: 05/09/2011 10:25:00
	</div>
	<div id="localizacao">
		<strong>Localização</strong>: <?php echo strtoupper($this->modulo); ?> > <a href=""><?php echo strtoupper($this->acao); ?></a>
	</div>
	<div class="identificacao">
		<strong>Grupo(s)</strong>: 
<?php 
if ($grupos) { 
	$arr = array();
	foreach ($grupos as $grupo) {
		$arr[] = $grupo->descricao;
	}
	echo implode(", ", $arr);
} 
?>
	</div>
	<div class="identificacao">
		<strong>Usuário</strong>: <?php echo $usuario->getPessoaFisica()->nome; ?>
	</div>
	<div class="clear"></div>
</div>
<?php */ ?>