<?php
$tb = new TbMenuPosicao();
$ms = $tb->getPorChave("L");
if ($ms) {
    $tb = new TbMenu();
    $menus = $tb->listar(array("id_menu_posicao" => $ms->getId()));
    if ($menus) {
?>
                <div id="menu">
                    <ul>
<?php foreach ($menus as $menu) { ?>
        <li><a href="<?php echo $menu->url(); ?>"><?php echo $menu->descricao; ?></a></li>
<?php } ?>
                    </ul>
                </div>
<?php }} ?>