<?php
$tb = new TbFuncionario();
$funcionario = $tb->getPorPessoaFisica($this->pf);
if ($funcionario) {
	$lotacaos = $funcionario->pegaLotacaoAtiva();
	if (count($lotacaos) > 1) {
?>
<div id="janela_selecao_lotacao" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 id="myModalLabel">Selecionar Lotação</h4>
    </div>
    <div class="modal-body">
        <div class="alert alert-info">
            Você possui mais de uma lotação ativa, selecione a lotação que deseja trabalhar.
        </div>
        <table class="table table-striped table-bordered">
            <thead>
			<tr>
				<th>Tipo</th>
				<th>Sigla</th>
				<th>Descrição</th>
			</tr>
            </thead>
<?php foreach ($lotacaos as $lotacao) {
	$setor = $lotacao->findParentRow("TbSetor");
?>
			<tr>
				<td align="center">
					<a href="<?php echo $this->url(array("action" => "lotacao", "id" => $lotacao->getId())); ?>">
						<?php echo $lotacao->findParentRow("TbLotacaoTipo")->toString(); ?>
					</a>
				</td>
				<td align="center">
					<a href="<?php echo $this->url(array("action" => "lotacao", "id" => $lotacao->getId())); ?>"><?php echo $setor->sigla; ?></a>
				</td>
				<td><a href="<?php echo $this->url(array("action" => "lotacao", "id" => $lotacao->getId())); ?>"><?php echo $setor->descricao; ?></a></td>
			</tr>
<?php } ?>
		</table>        
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
    </div>   
</div>
	<div class="janela_modal" id="janela_selecao_lotacao" style="display:none">
		<table class="lista_box lista">
			<tr>
				<th colspan="3">Você possui mais de uma lotação ativa, selecione a lotação que deseja trabalhar.</th>
			</tr>
			<tr>
				<th>Tipo</th>
				<th>Sigla</th>
				<th>Descrição</th>
			</tr>
<?php foreach ($lotacaos as $lotacao) {
	$setor = $lotacao->findParentRow("TbSetor");
?>
			<tr>
				<td align="center">
					<a href="<?php echo $this->url(array("action" => "lotacao", "id" => $lotacao->getId())); ?>">
						<?php echo $lotacao->findParentRow("TbLotacaoTipo")->toString(); ?>
					</a>
				</td>
				<td align="center">
					<a href="<?php echo $this->url(array("action" => "lotacao", "id" => $lotacao->getId())); ?>"><?php echo $setor->sigla; ?></a>
				</td>
				<td><a href="<?php echo $this->url(array("action" => "lotacao", "id" => $lotacao->getId())); ?>"><?php echo $setor->descricao; ?></a></td>
			</tr>
<?php } ?>
		</table>
	</div>
<?php }} ?>

<div class="row-fluid">
    
<?php
if ($funcionario) {
?>
    
<div class="block span4">
        <p class="block-heading"><i class="icon-user"></i><span class="break"></span>Informaçoes de Login</p>
        <div class="block-body">
        
<?php
if ($funcionario) {
	$lotacaos = $funcionario->pegaLotacaoAtiva();
	echo $funcionario->mostrarFoto();
} else {
	echo $this->pf->mostrarFoto(); 
}
?>
			<p><strong>Nome: </strong> <?php echo $this->pf->nome; ?></p>
			<p><strong>E-Mail: </strong> <?php echo $this->pf->pega_pessoa()->email; ?></p>
<?php
if ($funcionario) {
?>
			<p><strong>Matrícula: </strong> <?php echo $funcionario->matricula; ?></p>
			<p><strong>Cargo: </strong> <?php echo $funcionario->findParentRow("TbCargo")->toString(); ?></p>
<?php
$lotacao = $funcionario->pegaLotacaoAtual();
if ($lotacao) { 
?>
			<p><strong>Lotação: </strong>
<?php if (count($lotacaos) > 1) { ?>
			<a href="#" class="link_lotacao"><?php echo $lotacao->findParentRow("TbSetor")->toString(); ?></a>
<?php } else { ?>
			<?php echo $lotacao->findParentRow("TbSetor")->toString(); ?>
<?php } ?>
			</p>
<?php }} ?>
<?php if ($this->ultimo_login) { ?>
			<p><strong>Ultimo login: </strong> <?php echo $this->ultimo_login->data; ?></p>
			<p><strong>Endereço IP: </strong><?php echo $this->ultimo_login->ip; ?></p>
<?php } ?>
		</div>
		
	</div>
<div class="block span4">
            <p class="block-heading"><i class="icon-search"></i><span class="break"></span>Procurar Servidor</p>
            <div class="block-body">
                <form action="<?php echo $this->url(array("controller" => "funcionario", "action" => "search")); ?>" method="post">
                    <div class="input-prepend">
                        <span class="add-on">Nome:</span>
                        <input type="text" name="filtro_nome" class="input-block-level" id="filtro_nome">
                    </div>
                    
                    <div class="input-prepend">
                        <span class="add-on">Setor:</span>
                        <input type="text" name="filtro_setor" id="filtro_setor" class="input-block-level"/>
                    </div>
                    <br />
                    <input type="submit" value="PROCURAR" class="acao btn btn-primary" />
                    
            </form>
        </div>
</div>
<div class="span4">
<?php
if ($funcionario) {
    $obj = Escola_Alerta::getInstance();
    echo $obj->render(); 
} 
?>
</div>
</div>
    <div class="row-fluid">
<?php 
	$tb = new TbFuncionario();
	$aniversariantes = $tb->pegaAniversariantes();
	if ($aniversariantes) {
?>
        <div class="block span12">
            
            <p class="block-heading"><i class="icon-gift"></i><span class="break"></span>Aniversariantes da Semana</p>
            <div class="block-body">

						
			<table class="table table-hover">
				
				<tr class="titulo"> 
                                    <th width="100px" colspan="2">Foto</th>
                                    <th>Nome</th>
                                    <th width="130px">Dia</th>
				</tr>
<?php
$hoje = new Zend_Date();
$hoje = $hoje->get("MM-dd");
foreach ($aniversariantes as $aniversariante) {
	$pf = $aniversariante->pega_pessoa_fisica();
	$date = new Zend_Date($pf->data_nascimento);
	$atual = new Zend_Date();
	$atual->set($atual->get("YYYY") . $date->get("-MM-dd"));
	$aniversario = ($hoje == $date->get("MM-dd"));
	$bgcolor = "";
	if ($aniversario) {
		$bgcolor = " style='background-color: #F9F9F9'";
	}
?>
					<tr <?php echo $bgcolor; ?>>
						<td width="10px">
<?php if ($aniversario) { ?>
							<a href="#" rel="<?php echo $aniversariante->getId(); ?>" class="janela_funcionario">
								<i class="icon-gift icon-2x"></i>
							</a>
<?php } ?>
						</td>
						<td>
							<a href="#" rel="<?php echo $aniversariante->getId(); ?>" class="janela_funcionario">
<?php
	echo $pf->mostrarFoto(70, "center");
?>
							</a>
</td>
						<td>
							<a href="#" rel="<?php echo $aniversariante->getId(); ?>" class="janela_funcionario">
								<?php echo $pf->nome; ?>
							</a>
						</td>
						<td>
							<a href="#" rel="<?php echo $aniversariante->getId(); ?>" class="janela_funcionario">
								<?php echo $date->get("dd/MM"); ?> (<?php echo Escola_Util::pegaDiaSemana($atual); ?>)
							</a>
						</td>
					</tr>
<?php } ?>
			</table>
		</div>
		</div>
<?php } ?>
<?php } ?>
        </div>