<div class="hero">
                <div class="span12">
            <div id='tmpSlideshow'>
            <div id='tmpSlide-1' class='tmpSlide'>
              <img src='<?php echo $this->baseUrl(); ?>/img/f1.jpg' alt='Slide' />   
            
                <h4>CURSO IELTS</h4>
                <p>
                  CONCURSO DE BOLSA: Segunda chamada para o dia 21/11/2013. <br>
                  LOCAL: Sala do ICIBE/UFRA.<br>
                  As inscrições deverão ser registradas na FUNPEA, Travessa Mauriti n° 2520 A, entre Duque de Caxias e 25 de Setembro, em horário comercial: 08:30 às 12:30 e das 13:30 às 17:30.
                </p>

            
            </div>
            <div id='tmpSlide-2' class='tmpSlide'>
              <img src='<?php echo $this->baseUrl(); ?>/img/f2.jpg' alt='Slide' />   
            
                <h4>PORTARIA CONJUNTA Nº30, DE 13 DE MARÇO DE 2012</h4>
                <p>
                O SECRETÁRIO DE EDUCAÇÃO SUPERIOR DO MINISTÉRIO DA EDUCAÇÃO E O SECRETÁRIO DE POLÍTICAS E PROGRAMAS DEPESQUISA E DESENVOLVIMENTODO MINISTÉRIO DA CIÊNCIA E TECNOLOGIA
                </p>

            
            </div>
            <div id='tmpSlide-3' class='tmpSlide'>
              <img src='<?php echo $this->baseUrl(); ?>/img/f3.jpg' alt='Slide' />   
        
                <h4>CREDENCIAMENTO</h4>
                <p>
                  A FUNPEA através da Portaria Interministerial n° 475, de 14 de abril de 2008 e do Decreto n° 7.423, de 31 de dezembro de 2010 torna-se credenciada junto ao MEC. Clique aqui para ver publicação no D.O.U.
                </p>


          
            </div>
            <div id='tmpSlideshowControls'>
              <div class='tmpSlideshowControl' id='tmpSlideshowControl-1'><span>1</span></div>
              <div class='tmpSlideshowControl' id='tmpSlideshowControl-2'><span>2</span></div>
              <div class='tmpSlideshowControl' id='tmpSlideshowControl-3'><span>3</span></div>

            </div>
       </div>
          
            </div>
                
          
          <div class="row-fluid">
             
                <div class="span5">
                 <div class="well">
                  <h4>Apresentação</h4>
                  <p>
                      A FUNDAÇÃO DE APOIO À PESQUISA, EXTENSÃO E ENSINO EM CIÊNCIAS AGRÁRIAS, designada também pela sigla FUNPEA, é uma instituição de Direito Privado, sem fins lucrativos, goza de autonomia Patrimonial, Financeira e Administrativa na forma da lei, rege-se através estatuto e demais dispositivos legais aplicáveis.
                  </p>
                  <p><a class="btn" href="#">Ler mais &raquo;</a></p>
                  <h4>CREDENCIAMENTO</h4>
                  <p>A FUNPEA através da Portaria Interministerial n° 475, de 14 de abril de 2008 e do Decreto n° 7.423, de 31 de dezembro de 2010 torna-se credenciada junto ao MEC. Clique aqui para ver publicação no D.O.U.</p>
                  <p><a class="btn" href="#">Ler mais  &raquo;</a></p>
                  </div>
                  
                  
                </div>
                <div class="span7">
                    <div class="well">
                  <h4>Noticias</h4>
                  
                  <ul class="media-list">
                      <li><span class="badge badge-success">06/12/2013</span> 
                        <a href="<?php echo $this->url(array("controller" => "index", "action" => "view")); ?>">Confira os projetos atualmente firmados com a Universidade Federal Rural da Amazônia - UFRA</a>
                      </li>
                      <li><span class="badge badge-success">06/12/2013</span> 
                        <a href="<?php echo $this->url(array("controller" => "index", "action" => "view")); ?>">Confira os projetos atualmente firmados com a Universidade Federal Rural da Amazônia - UFRA</a>
                      </li>
                      <li><span class="badge badge-success">06/12/2013</span> 
                        <a href="<?php echo $this->url(array("controller" => "index", "action" => "view")); ?>">Confira os projetos atualmente firmados com a Universidade Federal Rural da Amazônia - UFRA</a>
                      </li>
                      <li><span class="badge badge-success">06/12/2013</span> 
                        <a href="<?php echo $this->url(array("controller" => "index", "action" => "view")); ?>">Confira os projetos atualmente firmados com a Universidade Federal Rural da Amazônia - UFRA</a>
                      </li>
                      <li><span class="badge badge-success">06/12/2013</span> 
                        <a href="<?php echo $this->url(array("controller" => "index", "action" => "view")); ?>">Confira os projetos atualmente firmados com a Universidade Federal Rural da Amazônia - UFRA</a>
                      </li>
                     
                  </ul>
                  <p><a class="btn" href="<?php echo $this->url(array("controller" => "index", "action" => "viewall")); ?>">Ler mais &raquo;</a></p>
                  </div>
                  <div class="well">
                  <h4>Formularios</h4>
                   <ul class="media-list">
                      <li><span class="label label-info">06/12/2013</span> 
                            <a href=""> FORMULÁRIO DE BOLSITA</a>
                      </li>
                      <li><span class="label label-info">06/12/2013</span> 
                            <a href=""> RECIBO</a>
                      </li>
                      <li><span class="label label-info">06/12/2013</span> 
                            <a href="">RELATÓRIO DE VIAGEM</a>
                      </li>
                      <li><span class="label label-info">06/12/2013</span> 
                            <a href=""> SOLICITAÇÃO DE ADIANTAMENTO PARA DESPESAS</a>
                      </li>
                      <li><span class="label label-info">06/12/2013</span> 
                            <a href=""> SOLICITAÇÃO GERAL</a>
                      </li>
                  </ul>
                  <p><a class="btn" href="#">Ler mais  &raquo;</a></p>
                  </div>
                  
                </div>
               
          </div>
            
              
        </div>