<div class="media">
                <div class="media-body">
                    <form action="" class="form-inline text-center">
                        <fieldset>
                            <legend>Busca na Página</legend>
                            <input type="text">
                            <buttom class="btn btn-info">Enviar</buttom>
                        </fieldset>
                    </form>
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>DATA</th>
                          <th>TITULO</th>
                        </tr>
                      </thead>
                      <tbody>
                          <?php for($i=0; $i<=20; $i++){ ?>
                        <tr>
                          <td><a href="#"><span class="badge badge-success">06/12/2013</span></a></td>
                          <td><a href="#">PROJETOS FIRMADOS COM A UNIVERSIDADE FEDERAL RURAL DA AMAZÔNIA</a></td>
                        </tr>
                          <?php } ?>
                      </tbody>
                    </table>
                </div>
                  <div class="pagination">
                    <ul>
                      <li><a href="#"> << </a></li>
                      <li><a href="#"> < </a></li>
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                      <li><a href="#">6</a></li>
                      <li><a href="#">7</a></li>
                      <li><a href="#">8</a></li>
                      <li><a href="#">9</a></li>
                      <li><a href="#">10</a></li>
                      <li><a href="#"> > </a></li>
                      <li><a href="#"> >> </a></li>
                    </ul>
                  </div>
            </div>