<div class="media">
                            <div class="media-body">
                              <h4 class="media-heading">APRESENTAÇÃO</h4>
                              <p>A FUNDAÇÃO DE APOIO À PESQUISA, EXTENSÃO E ENSINO EM CIÊNCIAS AGRÁRIAS, designada também pela sigla FUNPEA, é uma instituição de Direito Privado, sem fins lucrativos, goza de autonomia Patrimonial, Financeira e Administrativa na forma da lei, rege-se através estatuto e demais dispositivos legais aplicáveis.

A FUNPEA tem como missão Apoiar atividades de Pesquisa, Extensão e Ensino, apoiar programas de Desenvolvimento Sustentado e Proteção ao Meio Ambiente; Prestar serviços administrativos, técnicos, científicos e Sociais, Conceder bolsas de estudos em todos os níveis; Operar canais de difusão com serviços de informação destinados à divulgação com a finalidade da melhoria das comunidades Rurais da Amazônia Legal; Conceder subsídios para aquisição, divulgação e edição de livros, periódicos e boletins que versem sobre ciências agrárias e outros; Elaborar e executar projetos técnico-científicos; Prestar consultorias técnicas; entre outras.</p>
                              <table class="table table-bordered">
                                <thead>
                                  <tr>
                                    <th>Data</th>
                                    <th>Arquivo</th>
                                    <th>Tamanho</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td><a href="#">21/12/2013</a></td>
                                    <td><a href="#">PROJETOS FIRMADOS COM A UNIVERSIDADE FEDERAL RURAL DA AMAZÔNIA</a></td>
                                    <td><a href="#">374.18 KBytes</a></td>
                                  </tr>
                                </tbody>
                              </table>
                              
                              
<div id="box">

<ul id="slider">
	<li id="1" >
		<img src="<?php echo $this->baseUrl(); ?>/img/grass-bl.jpg" alt="grass-blades" width="500" height="338" />
		<p><span>Descricao da imagem 1</span></p>
	</li>
	<li id="2">
		<img src="<?php echo $this->baseUrl(); ?>/img/ladybug.jpg" alt="ladybug" width="500" height="338" />
		<p><span>Descricao da imagem 2</span></p>
	</li>
	<li id="3">
		<img src="<?php echo $this->baseUrl(); ?>/img/lotus.jpg" alt="lotus" width="500" height="338" />
		<p><span> 3</span></p>
	</li>
	<li id="4">
		<img src="<?php echo $this->baseUrl(); ?>/img/stones.jpg" alt="stones" width="500" height="338" />
		<p><span>Descricao da imagem 4</span></p>
	</li>
        <li id="5">
		<img src="<?php echo $this->baseUrl(); ?>/img/anfiteatro.jpg" alt="ddd" width="500" height="338" />
		<p><span>Descricao da imagem 5</span></p>
	</li>
        <li id="6">
		<img src="<?php echo $this->baseUrl(); ?>/img/reitoria.jpg" alt="stosssnes" width="500" height="338" />
		<p><span>Descricao da imagem 6</span></p>
	</li>
        <li id="7">
		<img src="<?php echo $this->baseUrl(); ?>/img/entrada1.jpg" alt="sqones" width="500" height="338" />
		<p><span>Descricao da imagem 7</span></p>
	</li>
</ul>

<ul id="thumb">
	<li><a href="#1"><img src="<?php echo $this->baseUrl(); ?>/img/grass-bl.jpg" alt="grass-blades" width="50" height="50" /></a></li>
	<li><a href="#2"><img src="<?php echo $this->baseUrl(); ?>/img/ladybug.jpg" alt="ladybug" width="50" height="50" /></a></li>
	<li><a href="#3"><img src="<?php echo $this->baseUrl(); ?>/img/lotus.jpg" alt="lotus" width="50" height="50" /></a></li>
	<li><a href="#4"><img src="<?php echo $this->baseUrl(); ?>/img/stones.jpg" alt="stones" width="50" height="50" /></a></li>
        <li><a href="#5"><img src="<?php echo $this->baseUrl(); ?>/img/anfiteatro.jpg" alt="stones" width="50" height="50" /></a></li>
        <li><a href="#6"><img src="<?php echo $this->baseUrl(); ?>/img/reitoria.jpg" alt="stones" width="50" height="50" /></a></li>
        <li><a href="#7"><img src="<?php echo $this->baseUrl(); ?>/img/entrada1.jpg" alt="stones" width="50" height="50" /></a></li>
</ul>

</div>
                            </div>
                          </div>