<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="jan_formulario" class="formulario form-horizontal">
            <div id="janela_pessoa_tipo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 id="myModalLabel">Adicionar Pessoa</h4>
                </div>
                <div class="modal-body">
                    <div class="row-fluid">
                        <fieldset>
<?php
$tb = new TbPessoaTipo();
$pts = $tb->listar();
if ($pts) { 
?>
                <div class="control-group">
                    <label for="jan_id_pessoa_tipo" class="control-label">Tipo de Pessoa:</label>
                    <div class="controls">
                        <select name="jan_id_pessoa_tipo" id="jan_id_pessoa_tipo" class="filtro">
                            <option value="" <?php echo (!$this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
<?php foreach ($pts as $pt) { ?>
                            <option value="<?php echo $pt->getId(); ?>" rel="<?php echo Escola_Util::minuscula($pt->chave); ?>" <?php echo ($pt->getId() == $this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>><?php echo $pt->toString(); ?></option>
<?php } ?>
                        </select>
                    </div>
                </div>
<?php } ?>
                            <div class="control-group jan_pf">
                                <label for="jan_cpf" class="control-label">C.P.F.:</label>
                                <div class="controls">
                                    <input type="text" name="jan_cpf" id="jan_cpf" class="span6 cpf" />
                                </div>
                            </div>
                            <div class="control-group jan_pj">
                                <label for="jan_cnpj" class="control-label">C.N.P.J.:</label>
                                <div class="controls">
                                    <input type="text" name="jan_cnpj" id="jan_cnpj" class="span6 cnpj" />
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                </div>
            </div>
        </form>
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
<?php
if ($pts) { 
?>
                <div class="control-group">
                    <label for="filtro_id_pessoa_tipo" class="control-label">Tipo de Pessoa:</label>
                    <div class="controls">
                        <select name="filtro_id_pessoa_tipo" id="filtro_id_pessoa_tipo" class="filtro">
                            <option value="" <?php echo (!$this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
<?php foreach ($pts as $pt) { ?>
                            <option value="<?php echo $pt->getId(); ?>" rel="<?php echo Escola_Util::minuscula($pt->chave); ?>" <?php echo ($pt->getId() == $this->dados["filtro_id_pessoa_tipo"])?"selected":""; ?>><?php echo $pt->toString(); ?></option>
<?php } ?>
                        </select>
                    </div>
                </div>
<?php } ?>
                <div class="control-group filtro_pf">
                    <label for="filtro_cpf" class="control-label">C.P.F.:</label>
                    <div class="controls">
                        <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" class="span2 filtro cpf" />
                    </div>
                </div>                        
                <div class="control-group filtro_pj">
                    <label for="filtro_cnpj" class="control-label">C.N.P.J.:</label>
                    <div class="controls">
                        <input type="text" name="filtro_cnpj" id="filtro_cnpj" value="<?php echo $this->dados["filtro_cnpj"]; ?>" class="span3 filtro cnpj" />
                    </div>
                </div>                        
                <div class="control-group">
                    <label for="filtro_nome" class="control-label">Nome da Pessoa:</label>
                    <div class="controls">
                        <input type="text" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" class="span5 filtro" />
                    </div>
                </div>                        
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>C.P.F./C.N.P.J.</th>
                            <th>Nome</th>
                            <th>E-Mail</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
<?php 
    foreach ($this->registros as $registro) { 
        $pt = $registro->findParentRow("TbPessoaTipo");
?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $pt->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->mostrar_documento(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->mostrar_nome(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->email; ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
<?php if ($pt->pf()) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "foto",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Foto">
                                        <i class="icon-camera-retro"></i>
                                    </a>
<?php } ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "telefone",
                                                                         "id_pessoa" => $registro->getId(), "id" => 0)); ?>" class="btn" title="Telefones">
                                        <i class="icon-phone"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "ib",
                                                                         "id_pessoa" => $registro->getId(), "id" => 0)); ?>" class="btn" title="Informações Bancárias">
                                        <i class="icon-money"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>