<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Visualização de Pessoa</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
<?php echo $this->registro->view(); ?>
            </div>
<?php if ($this->transporte_pessoa) { ?>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th colspan="3">Vínculos de Transporte</th>
                </tr>
                <tr>
                    <th>Tipo</th>
                    <th>Transporte</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
<?php foreach ($this->transporte_pessoa as $tp) { ?>
                <tr>
                    <td><?php echo $tp->findParentRow("TbTransportePessoaTipo")->toString(); ?></td>
                    <td><?php echo $tp->findParentRow("TbTransporte")->toString(); ?></td>
                    <td><?php echo $tp->findParentRow("TbTransportePessoaStatus")->toString(); ?></td>
                </tr>
<?php } ?>
            </tbody>
        </table>
<?php } ?>
<?php if ($this->notificacoes) { ?>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th colspan="5">Notificações de Infração</th>
                </tr>
                <tr>
                    <th>Código</th>
                    <th width="500px">Infrações</th>
                    <th>Data / Hora Infração</th>
                    <th>Localização Infração</th>
                    <th>Veículo</th>
                </tr>
            </thead>
            <tbody>
<?php 
foreach ($this->notificacoes as $notificacao) { 
    $ai = $notificacao->pegaAutoInfracao();
    $veiculo = $notificacao->findParentRow("TbVeiculo");
    $txt_infracao = "--";
    $ids = array();
    $infracoes = $notificacao->listarInfracao();
    if ($infracoes) {
        foreach ($infracoes as $infracao) {
            $ids[] = $infracao->toString();
        }
    }
    if (count($ids)) {
        $txt_infracao = "<ul><li>" . implode("</li><li>", $ids) . "</li></ul>";
    }
?>
                <tr>
                    <td><?php echo $ai->mostrar_codigo(); ?></td>
                    <td><?php echo $txt_infracao; ?></td>
                    <td><?php echo Escola_Util::formatData($notificacao->data_infracao); ?> / <?php echo $notificacao->hora_infracao; ?></td>
                    <td><?php echo $notificacao->local_infracao; ?></td>
                    <td><?php echo ($veiculo)?$veiculo->toString():"--"; ?></td>
                </tr>
<?php } ?>
            </tbody>
        </table>
<?php } ?>
            </div>
    </div>
</div>