<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Visualização de Pessoa > Informações Bancárias</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Pessoa:</dt>
                    <dd><?php echo $this->pessoa->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->ib->findParentRow("TbInfoBancariaTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Banco:</dt>
                    <dd><?php echo $this->ib->findParentRow("TbBanco")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Agência:</dt>
                    <dd><?php echo $this->ib->mostrar_agencia(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Número:</dt>
                    <dd><?php echo $this->ib->mostrar_conta(); ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>