<div class="row-fluid">
    <div class="dialog">
        <?php 
$tb = new TbSistema();
$sistema = $tb->pegaSistema();
$pj = $sistema->findParentRow("TbPessoaJuridica");
$pessoa = $pj->findParentRow("TbPessoa");
$arquivo = $pessoa->getFoto();
if ($arquivo) {
    //$filename = $arquivo->pegaLinkFisico();
?>	
        <center><img src="<?php echo $this->url(array("controller" => "arquivo", "action" => "view", "id" => $arquivo->getId())); ?>"  width="50%"/></center>
<?php } ?>
        <div class="block">
        <form action="<?php echo $this->url(array("controller" => "auth", "action" => "identify")); ?>" method="post" id="formulario" >
            <p class="block-heading">Acesso ao Sistema</p>
            <div class="block-body text-center">
                
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <input type="text" name="login_cpf" id="login_cpf" class="cpf" value="<?php echo $this->login_cpf; ?>" placeholder="___.___.___-__" />
                        
                    </div>
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-key"></i></span>
                            <input type="password" name="login_senha" id="login_senha" class="" />
                            
                    </div>
                    
                    
                    <div class="clearfix"></div>
                
            </div>
        </div>
        <p class="pull-right" style=""><input type="submit" value="Efetuar Login" class="btn btn-primary" /></p>
        <p><a href="<?php echo $this->url(array("controller" => "auth", "action" => "recuperasenha")); ?>" class="btn btn-warning">Recuperar senha</a></p>
    </form>
    </div>
    
</div>