<style type="text/css">
.box_form {
	margin-top: 60px;   
}
.img_logo {
	width: 200px;
	margin-top: 60px;
}
</style>
<div class="row-fluid">
	<div class="span6 offset3">
		<div class="well box_form">
			<form action="<?php echo $this->url(array("controller" => "auth", "action" => "recuperasenhaoffline")); ?>" method="post" id="formulario" class="form-horizontal">
				<fieldset>
					<legend>Recuperar Senha - OffLine</legend>
						<div class="alert">
							<p>
								Preencha os campos abaixo e clique em <strong>ENVIAR</strong>.
							</p>
						</div>					
						<div class="control-group">
							<label for="cpf" class="control-label">CPF: </label>
							<div class="controls">
								<div class="input-append">
	  								<input type="text" name="cpf" id="cpf" class="cpf" value="<?php echo $this->getRequest()->getParam("cpf"); ?>" />
	  								<span class="add-on"><i class="icon-user"></i></span>
								</div>
							</div>
						</div>
						<div class="control-group">
							<label for="email" class="control-label">E-Mail: </label>
							<div class="controls">
								<input type="text" name="email" id="email" value="<?php echo $this->getRequest()->getParam("email"); ?>" />
							</div>
						</div>
						<div class="control-group">
							<label for="nome" class="control-label">Primeiro Nome: </label>
							<div class="controls">
								<input type="text" name="nome" id="nome" value="<?php echo $this->getRequest()->getParam("nome"); ?>" />
							</div>
						</div>
						<div class="control-group">
							<label for="data_nascimento" class="control-label">Data de Nascimento: </label>
							<div class="controls">
								<input type="text" name="data_nascimento" id="data_nascimento" value="<?php echo $this->getRequest()->getParam("data_nascimento"); ?>" class="data" />
							</div>
						</div>
						<div class="control-group">
							<label for="identidade_numero" class="control-label">Identidade: </label>
							<div class="controls">
								<input type="text" name="identidade_numero" id="identidade_numero" value="<?php echo $this->getRequest()->getParam("identidade_numero"); ?>" />
								<span class="label label-info">Somente Números</span>
							</div>
						</div>
						<div class="control-group">
							<div class="controls">
								<input type="submit" value="ENVIAR" class="btn btn-danger" />
								<a href="<?php echo $this->url(array("controller" => "intranet")); ?>" class="btn">Cancelar</a>
							</div>
						</div>
				</fieldset>
			</form>
		</div>
	</div>
</div>