<?php 
$txt_id = $txt_tipo = $txt_data_hora = $txt_cpf = $txt_nome = $txt_numero = $txt_validade = $txt_status = "--";
$txt_nascimento = $txt_nome_pai = $txt_nome_mae = $txt_rg = $txt_telefone = $txt_endereco = "--";

if (isset($this->registro)) {
    $registro = $this->registro;
    if ($registro->getId()) {
        $txt_id = $registro->getId();
    }
    $ct = $registro->findParentRow("TbCredencialTipo");
    if ($ct) {
        $txt_tipo = $ct->toString();
    }
    $txt_data_hora = Escola_Util::formatData($registro->credencial_data) . " " . $registro->credencial_hora;
    $pf = $registro->pegaBeneficiario();
    if ($pf) {
        $txt_cpf = Escola_Util::formatCpf($pf->cpf);
        $txt_nome = $pf->nome;
        
        $txt_nascimento = Escola_Util::formatData($pf->data_nascimento);
        if (!empty($pf->nome_pai)) {
            $txt_nome_pai = $pf->nome_pai;
        }
        if (!empty($pf->nome_mae)) {
            $txt_nome_mae = $pf->nome_mae;
        }
        $rg = $pf->mostrar_identidade();
        if ($rg) {
            $txt_rg = $rg;
        }
        $pessoa = $pf->getPessoa();
        if ($pessoa) {
            $telefones = $pessoa->mostrarTelefones();
            if ($telefones) {
                $txt_telefone = $telefones;
            }
            $endereco = $pessoa->getEndereco();
            if ($endereco) {
                $txt_endereco = $endereco->toString();
            }
        }
    }
    $numero = $registro->mostrarNumero();
    if (!empty($numero)) {
        $txt_numero = $registro->mostrarNumero();
    }
    if (!empty($registro->data_validade)) {
        $txt_validade = Escola_Util::formatData($registro->data_validade);
    }
    $txt = $registro->getStatus();
    if ($txt) {
        $txt_status = $txt;
    }
}
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well well-small">
                <div class="page-header">
                    <h4>Cadastro de Credencial</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $txt_id; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $txt_tipo; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Número:</dt>
                    <dd><?php echo $txt_numero; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Validade:</dt>
                    <dd><?php echo $txt_validade; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Data / Hora:</dt>
                    <dd><?php echo $txt_data_hora; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Status:</dt>
                    <dd><?php echo $txt_status; ?></dd>
                </dl>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="well well-small">
                            <div class="page-header">
                                <h4>Beneficiário</h4>
                            </div>
                            <dl class="dl-horizontal">
                                <dt>C.P.F.:</dt>
                                <dd><?php echo $txt_cpf; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Nome:</dt>
                                <dd><?php echo $txt_nome; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Data de Nascimento:</dt>
                                <dd><?php echo $txt_nascimento; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Nome do Pai:</dt>
                                <dd><?php echo $txt_nome_pai; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Data da Mãe:</dt>
                                <dd><?php echo $txt_nome_mae; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Identidade:</dt>
                                <dd><?php echo $txt_rg; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Telefone(s):</dt>
                                <dd><?php echo $txt_telefone; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Endereço:</dt>
                                <dd><?php echo $txt_endereco; ?></dd>
                            </dl>
                        </div>
                    </div>
<?php 
$txt_cpf = $txt_nome = $txt_nascimento = $txt_nome_pai = $txt_nome_mae = $txt_rg = $txt_telefone = $txt_endereco = "--";
if (isset($registro)) {
    $pf = $registro->pegaResponsavel();
    if ($pf) {
        $txt_cpf = Escola_Util::formatCpf($pf->cpf);
        $txt_nome = $pf->nome;

        $txt_nascimento = Escola_Util::formatData($pf->data_nascimento);
        if (!empty($pf->nome_pai)) {
            $txt_nome_pai = $pf->nome_pai;
        }
        if (!empty($pf->nome_mae)) {
            $txt_nome_mae = $pf->nome_mae;
        }
        $rg = $pf->mostrar_identidade();
        if ($rg) {
            $txt_rg = $rg;
        }
        $pessoa = $pf->getPessoa();
        if ($pessoa) {
            $telefones = $pessoa->mostrarTelefones();
            if ($telefones) {
                $txt_telefone = $telefones;
            }
            $endereco = $pessoa->getEndereco();
            if ($endereco) {
                $txt_endereco = $endereco->toString();
            }
        }
    }
}
?>
                    <div class="span6">
                        <div class="well well-small">
                            <div class="page-header">
                                <h4>Responsável</h4>
                            </div>
                            <dl class="dl-horizontal">
                                <dt>C.P.F.:</dt>
                                <dd><?php echo $txt_cpf; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Nome:</dt>
                                <dd><?php echo $txt_nome; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Data de Nascimento:</dt>
                                <dd><?php echo $txt_nascimento; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Nome do Pai:</dt>
                                <dd><?php echo $txt_nome_pai; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Data da Mãe:</dt>
                                <dd><?php echo $txt_nome_mae; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Identidade:</dt>
                                <dd><?php echo $txt_rg; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Telefone(s):</dt>
                                <dd><?php echo $txt_telefone; ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt>Endereço:</dt>
                                <dd><?php echo $txt_endereco; ?></dd>
                            </dl>
                        </div>
                    </div>
                </div>          
            </div>                
        </div>
    </div>
<?php if ($this->ocorrencias) { ?>
    <div class="row-fluid">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th colspan="4">Ocorrências</th>
                    </tr>
                    <tr>
                        <th>Tipo</th>
                        <th>Data / Hora</th>
                        <th>Usuário</th>
                        <th>Observações</th>
                    </tr>
                </thead>
                <tbody>
<?php 
foreach ($this->ocorrencias as $ocor) {
    $txt_data_hora = $txt_usuario = $txt_tipo = $txt_obs = "--";
    $txt_data_hora = Escola_Util::formatData($ocor->ocorrencia_data) . " " . $ocor->ocorrencia_hora;
    $usuario = $ocor->findParentRow("TbUsuario");
    if ($usuario) {
        $txt_usuario = $usuario->toString();
    }
    $cot = $ocor->findParentRow("TbCredencialOcorrenciaTipo");
    if ($cot) {
        $txt_tipo = $cot->toString();
    }
    if (!empty($ocor->obs)) {
        $txt_obs = $ocor->obs;
    }
?>
                    <tr>
                        <td><?php echo $txt_tipo; ?></td>
                        <td><?php echo $txt_data_hora; ?></td>
                        <td><?php echo $txt_usuario; ?></td>
                        <td><?php echo $txt_obs; ?></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
    </div>
<?php } ?>
</div>