<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Mime Type</th>
                            <th>Extensão</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) { 
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->descricao; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->mime_type; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->extensao; ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar" data-toogle="tooltip">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Editar" data-toogle="tooltip">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn btn-primary link_excluir" title="Excluir" data-toogle="tooltip">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php
if ($this->registros) { 
	echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>