<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
<?php if ($this->registro->getId()) { ?>
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
<?php } ?>
                <div class="well">
                    <fieldset>
                        <legend>CADASTRO DE AGENTES DE TRÂNSITO: </legend>
                <?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>ID:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
                <?php } ?>
                        <div class="control-group">
                            <label for="codigo" class="control-label">Código:</label>
                            <div class="controls">
                                <input type="text" name="codigo" id="codigo" size="5" value="<?php echo $this->registro->codigo; ?>" class="span2" />
                            </div>
                        </div>
<?php
$ctrl = new Escola_Form_Element_Select_Table_Funcionario("id_funcionario");
$ctrl->setValue($this->registro->id_funcionario);
$ctrl->setLabel("Funcionário: ");
echo $ctrl->render($this);
?>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>