<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
                <div class="control-group">
                    <label for="filtro_codigo" class="control-label">Código do Agente:</label>
                    <div class="controls">
                        <input type="text" name="filtro_codigo" id="filtro_codigo" size="5" value="<?php echo $this->dados["filtro_codigo"]; ?>" class="span2 filtro" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_matricula" class="control-label">Matrícula:</label>
                    <div class="controls">
                        <input type="text" name="filtro_matricula" id="filtro_matricula" size="5" value="<?php echo $this->dados["filtro_matricula"]; ?>" class="span2 filtro" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_cpf" class="control-label">C.P.F.:</label>
                    <div class="controls">
                        <input type="text" name="filtro_cpf" id="filtro_cpf" value="<?php echo $this->dados["filtro_cpf"]; ?>" class="span2 filtro cpf" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_nome" class="control-label">Nome:</label>
                    <div class="controls">
                        <input type="text" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" class="span5 filtro" size="100" />
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Matrícula</th>
                            <th>C.P.F.</th>
                            <th>Nome</th>
                            <th>Cargo</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) { 
                    $funcionario = $registro->findParentRow("TbFuncionario");
                    $pf = $funcionario->findParentRow("TbPessoaFisica");
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->codigo; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $funcionario->matricula; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatCpf($pf->cpf); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $pf->nome; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $funcionario->findParentRow("TbCargo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "autoinfracao",
                                                                         "id_agente" => $registro->getId(), "id" => "0")); ?>" class="btn" title="Autos de Infração">
                                        <i class="icon-warning-sign"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>