<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Agente > Auto de Infração > Ocorrência > Notificação</h4>
                </div>
<?php if ($this->agente) { ?>
                <dl class="dl-horizontal">
                    <dt>Agente:</dt>
                    <dd><?php echo $this->agente->toString(); ?></dd>
                </dl>
<?php } ?>
                <dl class="dl-horizontal">
                    <dt>Auto de Infração:</dt>
                    <dd><?php echo $this->ai->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ocorrência:</dt>
                    <dd><?php echo $this->ocorrencia->toString(); ?></dd>
                </dl>
<?php echo $this->registro->view($this); ?>
        </div>
    </div>
</div>