<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Vínculo entre Serviço e Grupo de Transporte</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Id:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Serviço:</dt>
                    <dd><?php echo $this->servico->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Grupo de Transporte:</dt>
                    <dd><?php echo $this->transporte_grupo->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Periodicidade:</dt>
                    <dd><?php echo ($per = $this->registro->findParentRow("TbPeriodicidade")) ? $per->toString() : "--"; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Mês Referência:</dt>
                    <dd><?php echo ($this->registro->mes_referencia) ? Escola_Util::pegaMes($this->registro->mes_referencia) : "--"; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor:</dt>
                    <dd><?php echo $this->registro->pega_valor()->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Validade em Dias:</dt>
                    <dd><?php echo $this->registro->validade_dias; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Dias para o Vencimento:</dt>
                    <dd><?php echo $this->registro->vencimento_dias; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Juros por Dia de Atraso:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->juros_dia); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Obrigatório:</dt>
                    <dd><?php echo $this->registro->mostrar_obrigatorio(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Emite Documento:</dt>
                    <dd><?php echo ($this->registro->emite_documento) ? "SIM" : "NÃO"; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>