<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Serviço</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Id:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbServicoTipo"); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->codigo; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição:</dt>
                    <dd><?php echo $this->registro->descricao; ?></dd>
                </dl>
<?php
$servico_referencia = "--";
$sr = $this->registro->findParentRow("TbServicoReferencia");
if ($sr) {
    $servico_referencia = $sr->toString();
}
?>
                <dl class="dl-horizontal">
                    <dt>Tipo Referência:</dt>
                    <dd><?php echo $servico_referencia; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>