<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Descrição</th>
                        <th>Nome classe</th>
                        <th>Ativo</th>
                        <th width="20px">Operações</th>
                    </tr>
                </thead>
                <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
                        <?php
                        foreach ($this->registros as $registro) {
                        ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                        <?php echo $registro->tipo; ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                        <?php echo $registro->descricao; ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                        <?php echo $registro->nome_classe; ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                        <?php echo $registro->ativo ? "Sim" : "Não"; ?>
                                    </a>
                                </td>

                                <td>
                                    <div class="btn-group">
                                        <a href="<?php echo $this->url(array(
                                                        "controller" => $this->getRequest()->getControllerName(),
                                                        "action" => "editar",
                                                        "id" => $registro->getId()
                                                    )); ?>" class="btn" title="Editar">
                                            <i class="icon-cog"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                <?php } ?>
            </table>
            <?php if ($this->registros && count($this->registros)) {
                echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
            }
            ?>
        </div>
    </div>
</div>