<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "arquivo")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->documento->getId(); ?>" />
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Documento:</dt>
                        <dd><?php echo $this->documento->toString(); ?></dd>
                    </dl>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Miniatura</th>
                            <th>Data Envio</th>
                            <th>Tamanho</th>
                            <th>Descrição</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
                    $arquivo = $registro->pegaObjeto();
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                    <?php echo $arquivo->miniatura(array("width" => 50, "align" => "left")); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($arquivo->data_upload); ?> <?php echo $arquivo->hora_upload; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo Escola_Util::mostrarTamanho($arquivo->tamanho); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewarquivo", "id_documento_ref" => $registro->getId())); ?>">
                                <?php echo $arquivo->legenda; ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "viewarquivo",
                                                                         "id_documento_ref" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editararquivo",
                                                                         "id_documento_ref" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirarquivo",
                                                                         "id_documento_ref" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            <?php // echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
            </form>
        </div>
    </div>
</div>