<script type="text/javascript">
    $(document).ready(function() {
        $("#marca_todos").change(function() {
            $(".lista_id").prop("checked", $(this).prop("checked"));
            $(".lista_id").change();
        });
        $(".lista_id").change(function() {
            $("#btn_encaminhar").hide();
            var ctrl_checked = $(".lista_id:checked");
            if (ctrl_checked && ctrl_checked.length) {
                $("#btn_encaminhar").show();
            }
        });
        $("#btn_encaminhar").hide();
    });
    
    function encaminhar() {
        $("#formulario").prop("action", "<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "encaminhamultipla"), null, true); ?>");
        $("#formulario").submit();
    }
</script>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName(), "page" => $this->getRequest()->getParam("page")), null, true); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name="operacao" id="operacao" />
                <input type="hidden" name="jan_pagina" id="jan_pagina" />
                <input type="hidden" name="jan_id_documento" id="jan_id_documento" />

<div id="janela_vinculo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Localizar Documento a Vincular</h3>
    </div>
    <div class="modal-body">
        <div class="well well-small">
            <fieldset>
                <dl class="dl-horizontal">
                    <dt>Documento:</dt>
                    <dd id="info_documento"></dd>
                </dl>
                <div class="control-group">
                    <label for="" class="control-label">Tipo:</label>
                    <div class="controls">
                <?php
                $tb = new TbDocumentoTipoTarget();
                $dtt = $tb->getPorChave("D");
                if ($dtt) {
                    $tb = new TbDocumentoTipo();
                    $dts = $tb->listar(array("filtro_id_documento_tipo_target" => $dtt->getId()));
                    if ($dts) {
                ?>
                                                        <select name="jan_id_documento_tipo" id="jan_id_documento_tipo">
                                                            <option value="" selected>==> SELECIONE <==</option>
                <?php foreach ($dts as $dt) { ?>
                <?php if (!$dt->processo()) { ?>
                                                            <option value="<?php echo $dt->getId(); ?>"><?php echo $dt->toString(); ?></option>
                <?php }} ?>
                                                        </select>
                <?php }} ?>			

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="jan_numero">Número / Ano:</label>
                    <div class="controls">
                        <input type="text" name="jan_numero" id="jan_numero" value="" class="filtro span3" /> / <input type="text" name="jan_ano" id="jan_ano" value="" class="filtro span2"  />
                    </div>
                </div>
            </fieldset>
        </div>
        <table id="destino_resposta" class="table table-striped table-bordered" style="display:none">
            <thead class="head_destino"></thead>
            <tbody class="corpo_destino"></tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="button" value="Limpar Filtro" id="bt_destino_limpar" class="filtro_busca btn" />
        <input type="submit" value="Procurar" class="filtro_busca btn btn-primary" />
    </div>
</div>                
                
<div id="janela_processo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Tornar Processo</h3>
    </div>
    <div class="modal-body">
        <div class="alert alert-info">
            Para numeração automática, basta deixar os campos em brando.
        </div>
        <fieldset>
            <div class="control-group">
                <label for="" class="control-label">Número do Processo:</label>            
                <div class="controls">
                    <input type="text" name="numero" id="numero" class="span4" maxlength="50" value="" /> /
                    <input type="text" name="ano" id="ano" maxlength="4" value="" class="span3" />
                </div>
            </div>
        </fieldset>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="button" value="Confirmar" class="btn btn-primary" id="bt_janela_confirmar" />
    </div>
</div>                

<div id="janela_arquivar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Receber</h3>
    </div>
    <div class="modal-body">
        Confirmar Recebimento do Documento?
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="button" value="Confirmar" id="bt_arquivar_confirmar" class="btn btn-primary" />
    </div>
</div>                

          <div class="well well-small" id="idPesquisa">
              <div class="page-header">
                  <h4>Opções de Pesquisa</h4>
              </div>
              <div class="control-group">
                  <label for="filtro_opcao" class="control-label">Opções de Filtro:</label>
                  <div class="controls">
                      <select name="filtro_opcao" id="filtro_opcao" class="filtro span5">
                        <option value="" <?php echo (!$this->dados["filtro_opcao"])?"selected":""; ?>>==> SELECIONE <==</option>
                        <option value="R" <?php echo ("R" == $this->dados["filtro_opcao"])?"selected":""; ?>>A RECEBER</option>
                        <option value="S" <?php echo ("S" == $this->dados["filtro_opcao"])?"selected":""; ?>>DOCUMENTOS QUE ESTÃO NO SETOR</option>
                        <option value="P" <?php echo ("P" == $this->dados["filtro_opcao"])?"selected":""; ?>>DOCUMENTOS QUE PERTENCEM AO SETOR</option>
                    </select>
                    <input type="checkbox" name="filtro_avancado" id="filtro_avancado" />Mais Opções de Pesquisa
                  </div>
              </div>
             <?php
            $tb = new TbDocumentoTipoTarget();
            $dtt = $tb->getPorChave("D");
            if ($dtt) {
                $tb = new TbDocumentoTipo();
                $dts = $tb->listar(array("filtro_id_documento_tipo_target" => $dtt->getId()));
                if ($dts) {
            ?>
             <div class="control-group linha_avancado">
                  <label for="filtro_id_documento_tipo" class="control-label">Tipo de Documento:</label>
                  <div class="controls">
                      <select name="filtro_id_documento_tipo" id="filtro_id_documento_tipo" class="filtro filtro_avancado">
                                                        <option value="" <?php echo (!$this->dados["filtro_id_documento_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
            <?php foreach ($dts as $dt) { ?>
                                                        <option value="<?php echo $dt->getId(); ?>" <?php echo ($dt->getId() == $this->dados["filtro_id_documento_tipo"])?"selected":""; ?>><?php echo $dt->toString(); ?></option>
            <?php } ?>
                    </select>
                  </div>
              </div>
<?php }} ?>
 <?php
                $tb = new TbDocumentoModo();
                $dms = $tb->listar();
                if ($dms) {
            ?>
              <div class="control-group linha_avancado">
                  <label for="filtro_id_documento_modo" class="control-label">Modo:</label>
                  <div class="controls">
                      <select name="filtro_id_documento_modo" id="filtro_id_documento_modo" class="filtro filtro_avancado">
                                                        <option value="" <?php echo (!$this->dados["filtro_id_documento_modo"])?"selected":""; ?>>==> SELECIONE <==</option>
            <?php foreach ($dms as $dm) { ?>
                                                        <option value="<?php echo $dm->getId(); ?>" <?php echo ($dm->getId() == $this->dados["filtro_id_documento_modo"])?"selected":""; ?>><?php echo $dm->toString(); ?></option>
            <?php } ?>
                    </select>
                  </div>
              </div>
<?php } ?>
              <div class="control-group linha_avancado">
                  <label for="filtro_numero" class="control-label">Número:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span2" name="filtro_numero" id="filtro_numero" value="<?php echo $this->dados["filtro_numero"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_ano" class="control-label">Ano:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span1" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_setor" class="control-label">Setor:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span5" name="filtro_setor" id="filtro_setor" value="<?php echo $this->dados["filtro_setor"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_funcionario" class="control-label">Nome Criador:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span5" name="filtro_funcionario" id="filtro_funcionario" value="<?php echo $this->dados["filtro_funcionario"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_interessado" class="control-label">Interessado:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span5" name="filtro_interessado" id="filtro_interessado" value="<?php echo $this->dados["filtro_interessado"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_data_inicial" class="control-label">Data Inicial:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span2 data" name="filtro_data_inicial" id="filtro_data_inicial" value="<?php echo $this->dados["filtro_data_inicial"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_data_final" class="control-label">Data Final:</label>
                  <div class="controls">
                      <input type="text" class="filtro filtro_avancado span2 data" name="filtro_data_final" id="filtro_data_final" value="<?php echo $this->dados["filtro_data_final"]; ?>" />
                  </div>
              </div>
              <div class="control-group linha_avancado">
                  <label for="filtro_resumo" class="control-label">Resumo:</label>
                  <div class="controls">
                      <textarea name="filtro_resumo" id="filtro_resumo" rows="4" class="filtro filtro_avancado span5"><?php echo $this->dados["filtro_resumo"]; ?></textarea>
                  </div>
              </div>
<?php
    $tb = new TbDocumentoStatus();
    $dss = $tb->listar();
    if ($dss) {
?>
              <div class="control-group linha_avancado">
                  <label for="filtro_id_documento_status" class="control-label">Situação:</label>
                  <div class="controls">
                      <select name="filtro_id_documento_status" id="filtro_id_documento_status" class="filtro filtro_avancado">
                                                        <option value="" <?php echo (!$this->dados["filtro_id_documento_status"])?"selected":""; ?>>==> SELECIONE <==</option>
            <?php foreach ($dss as $ds) { ?>
                                                        <option value="<?php echo $ds->getId(); ?>" <?php echo ($ds->getId() == $this->dados["filtro_id_documento_status"])?"selected":""; ?>><?php echo $ds->toString(); ?></option>
            <?php } ?>
                    </select>
                  </div>
              </div>
<?php } ?>
              <div class="control-group">
                  <div class="controls">
                        <input type="submit" value="Pesquisar" class="btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />                      
                  </div>
              </div>
          </div>
                
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
<?php if ($this->registros && count($this->registros)) { ?>
                                <input type="checkbox" name="" id="marca_todos" />
<?php } ?>
                            </th>
                            <th>Data / Hora</th>
                            <th>Tipo</th>
                            <th>Número</th>
                            <th>Procedência</th>
                            <th>Setor</th>
                            <th>Funcionário</th>
                            <th>Interessado</th>
                            <th>Resumo</th>
                            <th>Localização Atual</th>
                            <th>Situação</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
                    $atual = $registro->pegaSetorAtual();
                    $habEncaminhar = $registro->habilitaEncaminhar($this->funcionario);
            ?>
                        <tr>
                            <td><input type="checkbox" name="lista_id[]" class="lista_id" value="<?php echo $registro->getId(); ?>" /></td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_criacao); ?> - <?php echo $registro->hora_criacao; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbDocumentoTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarNumero(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarProcedencia(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbSetor")->sigla; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbFuncionario")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarInteressado(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->resumo; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $atual->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbDocumentoStatus")->toString(); ?>
            <?php if ($registro->fora_do_prazo()) { ?>
                                <strong> - EM ATRASO</strong>
            <?php } ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
            <?php if ($registro->habilitaAlterar($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
            <?php } ?>
            <?php if ($registro->habilitaAlterar($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
            <?php } ?>
            <?php if ($habEncaminhar) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "arquivo",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Anexos">
                                        <i class="icon-paper-clip"></i>														 
                                    </a>
            <?php } ?>
            <?php if ($registro->habilitaReceber($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "receber",
                                                                         "id" => $registro->getId())); ?>" class="btn link_receber" title="Receber">
                                        <i class="icon-download-alt"></i>
                                    </a>
            <?php } ?>
            <?php if ($registro->habilitaEncaminhar($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "encaminhar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Encaminhar">
                                        <i class="icon-share"></i>
                                    </a>
            <?php } ?>
            <?php if ($registro->habilitaArquivar($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "arquivar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Arquivar">
                                        <i class="icon-lock"></i>
                                    </a>
            <?php } ?>
            <?php if ($registro->habilitaCancelarArquivar($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "cancelar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Cancelar Arquivamento">
                                        <i class="icon-unlock"></i>
                                    </a>
            <?php } ?>
            <?php if ($registro->habilitaTornarProcesso($this->funcionario)) { ?>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "processo",
                                                                         "id" => $registro->getId())); ?>" class="btn link_processo" title="Tornar Processo">
                                        <i class="icon-book"></i>
                                    </a>
            <?php } ?>
            <?php if ($habEncaminhar) { ?>
                                    <a href="#" class="link_vincular btn" id="<?php echo $registro->getid(); ?>" title="Vincular Documento">
                                        <i class="icon-retweet"></i>
                                    </a>
            <?php } ?>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            </form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>