<script type="text/javascript">
$(document).ready(
	function() {
        //DESTINO
        $("#link_destino").click(
            function(event) {
                event.preventDefault();
                $("#jan_pagina").val("");
                $("#janela_destino").modal("show");
            }
        );
        $("#jan_tipo_destino").change(
            function() {
                $("#jan_pagina").val("");
                procurarDestino();
            }
        );
        $(".bt_destino_cancelar").click(
            function() {
                fecharDestino();
            }
        );
        $("#bt_destino_limpar").click(
            function() {
                $("#janela_destino .filtro").val("");
                procurarDestino();
            }
        );
        $("#janela_destino").css( { "width": "800px", "margin-left": "-400px" } ).modal("hide");
        $("#janela_destino").on("shown", function() {
            $("#jan_tipo_destino").val($("#tipo_destino").val());
            $("#operacao").val("destino");
            $(".link_destino, #janela_destino .filtro").val("");
            procurarDestino();            
        });
        $("#janela_destino").on("hide", function() {
            $("#operacao").val("");
        });
        $("#janela_destino").on("keypress", function(event) {
            if (event.which == 13) {
                event.preventDefault(); 
                $("#formulario").submit();
            }
        });
	}
);

function procurarDestino() {
    var ctrls = $("#destino_busca .filtro_busca");
    var obj = $("#jan_tipo_destino");
    ctrls.hide();
    if (obj.val().length) {
        ctrls.show();
    }
    $("#destino_resposta, .linha_filtro").hide();
    switch (obj.val()) {
        case "F":
            $("#destino_busca .filtro_funcionario, #destino_busca .filtro_pessoa").show();
            buscarDestinoFuncionario();
            break;
        case "S":
            $("#destino_busca .filtro_setor").show();
            buscarDestinoSetor();
            break;
    }
}

function fecharDestino() {
    $("#janela_destino").modal("hide");
}

function buscarDestinoSetor() {
    $("#destino_resposta tr").remove();
    $("#destino_resposta").hide();
    var ajax_obj = $.ajax({
        "url" : "<?php echo Escola_Util::getBaseUrl(); ?>/setor/listarporpagina/format/json/",
        "type" : "POST",
        "data" : { "filtro_criterio": $("#jan_destino_criterio").val(),
                   "pagina_atual": $("#jan_pagina").val(),
                   "filtro_id_setor_procedencia": $("#id_setor_procedencia").val(),
                   "setor_tipo" : "I",
                   "qtd_por_pagina": 20 },
        "success" : function(result) {
            destinos = [];
            $('<tr><th width="50px">ID</th><th width="160px">Sigla</th><th>Descrição</th></tr>').appendTo($(".head_destino"));
            if (result.items && result.items.length) {
                for (var i = 0; i < result.items.length; i++) {
                    var item = result.items[i];
                    destinos[i] = item;
                    var tr = $('<tr class="linha_resultado"></tr>').appendTo($("#destino_resposta"));
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.id + '</a></td>').appendTo(tr);
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.sigla + '</a></td>').appendTo(tr);
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.descricao + '</a></td>').appendTo(tr);
                    tr.appendTo($(".corpo_destino"));
                }
                $(".link_destino").click(
                    function(event) {
                        event.preventDefault();
                        $("#show_destino").val(destinos[$(this).attr("id")].sigla + " - " + destinos[$(this).attr("id")].descricao);
                        $("#tipo_destino").val($("#jan_tipo_destino").val());
                        $("#id_destino").val(destinos[$(this).attr("id")].id);
                        fecharDestino();
                    }
                );
                var paginacao = new Paginacao();
                paginacao.total_pagina = result.total_pagina;
                paginacao.pagina_atual = result.pagina_atual;
                paginacao.primeira = result.primeira;
                paginacao.ultima = result.ultima;
                var html = paginacao.render();
                $('<tr class="linha_resultado"><td align="center" colspan="3">' + html + '</td></tr>').appendTo($("#destino_resposta"));
            } else {
                $("<tr class='linha_resultado'><td colspan='3' align='center'>NEHUM REGISTRO LOCALIZADO!</td></tr>").appendTo($("#destino_resposta"));
            }
            $("#janela_destino .filtro").first().focus();
            $("#destino_resposta").show();
            $("#mask2").height($(document).height());
        }
    });
}

function buscarDestinoFuncionario() {
    $("#destino_resposta tr").remove();
    $("#destino_resposta").hide();
    var ajax_obj = $.ajax({
        "url" : "<?php echo Escola_Util::getBaseUrl(); ?>/funcionario/listarporpagina/format/json/",
        "type" : "POST",
        "data" : { "filtro_cpf": $("#destino_filtro_cpf").val(),
                   "filtro_matricula": $("#destino_filtro_matricula").val(), 
                   "filtro_nome": $("#destino_filtro_nome").val(),
                   "pagina_atual": $("#jan_pagina").val(),
                   "filtro_id_setor_procedencia": $("#id_setor_procedencia").val(),
                   "qtd_por_pagina": 20 },
        "success" : function(result) {
            destinos = [];
            $('<tr><th width="50px">ID</th><th>Matrícula</th><th>Nome</th><th>Cargo</th><th>Setor</th></tr>').appendTo($(".head_destino"));
            if (result.items && result.items.length) {
                for (var i = 0; i < result.items.length; i++) {
                    var item = result.items[i];
                    destinos[i] = item;
                    var tr = $('<tr class="linha_resultado"></tr>').appendTo($("#destino_resposta"));
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.id + '</a></td>').appendTo(tr);
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.matricula + '</a></td>').appendTo(tr);
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.nome + '</a></td>').appendTo(tr);
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.cargo + '</a></td>').appendTo(tr);
                    $('<td><a href="#" id="' + i + '" class="link_destino">' + item.setor + '</a></td>').appendTo(tr);
                    tr.appendTo($(".corpo_destino"));
                }
                $(".link_destino").click(
                    function(event) {
                        event.preventDefault();
                        $("#show_destino").val(destinos[$(this).attr("id")].matricula + " - " + destinos[$(this).attr("id")].nome);
                        $("#tipo_destino").val($("#jan_tipo_destino").val());
                        $("#id_destino").val(destinos[$(this).attr("id")].id);
                        fecharDestino();
                    }
                );
                var paginacao = new Paginacao();
                paginacao.total_pagina = result.total_pagina;
                paginacao.pagina_atual = result.pagina_atual;
                paginacao.primeira = result.primeira;
                paginacao.ultima = result.ultima;
                var html = paginacao.render();
                $('<tr class="linha_resultado"><td align="center" colspan="5">' + html + '</td></tr>').appendTo($("#destino_resposta"));
            } else {
                $("<tr class='linha_resultado'><td colspan='5' align='center'>NEHUM REGISTRO LOCALIZADO!</td></tr>").appendTo($("#destino_resposta"));
            }
            $("#janela_destino .filtro").first().focus();
            $("#destino_resposta").show();
            $("#mask2").height($(document).height());
        }
    });
}
</script>

<div id="janela_destino" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Localizar Destino</h3>
    </div>
    <div class="modal-body">
        <div class="well well-small" id="destino_busca">
            <fieldset>
                <div class="control-group">
                    <label for="jan_tipo_destino" class="control-label">Tipo:</label>
                    <div class="controls">
                        <select name="jan_tipo_destino" id="jan_tipo_destino">
                            <option value="">==> SELECIONE <==</option>
                            <option value="F">FUNCIONÁRIO</option>
                            <option value="S">SETOR</option>
                        </select>
                    </div>
                </div>
                <div class="control-group filtro_busca filtro_funcionario linha_filtro">
                    <label for="destino_filtro_matricula" class="control-label">Matrícula:</label>
                    <div class="controls">
                        <input type="text" name="filtro_matricula" id="destino_filtro_matricula" value="" class="filtro" />
                    </div>
                </div>
                <div class="control-group filtro_busca filtro_pessoa linha_filtro">
                    <label for="destino_filtro_cpf" class="control-label">C.P.F.:</label>
                    <div class="controls">
                        <input type="text" name="filtro_cpf" id="destino_filtro_cpf" value="" class="filtro cpf" />
                    </div>
                </div>
                <div class="control-group filtro_busca filtro_pessoa linha_filtro">
                    <label for="destino_filtro_nome" class="control-label">Nome:</label>
                    <div class="controls">
                        <input type="text" name="filtro_nome" id="destino_filtro_nome" value="" size="60" class="filtro" />
                    </div>
                </div>
                <div class="control-group filtro_busca filtro_setor linha_filtro">
                    <label for="jan_destino_criterio" class="control-label">Nome:</label>
                    <div class="controls">
                        <input type="text" name="jan_destino_criterio" id="jan_destino_criterio" value="" size="60" class="filtro" />
                    </div>
                </div>
            </fieldset>
        </div>
        <table id="destino_resposta" class="table table-striped table-bordered" style="display:none">
            <thead class="head_destino"></thead>
            <tbody class="corpo_destino"></tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
		<input type="button" value="Limpar Filtro" id="bt_destino_limpar" class="filtro_busca btn" />
        <input type="submit" value="Procurar" class="btn btn-primary filtro_busca" />
    </div>
</div>