<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario">
            <?php
            echo $this->registro->view($this);
            $anexos = $this->registro->pegaAnexos();
            if ($anexos) {
            ?>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th colspan="6">
                            Arquivos Anexos
                        </th>
                    </tr>
                    <tr>
                        <th width="60px">Tipo</th>
                        <th width="180px">Data / Hora</th>
                        <th>Tamanho</th>
                        <th>Legenda</th>
                    </tr>
                    </thead>
            <?php 
            foreach ($anexos as $anexo) {
                $doc = $anexo->pegaObjeto(); 
                $url_arquivo = Escola_Util::url(array("controller" => "arquivo", "action" => "view", "id" => $doc->getId()));
            ?>
                    <tr>
                        <td>
                            <div align="left">
                                <a href="<?php echo $url_arquivo; ?>">
                                    <?php echo $doc->miniatura(array("width" => 50, "align" => "left")); ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $url_arquivo; ?>">
                                    <?php echo Escola_Util::formatData($doc->data_upload); ?> - <?php echo $doc->hora_upload; ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $url_arquivo; ?>">
                                    <?php echo Escola_Util::mostrarTamanho($doc->tamanho); ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $url_arquivo; ?>">
                                    <?php echo $doc->legenda; ?>
                                </a>
                            </div>
                        </td>
                    </tr>
            <?php } ?>
                </table>
            <?php } ?>
            <?php
            $anexos = $this->registro->pegaTbDocumento();
            if ($anexos) {
            ?>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th colspan="6">
                            Documentos Vinculados
                        </th>
                    </tr>
                    <tr>
                        <th width="180px">Data / Hora</th>
                        <th>Tipo</th>
                        <th>Número</th>
                        <th>Interessado</th>
                        <th>Resumo</th>
                        <th>Tipo Anexo</th>
                    </tr>
                    </thead>
            <?php 
            foreach ($anexos as $anexo) {
                $doc = $anexo->pegaObjeto(); 
            ?>
                    <tr>
                        <td>
                            <div align="left">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "view", "id" => $doc->getId(), "flag" => true), null, true); ?>">
                                    <?php echo Escola_Util::formatData($doc->data_criacao); ?> - <?php echo $doc->hora_criacao; ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "view", "id" => $doc->getId(), "flag" => true), null, true); ?>">
                                    <?php echo $doc->findParentRow("TbDocumentoTipo")->toString(); ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "view", "id" => $doc->getId(), "flag" => true), null, true); ?>">
                                    <?php echo $doc->mostrarNumero(); ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "view", "id" => $doc->getId(), "flag" => true), null, true); ?>">
                                    <?php echo $doc->mostrarInteressado(); ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "view", "id" => $doc->getId(), "flag" => true), null, true); ?>">
                                    <?php echo $doc->resumo; ?>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div align="left">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "view", "id" => $doc->getId(), "flag" => true), null, true); ?>">
                                    <?php echo $anexo->mostrarTipo(); ?>
                                </a>
                            </div>
                        </td>
                    </tr>
            <?php } ?>
                </table>
            <?php } ?>
            <?php
            $movs = $this->registro->pegaMovimentacao();
            if ($movs) {
            ?>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th colspan="8">
                            Movimentações
                        </th>
                    </tr>
                    <tr>
                        <th>Data / Hora</th>
                        <th>Tipo</th>
                        <th>Setor</th>
                        <th>Funcionário</th>
                        <th>Despacho</th>
                        <th>Destino</th>
                        <th>Status</th>
                        <th width="20px"></th>
                    </tr>
                    </thead>
            <?php foreach ($movs as $mov) { 
                $mot_tipo = $mov->findParentRow("TbMovimentacaoTipo");
                ?>
                    <tr>
                        <td><div align="center"><?php echo Escola_Util::formatData($mov->data_movimentacao); ?> - <?php echo $mov->hora_movimentacao; ?></div></td>
                        <td><div align="center"><?php echo $mov->findParentRow("TbMovimentacaoTipo")->toString(); ?></div></td>
                        <td><div align="left"><?php echo $mov->findParentRow("TbSetor")->toString(); ?></div></td>
                        <td><div align="left"><?php echo $mov->findParentRow("TbFuncionario")->toString(); ?></div></td>
                        <td><div align="left"><?php echo $mov->despacho; ?></div></td>
                        <td><div align="left"><?php echo $mov->mostrarDestino(); ?></div></td>
                        <td><div align="left"><?php echo $mov->mostrarStatus(); ?></div></td>
                        <td>
<?php 
$id_setor = 0;
$tb = new TbFuncionario();
$funcionario = $tb->pegaLogado();
if ($funcionario) {
    $lotacao = $funcionario->pegaLotacaoAtual();
    if ($lotacao) {
        $id_setor = $lotacao->id_setor;
    }
}
if ($mot_tipo->envio() && $mov->pendente() && ($id_setor == $this->registro->id_setor_atual)) { 
?>
                            <div align="center">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirmovimentacao",
                                                                         "id" => $mov->getId())); ?>" class="btn link_excluir" title="Excluir Movimentação"><i class="icon-trash"></i></a>
                            </div>
<?php } ?>
                        </td>
                    </tr>
<?php } ?>
                </table>
<?php } ?>
            </form>
        </div>
    </div>
</div>