<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
<?php if ($this->registro->getId()) { ?>
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
<?php } ?>
                <div class="well">
                    <fieldset>
                        <legend>ATRIBUIR AUTO DE INFRAÇÃO: </legend>
                        <dl class="dl-horizontal">
                            <dt>ID:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Código:</dt>
                            <dd><?php echo $this->registro->mostrar_codigo(); ?></dd>
                        </dl>
<?php 
$ctrl = new Escola_Form_Element_Select_Table("id_agente");
$ctrl->setPkName("id_agente");
$ctrl->setModel("TbAgente");
$ctrl->setValue("");
$ctrl->setLabel("Agente:");
$ctrl->setAttrib("class", "span5");
echo $ctrl->render($this);
?>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>