<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "licencapgto")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <div class="well well-small">
                    <fieldset>
                        <legend>CONFIRMAR PAGAMENTO DE AUTO DE INFRAÇÃO: </legend>
<?php echo $this->registro->form_pagamento($this); ?>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>