<div class="conteudo_controller">
    <div class="row-fluid">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>
                <div class="control-group">
                    <label for="filtro_placa" class="control-label">Placa:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2" name="filtro_placa" id="filtro_placa" value="<?php echo $this->dados["filtro_placa"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_chassi" class="control-label">Chassi:</label>
                    <div class="controls">
                        <input type="text" class="filtro span2" name="filtro_chassi" id="filtro_chassi" value="<?php echo $this->dados["filtro_chassi"]; ?>" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="filtro_proprietario" class="control-label">Nome Proprietário:</label>
                    <div class="controls">
                        <input type="text" class="filtro span5" name="filtro_proprietario" id="filtro_proprietario" value="<?php echo $this->dados["filtro_proprietario"]; ?>" />
                    </div>
                </div>
<?php 
$ctrl = new Escola_Form_Element_Select_Table("filtro_id_fabricante");
$ctrl->setAttrib("class", "filtro");
$ctrl->setPkName("id_fabricante");
$ctrl->setModel("TbFabricante");
$ctrl->setValue($this->dados["filtro_id_fabricante"]);
$ctrl->setLabel("Fabricante:");
echo $ctrl->render($this);
?>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Chassi</th>
                            <th>Placa</th>
                            <th>Tipo</th>
                            <th>Categoria</th>
                            <th>Proprietário</th>
                            <th>Estado</th>
                            <th>Combustível</th>
                            <th>Fabricante</th>
                            <th>Ano Fabricação</th>
                            <th>Data Aquisição</th>
                            <th>Renavan</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
<?php 
    foreach ($this->registros as $registro) { 
        $txt_vc = "--";
        $vc = $registro->findParentRow("TbVeiculoCategoria");
        if ($vc) {
            $txt_vc = $vc->toString();
        }
        $txt_pessoa = "--";
        $pessoa = $registro->findParentRow("TbPessoa");
        if ($pessoa) {
            $txt_pessoa = $pessoa->toString();
        }
?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->chassi; ?>
                                </a>
                            </td>                            
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->placa; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbVeiculoTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $txt_vc; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $txt_pessoa; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbUf")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbCombustivel")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbFabricante")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->ano_fabricacao; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_aquisicao); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->renavan; ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
<?php if ($this->registros && count($this->registros)) {
 echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>