<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Veículo</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Id:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbVeiculoTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Categoria:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbVeiculoCategoria")->toString(); ?></dd>
                </dl>
<?php
$txt = "--";
$pessoa = $this->registro->findParentRow("TbPessoa");
if ($pessoa) {
    $txt = $pessoa->toString();
}
?>
                <dl class="dl-horizontal">
                    <dt>Proprietário:</dt>
                    <dd><?php echo $txt; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Chassi:</dt>
                    <dd><?php echo $this->registro->chassi; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Placa:</dt>
                    <dd><?php echo $this->registro->placa; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Município:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbMunicipio")->toString(); ?> / <?php echo $this->registro->findParentRow("TbUf")->sigla; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Cor:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbCor")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Combustível:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbCombustivel")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Fabricante:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbFabricante")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ano Fabricação:</dt>
                    <dd><?php echo $this->registro->ano_fabricacao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ano Modelo:</dt>
                    <dd><?php echo $this->registro->ano_modelo; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Modelo:</dt>
                    <dd><?php echo $this->registro->modelo; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Data Aquisição:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_aquisicao); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Renavan:</dt>
                    <dd><?php echo $this->registro->renavan; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>DUT:</dt>
                    <dd><?php echo $this->registro->dut; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tara:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->tara); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Lotação:</dt>
                    <dd><?php echo $this->registro->lotacao; ?> Pessoas</dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Isento:</dt>
                    <dd><?php echo $this->registro->mostrar_isento(); ?></dd>
                </dl>
            </div>
<?php if ($this->transporte_veiculo) { ?>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th colspan="3">Vínculos de Transporte</th>
                </tr>
                <tr>
                    <th>Transporte</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
<?php foreach ($this->transporte_veiculo as $tv) { ?>
                <tr>
                    <td><?php echo $tv->findParentRow("TbTransporte")->toString(); ?></td>
                    <td><?php echo $tv->findParentRow("TbTransporteVeiculoStatus")->toString(); ?></td>
                </tr>
<?php } ?>
            </tbody>
        </table>
<?php } ?>
<?php echo $this->registro->mostrarTabelaNotificacao(); ?>
        </div>
    </div>
</div>