<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered tabela_mensagem">
                <thead>
                    <tr>
                        <th></th>
                        <th>Data / Hora</th>
                        <th>Tipo</th>
                        <th>Autor</th>
                        <th>Destinatário</th>
                        <th>Assunto</th>
                    </tr>
                </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
                <tbody>
        <?php 
            foreach ($this->registros as $registro) {
                $registro = TbMensagem::pegaPorId($registro["id_mensagem"]);
                $class = "";
                $img = "icon-envelope";
                $usuario = Escola_Acl::getInstance()->getUsuarioLogado();
                if (!$registro->lido($usuario)) {
                    $class = 'class="nao-lido" ';
                    $img = "icon-envelope";
                }
        ?>
                    <tr <?php echo $class; ?>>
                        <td width="25px">
                            <a href="<?php echo $this->url(array("action" => "visualizar", "id_mensagem" => $registro->getId())); ?>">
                                <i class="<?php echo $img; ?> icon-large"></i>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "visualizar", "id_mensagem" => $registro->getId())); ?>">
                                <?php echo Escola_Util::formatData($registro->data); ?> <?php echo $registro->hora; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "visualizar", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbMensagemTipo")->toString(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "visualizar", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbUsuario")->pega_pessoa_fisica()->nome; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "visualizar", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->mostrarDestinatario(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "visualizar", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->assunto; ?>
                            </a>
                        </td>
                    </tr>
        <?php } ?>
                </tbody>
        <?php } ?>
            </table>
<?php
if ($this->registros) {
	echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>
    </div>
</div>