<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Data / Hora</th>
                        <th>Tipo</th>
                        <th>Destinatário</th>
                        <th>Assunto</th>
                        <th colspan="5">Operações</th>
                    </tr>
                </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
                <tbody>
        <?php 
            foreach ($this->registros as $registro) {
        ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id_mensagem" => $registro->getId())); ?>">
                                <?php echo Escola_Util::formatData($registro->data); ?> <?php echo $registro->hora; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->findParentRow("TbMensagemTipo")->toString(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->mostrarDestinatario(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id_mensagem" => $registro->getId())); ?>">
                            <?php echo $registro->assunto; ?>
                            </a>
                        </td>
                        <td width="20px">
                            <div class="btn-group">
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "view",
                                                                     "id_mensagem" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                    <i class="icon-search"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "editar",
                                                                     "id_mensagem" => $registro->getId())); ?>" class="btn" title="Editar">
                                    <i class="icon-cog"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "excluir",
                                                                     "id_mensagem" => $registro->getId())); ?>" class="btn btn-primary link_excluir" title="Excluir">
                                    <i class="icon-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
        <?php } ?>
                </tbody>
        <?php } ?>
            </table>
<?php
if ($this->registros) {
	echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
}
?>
        </div>  
    </div>
</div>