<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Visualizar Mensagem</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Data / Hora:</dt>
                    <dd><?php echo $this->formatData($this->registro->data); ?> <?php echo $this->registro->hora; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbMensagemTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Autor:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbUsuario")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Destinatário:</dt>
                    <dd><?php echo $this->registro->mostrarDestinatario(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Assunto:</dt>
                    <dd><?php echo $this->registro->assunto; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Mensagem:</dt>
                    <dd>
                        <div class="well well-small">
                        <?php echo $this->registro->mensagem; ?>
                        </div>
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>