<?php $status = $this->lote->findParentRow("TbVinculoLoteStatus"); ?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <input type="hidden" name="id" id="id" value="<?php echo $this->getRequest()->getParam("id"); ?>" />
    <input type="hidden" name="operacao" id="operacao" />
    <input type="hidden" name="tipo" id="tipo" value="<?php echo $this->getRequest()->getParam("tipo"); ?>" />
    <input type="hidden" name="id_bolsa_tipo" id="id_bolsa_tipo" value="<?php echo $this->getRequest()->getParam("id_bolsa_tipo"); ?>" />
    
<div id="janela_inapto" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <input type="hidden" name="janela_inapto_id" id="janela_inapto_id" />
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Registrar Bolsista Inapto</h3>
    </div>
    <div class="modal-body">
        <div class="well well-small">
            <fieldset>
                <dl class="dl-horizontal">
                    <dt>Lote: </dt>
                    <dd><?php echo $this->lote->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Pagamento: </dt>
                    <dd id="show_pagamento"></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor: </dt>
                    <dd id="show_pagamento_valor"></dd>
                </dl>
                <div class="control-group">
                    <label for="janela_inapto_descricao" class="control-label">Motivo:</label>
                    <div class="controls">
                        <textarea name="janela_inapto_descricao" id="janela_inapto_descricao" rows="6" class="span7"></textarea>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
</div>        
    
<?php if ($status->pago()) { ?>
    <input type="hidden" name="janela_problema_id" id="janela_problema_id" />
<div id="janela_problema" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Registrar Problema de Pagamento</h3>
    </div>
    <div class="modal-body">
        <div class="well well-small">
            <fieldset>
                <dl class="dl-horizontal">
                    <dt>Lote: </dt>
                    <dd><?php echo $this->lote->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Pagamento: </dt>
                    <dd id="show_pagamento"></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor: </dt>
                    <dd id="show_pagamento_valor"></dd>
                </dl>
                <div class="control-group">
                    <label for="janela_problema_descricao" class="control-label">Descrição do Problema:</label>
                    <div class="controls">
                        <textarea name="janela_problema_descricao" id="janela_problema_descricao" rows="6" class="span7"></textarea>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
</div>    
<?php } ?>
<?php if ($this->pt->bolsista()) { ?>
<div id="janela_bolsista" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Adicionar Bolsista</h3>
    </div>
    <div class="modal-body">
        <div class="well well-small">
            <fieldset>
                <div class="control-group">
                    <label for="janela_bolsista_cpf" class="control-label">C.P.F.:</label>
                    <div class="controls">
                        <input type="text" name="janela_bolsista_cpf" id="janela_bolsista_cpf" value="" class="filtro cpf span4" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="janela_bolsista_nome" class="control-label">Nome:</label>
                    <div class="controls">
                        <input type="text" name="janela_bolsista_nome" id="janela_bolsista_nome" value="" size="60" class="filtro span7" />
                    </div>
                </div>
            </fieldset>
        </div>
        <table id="tabela_resposta" class="table table-striped table-bordered">
            <thead class="head_destino">
                <tr>
                    <th>ID</th>
                    <th>Tipo</th>
                    <th>C.P.F.</th>
                    <th>Nome</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody class="corpo_bolsista"></tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="button" value="Limpar Filtro" id="btn_limpar_filtro" class="btn" />
        <input type="button" value="Procurar" id="btn_procurar" class="btn btn-primary" />
    </div>
</div>
<?php } ?>
    <div class="well well-small">
        <dl class="dl-horizontal">
            <dt>Lote:</dt>
            <dd><?php echo $this->lote->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Tipo:</dt>
            <dd><?php echo $this->tipo; ?></dd>
        </dl>
<?php if ($this->bolsa_tipo) { ?>
        <dl class="dl-horizontal">
            <dt>Tipo de Bolsa:</dt>
            <dd><?php echo $this->bolsa_tipo; ?></dd>
        </dl>
<?php } ?>
        <dl class="dl-horizontal">
            <dt>Valor Vinculado:</dt>
            <dd><?php echo Escola_Util::number_format($this->total); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Valor Previsão:</dt>
            <dd><?php echo Escola_Util::number_format($this->previsao); ?></dd>
        </dl>
<?php if ($this->mensagem) { ?>
        <dl class="dl-horizontal">
            <dt>Mensagem:</dt>
            <dd><?php echo $this->mensagem; ?></dd>
        </dl>
<?php } ?>
    </div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Tipo</th>
                                <th>Tipo de Despesa</th>
				<th>Referência</th>
				<th>Valor</th>
				<th>Situação</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<script type="text/javascript">
    var pagamentos = [];
</script>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
            $txt_bolsa_tipo = "--";
            $bt = $registro->findParentRow("TbBolsaTipo");
            if ($bt) {
                $txt_bolsa_tipo = $bt->toString();
            }
        $action_view = array("controller" => $this->getRequest()->getControllerName(),
                             "action" => "viewloteitem",
                             "id" => $this->lote->getId(),
                             "id_vinculo_lote_item" => $registro->getId());
        $item_status = $registro->findParentRow("TbVinculoLoteItemStatus");
?>
<script type="text/javascript">
    pagamentos[<?php echo $registro->getId(); ?>] = { "id_vinculo_lote_item": <?php echo $registro->getId(); ?>, 
                                                      "referencia": "<?php echo $registro->mostrar_referencia(); ?>",
                                                      "valor": "<?php echo $registro->pega_valor()->toString(); ?>"};
</script>
			<tr>
				<td>
                    <a href="<?php echo $this->url($action_view); ?>" title="Visualizar">
					<?php echo $registro->des_tipo(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url($action_view); ?>" title="Visualizar">
					<?php echo $txt_bolsa_tipo; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url($action_view); ?>" title="Visualizar">
					<?php echo $registro->mostrar_referencia(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url($action_view); ?>" title="Visualizar">
					<?php echo $registro->pega_valor()->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url($action_view); ?>" title="Visualizar">
					<?php echo $item_status->toStringFmt(); ?>
                    </a>
				</td>
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url($action_view); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
<?php 
if ($status->aguardando_aprovacao()) {
    if (!$this->pt->bolsista()) {
?>
                        
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "loteitemeditar",
                                                             "id_vinculo_lote_item" => $registro->getId(),
															 "id" => $this->lote->getId())); ?>" class="btn" title="Editar">
							<i class="icon-cog"></i>
						</a>
<?php } else { ?>
<?php if ($item_status->inapto()) { ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "cancelarinapto",
                                                             "id_vinculo_lote_item" => $registro->getId(),
															 "id" => $this->lote->getId())); ?>" class="btn link_confirma" title="Cancelar Inapto">
							<i class="icon-check"></i>
						</a>
<?php } else { ?>
						<a href="#" id="<?php echo $registro->getId(); ?>" class="btn link_inapto" title="Lançar Inapto">
							<i class="icon-remove-circle"></i>
						</a>
<?php } ?>
<?php } ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "loteitemexcluir",
                                                             "id_vinculo_lote_item" => $registro->getId(),
															 "id" => $this->lote->getId())); ?>" class="btn link_excluir" title="Excluir">
							<i class="icon-trash"></i>
						</a>
<?php } elseif ($status->pago()) { ?>
						<a href="#" id="<?php echo $registro->getId(); ?>" class="btn link_registrar_problema" title="Registrar Problemas de Pagamento">
							<i class="icon-warning-sign"></i>
						</a>
<?php } ?>
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>