<div class="conteudo_controller">
	<div class="row-fluid">
		<div class="span12">
			<div class="well">
                <div class="page-header">
                    <h3>Ítem de Lote de Pagamento</h3>
                </div>
                <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição.:</dt>
                    <dd><?php echo $this->lote->toString(); ?></dd>
                </dl>
<?php echo $this->registro->toHTML($this); ?>
			</div>
<?php if ($this->ocorrencias) { ?>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th colspan="4">Ocorrências</th>
                    </tr>
                    <tr>
                        <th>Data</th>
                        <th>Usuário</th>
                        <th>Descrição</th>
                        <th>Pagamento</th>
                    </tr>
                </thead>
                <tbody>
<?php 
foreach ($this->ocorrencias as $ocor) {
    $usuario = $ocor->findParentRow("TbUsuario");
    $txt_pgto = "";
    $pgto = $ocor->findParentRow("TbVinculoLoteItem");
    if ($pgto) { 
        $txt_pgto = $pgto->toString();
    }
?>
                    <tr>
                        <td><?php echo Escola_Util::formatData($ocor->data); ?></td>
                        <td><?php echo $usuario->toString(); ?></td>
                        <td><?php echo $ocor->descricao; ?></td>
                        <td><?php echo $txt_pgto; ?></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
<?php } ?>
		</div>
	</div>
</div>