<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well">
                    <fieldset>
                        <legend>Cadastro de Ícone: </legend>
                <?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>ID:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
                <?php } ?>
                <?php
                    $ctrl = new Escola_Form_Element_Select_Table("id_icone_tipo");
                    $ctrl->setPkName("id_icone_tipo");
                    $ctrl->setModel("TbIconeTipo");
                    $ctrl->setValue($this->registro->id_icone_tipo);
                    $ctrl->setLabel("Tipo: ");
                    echo $ctrl->render($this);
                ?>
<?php
	$ctrl = new Escola_Form_Element_Icone("descricao");
	$ctrl->setValue($this->registro->descricao);
	echo $ctrl->render($this);
?>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>