<form action="<?php echo $this->url(array("controller" => "servidor", "action" => "editar")); ?>" method="post" id="formulario" class="formulario">
	<input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
	<fieldset>
		<legend>CADASTRO DE SERVIDOR: </legend>
<?php if ($this->registro->getId()) { ?>
		<div>
			<label>Código:</label>
			<span class="read-only"><?php echo $this->grupo->getId(); ?></span>
		</div>
<?php } ?>
<?php
$ctrl = new Escola_Form_Element_Cpf("cpf");
$ctrl->setValue($this->pf->cpf);
?>
		<div>
			<label for="<?php echo $ctrl->getId(); ?>">C.P.F.:</label><?php echo $ctrl->render($this); ?>
		</div>
		<div>
			<label for="nome">Nome:</label><input type="text" name="nome" id="nome" size="60" maxlength="60" value="<?php echo $this->pf->nome; ?>" />
		</div>
		<div>
			<label for="email">E-Mail:</label><input type="text" name="email" id="email" size="60" maxlength="60" value="<?php echo $this->pf->pega_pessoa()->email; ?>" />
		</div>
		<div>
			<label for="data_nascimento">Data de Nascimento:</label><input type="text" name="data_nascimento" id="data_nascimento" size="10" value="<?php echo $this->pf->data_nascimento; ?>" class="data" />
		</div>
		<div>
			<label for="identidade_numero">Identidade - Número:</label><input type="text" name="identidade_numero" id="identidade_numero" size="30" maxlength="30" value="<?php echo $this->pf->identidade_numero; ?>" />
		</div>
		<div>
			<label for="identidade_orgao_expedidor">Identidade - Órgão Expedidor:</label><input type="text" name="identidade_orgao_expedidor" id="identidade_orgao_expedidor" size="20" maxlength="20" value="<?php echo $this->pf->identidade_orgao_expedidor; ?>" />
		</div>
<?php
	$ctrl = new Escola_Form_Element_Select_Table("identidade_id_uf");
	$ctrl->setPkName("id_uf");
	$ctrl->setModel("TbUf");
	$ctrl->setValue($this->pf->identidade_id_uf);
	$ctrl->setLabel("Identidade - UF: ");
	echo $ctrl->render($this);
?>
	</fieldset>
</form>