<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "lotacao")); ?>" method="post" id="formulario" class="formulario">
                <input type="hidden" name="id" id="id" value="<?php echo $this->funcionario->getId(); ?>" />
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Funcionário: </dt>
                        <dd><?php echo $this->funcionario->toString(); ?></dd>
                    </dl>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Setor</th>
                            <th>Tipo</th>
                            <th>Função</th>
                            <th>Data Inicial</th>
                            <th>Data Final</th>
                            <th>Chefe</th>
                            <th colspan="5">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
                    $funcionario_funcao = "";
                    $funcionario = $registro->findParentRow("TbFuncionario");
                    $ff = $registro->findParentRow("TbFuncionarioFuncao");
                    if ($ff) {
                        $funcionario_funcao = $ff->toString();
                    }
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbSetor")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbLotacaoTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                                <?php echo $funcionario_funcao; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                                <?php echo $this->formatData($registro->data_inicial); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                                <?php echo $this->formatData($registro->data_final); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewlotacao", "id_lotacao" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarChefe(); ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "viewlotacao",
                                                                         "id_lotacao" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editarlotacao",
                                                                         "id_lotacao" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirlotacao",
                                                                         "id_lotacao" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            <?php //echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
            </form>
        </div>
    </div>
</div>