<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Lotação</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>FUNCIONÁRIO:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbFuncionario")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Setor:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbSetor")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbLotacaoTipo")->toString(); ?></dd>
                </dl>
        <?php
        $ff = $this->registro->findParentRow("TbFuncionarioFuncao");
        if ($ff) {
        ?>
                <dl class="dl-horizontal">
                    <dt>Função:</dt>
                    <dd><?php echo $ff->toString(); ?></dd>
                </dl>
        <?php } ?>
                <dl class="dl-horizontal">
                    <dt>Data Inicial:</dt>
                    <dd><?php echo $this->formatData($this->registro->data_inicial); ?></dd>
                </dl>
        <?php if ($this->formatData($this->registro->data_final)) { ?>
                <dl class="dl-horizontal">
                    <dt>Data Final:</dt>
                    <dd><?php echo $this->formatData($this->registro->data_final); ?></dd>
                </dl>
        <?php } ?>
                <dl class="dl-horizontal">
                    <dt>Chefe:</dt>
                    <dd><?php echo $this->registro->mostrarChefe(); ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>