<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Servidor - Ocorrência</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>FUNCIONÁRIO:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbFuncionario")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbFuncionarioOcorrenciaTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Data Inicial:</dt>
                    <dd><?php echo $this->formatData($this->registro->data_inicio); ?></dd>
                </dl>
        <?php if ($this->formatData($this->registro->data_final)) { ?>
                <dl class="dl-horizontal">
                    <dt>Data Final:</dt>
                    <dd><?php echo $this->formatData($this->registro->data_final); ?></dd>
                </dl>
        <?php } ?>
                <dl class="dl-horizontal">
                    <dt>Observações:</dt>
                    <dd><?php echo $this->registro->observacoes; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>