<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "atendimento")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well">
                    <fieldset>
                        <legend>ADICIONAR ATENDIMENTO: </legend>
                <?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>Chamado:</dt>
                            <dd><?php echo $this->registro->toString(); ?></dd>
                        </dl>
                <?php } ?>
                        <div class="control-group">
                            <label for="observacoes" class="control-label">Serviço Executado:</label>
                            <div class="controls">
                                <textarea name="observacoes" id="observacoes" rows="6" class="span5"></textarea>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>