<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Chamado</h4>
                </div>
                    <dl class="dl-horizontal">
                        <dt>ID:</dt>
                        <dd><?php echo $this->registro->getId(); ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Tipo:</dt>
                        <dd><?php echo $this->registro->findParentRow("TbChamadoTipo")->descricao; ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Data / Hora:</dt>
                        <dd><?php echo Escola_Util::formatData($this->registro->data_criacao); ?> <?php echo $this->registro->hora_criacao; ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Criado Por:</dt>
                        <dd><?php echo $this->registro->findParentRow("TbFuncionario")->toString(); ?> - <?php echo $this->registro->findParentRow("TbSetor")->toString(); ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Descrição do Problema:</dt>
                        <dd><?php echo $this->registro->descricao_problema; ?></dd>
                    </dl>
            <?php if ($this->registro->finalizado() && $this->registro->nota) { ?>
                    <dl class="dl-horizontal">
                        <dt>Nota do Atendimento:</dt>
                        <dd><?php echo $this->registro->nota; ?></dd>
                    </dl>
            <?php } ?>
                    <dl class="dl-horizontal">
                        <dt>Situação:</dt>
                        <dd><?php echo $this->registro->findParentRow("TbChamadoStatus")->toString(); ?></dd>
                    </dl>
                </div>
            <?php
            $movs = $this->registro->pegaOcorrencia();
            if ($movs) {
            ?>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th colspan="7">
                                Ocorrências
                            </th>
                        </tr>
                        <tr>
                            <th>Data / Hora</th>
                            <th>Tipo</th>
                            <th>Setor</th>
                            <th>Funcionário</th>
                            <th>Observações</th>
                        </tr>
                    </thead>
                    <tbody>
            <?php foreach ($movs as $mov) { ?>
                        <tr>
                            <td><div align="center"><?php echo Escola_Util::formatData($mov->data_ocorrencia); ?> - <?php echo $mov->hora_ocorrencia; ?></div></td>
                            <td><div align="center"><?php echo $mov->findParentRow("TbChamadoOcorrenciaTipo")->toString(); ?></div></td>
                            <td><div align="left"><?php echo $mov->findParentRow("TbSetor")->toString(); ?></div></td>
                            <td><div align="left"><?php echo $mov->findParentRow("TbFuncionario")->toString(); ?></div></td>
                            <td><div align="left"><?php echo $mov->observacoes; ?></div></td>
                        </tr>
            <?php } ?>
                    </tbody>
                </table>
            <?php } ?>
        </div>
    </div>
</div>