<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
<?php if ($this->ib->getId()) { ?>
                <input type="hidden" name="id_info_bancaria" id="id_info_bancaria" value="<?php echo $this->ib->getId(); ?>" />
<?php } ?>
                <div class="well">
                    <fieldset>
                        <legend>CADASTRO DE CONVÊNIO BANCÁRIO: </legend>
                <?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>Código:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
                <?php } ?>
                        <div class="control-group">
                            <label for="descricao" class="control-label">Descrição:</label>
                            <div class="controls">
                                <input type="text" name="descricao" id="descricao" maxlength="60" value="<?php echo $this->registro->descricao; ?>" class="span5" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="convenio" class="control-label">Convênio:</label>
                            <div class="controls">
                                <input type="text" name="convenio" id="convenio" maxlength="60" value="<?php echo $this->registro->convenio; ?>" class="span3" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="contrato" class="control-label">Contrato:</label>
                            <div class="controls">
                                <input type="text" name="contrato" id="contrato" maxlength="60" value="<?php echo $this->registro->contrato; ?>" class="span3" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="padrao" class="control-label">Padrão?</label>
                            <div class="controls">
                                <select name="padrao" id="padrao">
                                    <option value="S" <?php echo ($this->registro->padrao())?"selected":""; ?>>SIM</option>
                                    <option value="N" <?php echo (!$this->registro->padrao())?"selected":""; ?>>NÃO</option>
                                </select>
                            </div>
                        </div>
                   </fieldset>
                </div>
                <div class="well well-small">
<?php echo $this->ib->render($this); ?>
                </div>
            </form>
        </div>
    </div>
</div>