<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <div class="well well-small" id="idPesquisa">
                    <fieldset>
                        <legend>Opções de Pesquisa</legend>
            <?php
            $tb = new TbDocumentoTipoTarget();
            $dtt = $tb->getPorChave("A");
            $tb = new TbDocumentoTipo();
            $dts = $tb->listar(array("filtro_id_documento_tipo_target" => $dtt->getId()));
            if ($dts && count($dts)) {
            ?>
                        <div class="control-group">
                            <label for="filtro_id_documento_tipo" class="control-label">Tipo</label>
                            <div class="controls">
                                <select name="filtro_id_documento_tipo" id="filtro_id_documento_tipo" class="filtro">
                                                        <option value="" <?php echo (!$this->dados["filtro_id_documento_tipo"])?"selected":""; ?>>==> SELECIONE <==</option>
            <?php foreach ($dts as $dt) { ?>
                                                        <option value="<?php echo $dt->getId(); ?>"  <?php echo ($this->dados["filtro_id_documento_tipo"] == $dt->getId())?"selected":""; ?>><?php echo $dt->toString(); ?></option>
            <?php } ?>
                                </select>
                            </div>
                        </div>
<?php } ?>
                        <div class="control-group">
                            <label for="filtro_numero" class="control-label">Número:</label>
                            <div class="controls">
                                <input type="text" class="filtro span2" name="filtro_numero" id="filtro_numero" value="<?php echo $this->dados["filtro_id_documento_tipo"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_ano" class="control-label">Ano:</label>
                            <div class="controls">
                                <input type="text" class="filtro span1" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="filtro_ano" class="control-label">Resumo:</label>
                            <div class="controls">
                                <textarea name="filtro_resumo" id="filtro_resumo" rows="6" class="filtro span5"><?php echo $this->dados["filtro_resumo"]; ?></textarea>
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <input type="submit" value="Pesquisar" class="btn btn-primary" />
                                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />                                
                            </div>
                        </div>
                    </fieldset>
                </div>

                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Data / Hora Criação</th>
                            <th>Tipo</th>
                            <th>Número</th>
                            <th>Resumo</th>
                            <th>Arquivo</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php
                foreach ($this->registros as $registro) {
                    $registro = TbDocumento::pegaPorId($registro["id_documento"]);
                    $arquivo = $registro->pega_arquivo();
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data_criacao); ?> - <?php echo $registro->hora_criacao; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbDocumentoTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarNumero(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->resumo; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo ($arquivo)?$arquivo->miniatura(array("width" => 50, "link" => true)):""; ?>
                                </a>
                            </td>
                            <td width="20px">
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                 "action" => "editar",
                                                 "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "funcionario",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Funcionários">
                                        <i class="icon-group"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            </form>
<?php if ($this->registros && count($this->registros)) { ?>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
<?php } ?>
        </div>
    </div>
</div>