<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Cadastro de Documento Administrativo</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbDocumentoTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Número:</dt>
                    <dd><?php echo $this->registro->mostrarNumero(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Resumo:</dt>
                    <dd><?php echo $this->registro->resumo; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>