<div class="conteudo_controller">
	<div class="row-fluid">
		<div class="span12">
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Descrição</th>
				<th>Grupo Inferior</th>
				<th>Padrão</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->grupos) { ?>
		<tbody>
<?php 
	foreach ($this->grupos as $registro) { 
		$inferior = "";
		$m_inferior = $registro->findParentRow("TbGrupo");
		if (count($m_inferior)) {
			$inferior = $m_inferior->descricao;
		}
?>
			<tr>
				<td>
					<?php echo $registro->descricao; ?>
				</td>
				<td>
					<?php echo $inferior; ?>
				</td>
				<td>
					<?php echo $registro->mostrarPadrao(); ?>
				</td>
				<td width="20px">
					<div class="btn-group">	
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "editar",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Alterar">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluir",
															 "id" => $registro->getId())); ?>" class="btn btn-primary link_excluir" id="ExcluirGrupo" data-toggle="tooltip" title="Excluir">
							<i class="icon-trash"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "permissoes",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Permissões">
							<i class="icon-key"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "usuarios",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Usuários">
							<i class="icon-group"></i>
						</a>
					</div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
		</div>
	</div>
</div>
<?php echo $this->paginationControl($this->grupos, "sliding", "minha_paginacao_control.phtml"); ?>