<!-- janela adicionar usuário -->
<div id="janela_usuario" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <input type="hidden" name="jan_pagina" id="jan_pagina" />
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Adicionar Usuários</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
        <div class="well well-small">
            <form action="" method="post" id="form_usuario" class="form-horizontal">
                <fieldset>
                    <legend>Filtro de Busca</legend>
                    <div class="control-group">
                        <label for="filtro_nome" class="control-label">Nome: </label>
                        <div class="controls">
                            <input type="text" name="filtro_nome" id="filtro_nome" class="span7"  />
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <input type="submit" value="Procurar" class="btn btn-primary" />
                            <input type="button" value="Limpar Consulta" id="bt_limpar" class="btn" />
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
            </div>
        <table class="table table-striped table-bordered" id="table_usuario">
            <thead>
                <tr>
                    <th>Usuário</th>
                    <th>Situação</th>
                    <th width="20px"></th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
    </div>
</div>

<div class="conteudo_controller">
            <form action="<?php echo $this->url(array("controller" => "grupo", "action" => "usuarios")); ?>" method="post" id="formulario" class="formulario">
                <input type="hidden" name="id" id="id" value="<?php echo $this->grupo->getId(); ?>" />
    <div class="row-fluid">
        <div class="span12">
                <div class="well">
                    <dl class="dl-horizontal">
                        <dt>Grupo:</dt>
                        <dd><?php echo $this->grupo->toString(); ?></dd>
                    </dl>
                </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="span3">C.P.F.</th>
                            <th>Nome do Usuário</th>
                            <th width="40px">Operações</th>
                        </tr>
                    </thead>
<?php if ($this->usuarios) { ?>
                    <tbody>
<?php 
foreach ($this->usuarios as $dado) { 
    $usuario = TbUsuario::pegaPorId($dado["id_usuario"]);
    $pf = $usuario->pega_pessoa_fisica();
?>
                    <tr>
                        <td><?php echo Escola_Util::formatCpf($pf->cpf); ?></td>
                        <td><?php echo $pf->nome; ?></td>
                        <td>
                            <div class="text-center">
                                <div class="btn-group">
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "usuarioexcluir", "id" => $this->grupo->getId(), "id_usuario" => $usuario->getId())); ?>" class="btn btn-danger link_excluir" data-toggle="tooltip" title="Excluir"><i class="icon-trash"></i></a>
                                </div>
                            </div>
                        </td>
                    </tr>
<?php } ?>
                    </tbody>
<?php } ?>
                </table>
        </div>
    </div>
            </form>
</div>
<?php echo $this->paginationControl($this->usuarios, "sliding", "minha_paginacao_control.phtml"); ?>