<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well">
                    <fieldset>
                        <legend>CADASTRO DE FUNÇÃO GRATIFICADA: </legend>
                <?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>Código:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
                <?php } ?>
                        <div class="control-group">
                            <label for="descricao" class="control-label">Código:</label>
                            <div class="controls">
                                <input type="text" name="codigo" id="codigo" maxlength="10" value="<?php echo $this->registro->codigo; ?>" class="span2" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="descricao" class="control-label">Descrição:</label>
                            <div class="controls">
                                <input type="text" name="descricao" id="descricao" maxlength="60" value="<?php echo $this->registro->descricao; ?>" class="span5" />
                            </div>
                        </div>
                <?php
                    $ctrl = new Escola_Form_Element_Select_Table("id_funcionario_funcao_tipo");
                    $ctrl->setPkName("id_funcionario_funcao_tipo");
                    $ctrl->setModel("TbFuncionarioFuncaoTipo");
                    $ctrl->setValue($this->registro->id_funcionario_funcao_tipo);
                    $ctrl->setLabel("Tipo: ");
                    echo $ctrl->render($this);
                ?>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>