<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Tipo</th>
                        <th>Funcionário Vinculado</th>
                        <th width="20px">Operações</th>
                    </tr>
                </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
                <tbody>
        <?php 
            foreach ($this->registros as $registro) {
                $func = "";
                $funcionario = $registro->pegaFuncionario();
                if ($funcionario) {
                    $func = $funcionario->toString();
                }
        ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->codigo; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->descricao; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbFuncionarioFuncaoTipo")->toString(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $func; ?>
                            </a>
                        </td>
                        <td>
                            <div class="btn-group">	
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "view",
                                                                     "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                    <i class="icon-search"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "editar",
                                                                     "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                    <i class="icon-cog"></i>
                                </a>
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "excluir",
                                                                     "id" => $registro->getId())); ?>" class="btn btn-primary link_excluir" title="Excluir">
                                    <i class="icon-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
        <?php } ?>
                </tbody>
        <?php } ?>
            </table>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>