<style>
    .operacoes {
        text-align: center !important;
    }

    .div_btn_adicionar {
        margin-bottom: 10px;
    }

    .div_btn_adicionar button {
        height: 40px;
        width: 200px;
    }
</style>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editar")); ?>" method="post" id="formulario" class="formulario form-horizontal">

                    <input type="hidden" name="id" id="id" value="" class="cadastro-item" />

                    <fieldset>
                        <legend>REQUERIMENTO: </legend>

                        <legend class="cadastro">SOLICITANTE: </legend>
                        <dl class="dl-horizontal cadastro">
                            <dt>C.P.F.:</dt>
                            <dd id="req-show-cpf"></dd>
                        </dl>
                        <dl class="dl-horizontal cadastro">
                            <dt>Nome:</dt>
                            <dd id="req-show-nome"></dd>
                        </dl>

                    </fieldset>

                    <legend class="cadastro">REQUERIMENTO: </legend>

                    <div class="div_btn_adicionar"><button class="btn" id="btn-adicionar">Adicionar Serviço</button></div>

                    <div class="row-fluid">
                        <div class="span12">
                            <table class="table table-striped table-bordered" id="tabela-itens">
                                <thead>
                                    <tr>
                                        <th>Serviços Adicionados</th>
                                        <th width="20px" class="operacoes">Operações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

<!-- janela modal início -->
<div id="modalServico" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Adicionar Serviços</h3>
    </div>

    <div class="modal-body">

        <div id="erro-salvar"></div>

        <div class="row-fluid" id="servico-selecao">
            <div class="input-append span12">
                <input id="servico-procurar" type="text" class="span10" placeholder="Digite um serviço para localizar ou adicionar.">
                <button id="btn-servico-adicionar" class="btn" type="button" style="display: none;">Adicionar</button>
            </div>

            <ul id="ul-servico">

            </ul>
        </div>

        <div class="row-fluid" id="servico-confirmacao">
            <div class="span12">Serviço: <span id="servico-show"></span></div>
            <textarea id="servico-obs" placeholder="Observações." rows="6" class="span12"></textarea>
        </div>

    </div>

    <div class="modal-footer">
        <button id="btn-fechar" class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <button id="btn-cancelar" class="btn btn-final">Cancelar</button>
        <button id="btn-salvar" class="btn btn-primary btn-final">Salvar</button>
    </div>

</div>
<!-- janela modal fim -->

<script>
    let servicos = null;
    let servicoSelecionado = null;

    async function requerimento_init() {
        const pessoa = _.get(dados, "pessoa");
        $("#req-show-cpf").text(formataCPF(_.get(pessoa, "cpf")));
        $("#req-show-nome").text(_.get(pessoa, "nome"));
        $("#link_cancelar, #link_salvar").show();
        listaServicos();
    }

    async function salvarFormRequerimento() {
        limpaAlerta();
        try {

            if (!(dados.servicos && dados.servicos.length)) {
                throw new Error("Adicione pelo penos um serviço ao requerimento.");
            }

            dados.requerimento = registro;
            const result = await salvarRequerimento(dados);

            if (result.erro) {
                throw new Error(result.erro);
            }

            if (!(result && result.requerimento && result.requerimento.id)) {
                throw new Error("Ocorreu uma falha ao tentar salvar o requerimento. Informe o administrador.");
            }

            $.mensagemAlerta({
                tipo: "sucesso",
                mensagem: "Requerimento cadastrado com sucesso."
            });

            window.location.href = "<?php echo $this->url(array("controller" => "requerimento", "action" => "view")); ?>/id/" + result.requerimento.id;

        } catch (error) {
            $.mensagemAlerta({
                mensagem: errorMessage(error)
            });
        }
    }

    function requerimentoCancelar() {
        setOperacao("pessoa", false);
    }

    function listaServicos() {
        limpaAlerta();
        const servicos = _.get(dados, "servicos") || [];

        const tbody = $("#tabela-itens tbody");

        tbody.children().remove();

        if (!(servicos && servicos.length)) {
            const tr = $("<tr>");

            $("<td>", {
                "colspan": 2,
                "text": "Nenhum registro adicionado"
            }).appendTo(tr);

            tr.appendTo(tbody);

            return;
        }

        for (const servico of servicos) {

            let txt_td = servico.descricao;
            if (servico.obs) {
                txt_td += " <div class='small muted'>" + servico.obs + "</div>";
            }

            const tr = $("<tr>");
            $("<td>", {
                html: txt_td
            }).appendTo(tr);

            const td = $("<td>", {
                width: "20px",
                class: "operacoes"
            }).appendTo(tr);

            const div = $("<div>", {
                class: "btn-group"
            }).appendTo(td);

            const a = $("<a>", {
                href: "#",
                class: "btn",
                title: "Excluir",
                click: function(ev) {
                    ev.preventDefault();
                    dados.servicos = dados.servicos.filter(function(serv) {
                        if (servico.id) {
                            return serv.id !== servico.id;
                        }
                        return serv.descricao.toLowerCase() !== servico.descricao.toLowerCase();
                    });
                    listaServicos();
                }
            }).appendTo(div);

            const img = $("<i>", {
                class: "icon-trash",
            }).appendTo(a);

            tr.appendTo(tbody);
        }
    }

    function salvarRequerimento(dados) {
        return new Promise(function(resolve, reject) {
            var ajax_obj = $.ajax({
                "url": "<?php echo Escola_Util::getBaseUrl(); ?>/requerimento/salvar/format/json/",
                "type": "POST",
                "data": {
                    ...dados
                },
                "success": function(result) {
                    if (result.erro && result.erro.length) {
                        return reject(result.erro);
                    }

                    if (!result.result) {
                        return resolve(null);
                    }

                    return resolve(result.result);
                }
            });

        });
    }

    function carregarServicos() {
        return new Promise(function(resolve, reject) {
            var ajax_obj = $.ajax({
                "url": "<?php echo Escola_Util::getBaseUrl(); ?>/servico/listar/format/json/",
                "type": "POST",
                "success": function(result) {
                    if (result.erro && result.erro.length) {
                        return reject(result.erro);
                    }

                    if (!result.result) {
                        return resolve(null);
                    }

                    return resolve(result.result);
                }
            });

        });
    }

    function selecionaServico(servico) {
        if (!servico) {
            return;
        }

        if (typeof servico === 'string') {
            servicoSelecionado = {
                descricao: servico.toUpperCase()
            }
        } else if (servico && servico.descricao) {
            servicoSelecionado = servico;
        }

        $("#servico-show").text(servicoSelecionado.descricao);
        $("#servico-selecao, #btn-fechar").hide();
        $("#servico-confirmacao, .btn-final").show();
        $("#servico-obs").val('').focus().select();
    }

    function atualizaServicos() {
        erroSalvar();
        $("#btn-servico-adicionar").hide();
        $("#servico-procurar").removeClass("span10").addClass("span12");

        if (!(servicos && servicos.length)) {
            return;
        }

        const servico_nome = $("#servico-procurar").val().toLowerCase();

        const filtrados = servicos.filter(function(servico) {

            if (dados.servicos && dados.servicos.length) {
                const existe = dados.servicos.some(function(s) {
                    if (!s.id) {
                        return false;
                    }
                    return s.id === servico.id;
                });

                if (existe) {
                    return false;
                }
            }

            if (!(servico_nome && servico_nome.length)) {
                return true;
            }

            if (!(servico && servico.descricao)) {
                return false;
            }

            return servico.descricao.toLowerCase().includes(servico_nome);
        });

        const ul = $("#ul-servico");

        ul.children().remove();

        if (!(filtrados && filtrados.length)) {
            $("#servico-procurar").removeClass("span12").addClass("span10");
            $("#btn-servico-adicionar").show();
        }

        for (const servico of filtrados) {
            const li = $("<li>").appendTo(ul);
            $("<a>", {
                href: "#",
                text: servico.descricao,
                click: function(event) {
                    event.preventDefault();
                    selecionaServico(servico);
                }
            }).appendTo(li);
        }

    }

    function modalServicoCancelar() {
        $("#servico-confirmacao, .btn-final").hide();
        $("#servico-selecao, #btn-fechar").show();
        $("#servico-procurar").val('');

        servicoSelecionado = null;
        atualizaServicos();
    }

    function erroSalvar(erro) {
        $("#erro-salvar").children().remove();
        if (!erro) {
            return;
        }
        $('<div class="alert alert-error" id="servico-erro-salvar">' + erro + '</div>').appendTo($("#erro-salvar"));
    }

    $(document).ready(function() {

        $("#btn-adicionar").click(async function(event) {
            event.preventDefault();
            limpaAlerta();

            if (!(servicos && servicos.length)) {
                servicos = await carregarServicos();
            }

            modalServicoCancelar();

            $("#modalServico").modal("show");
            $("#modalServico").on("shown", function() {
                $("#servico-procurar").focus().select();
            });

        });

        $("#modalServico").css({
            // "width": "900px",
            // "margin-left": "-450px"
        });

        $("#servico-procurar").keyup(function() {
            atualizaServicos();
        });

        $("#btn-servico-adicionar").click(function() {
            selecionaServico($("#servico-procurar").val());
        });

        $("#btn-cancelar").click(function() {
            modalServicoCancelar();
        });

        $("#btn-salvar").click(function() {
            limpaAlerta();
            erroSalvar();
            if (!dados.servicos) {
                dados.servicos = [];
            }

            if (dados.servicos.length) {
                const existe = dados.servicos.some(function(s) {
                    if (servicoSelecionado.id) {
                        return s.id === servicoSelecionado.id
                    }
                    return servicoSelecionado.descricao.toLowerCase() === s.descricao.toLowerCase();
                });
                if (existe) {
                    erroSalvar("Falha, ítem já adicionado.");
                    return;
                }
            }

            servicoSelecionado.obs = $("#servico-obs").val();
            dados.servicos.push(servicoSelecionado);
            $("#modalServico").modal("hide");

            listaServicos();
        });

    })
</script>