<?php
$sits = [
    '',
    Requerimento::$SITUACAO_PENDENTE,
    Requerimento::$SITUACAO_DEFERIDO,
    Requerimento::$SITUACAO_DEFERIDO_PARCIALMENTE,
    Requerimento::$SITUACAO_INDEFERIDO,
];
?>
<style>
    #carregando,
    .cadastro,
    .busca {
        display: none;
    }
</style>
<div class="conteudo_controller">
    <div class="row-fluid" id="idPesquisa" style="display:none;">
        <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="get" id="form-pesquisa" class="formulario form-horizontal">
            <div class="well well-small">
                <div class="page-header">
                    <h4>Opções de Pesquisa</h4>
                </div>

                <div class="control-group">
                    <label for="filtro_numero" class="control-label">Número / Ano:</label>
                    <div class="controls">
                        <input placeholder="Número" type="text" name="filtro_numero" id="filtro_numero" value="<?php echo $this->dados["filtro_numero"]; ?>" class="span1 filtro" /> /
                        <input placeholder="Ano" type="text" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" class="span1 filtro" />
                    </div>
                </div>

                <div class="control-group">
                    <label for="filtro_descricao" class="control-label">CPF, CNPJ ou Nome:</label>
                    <div class="controls">
                        <input placeholder="C.P.F., C.N.P.J. ou Nome" type="text" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" class="span5 filtro" />
                    </div>
                </div>

                <div class="control-group">
                    <label for="filtro_data_criacao_inicio" class="control-label">Criação entre:</label>
                    <div class="controls">
                        <input placeholder="Data início" type="text" name="filtro_data_criacao_inicio" id="filtro_data_criacao_inicio" value="<?php echo $this->dados["filtro_data_criacao_inicio"]; ?>" class="span2 filtro data" /> e
                        <input placeholder="Data final" type="text" name="filtro_data_criacao_fim" id="filtro_data_criacao_fim" value="<?php echo $this->dados["filtro_data_criacao_fim"]; ?>" class="span2 filtro data" />
                    </div>
                </div>

                <div class="control-group">
                    <label for="filtro_situacao" class="control-label">Situação:</label>
                    <div class="controls">
                        <select name="filtro_situacao" id="filtro_situacao" class="span3 filtro">
                            <? foreach ($sits as $sit): ?>
                            <option <?php if ($this->dados["filtro_situacao"] == $sit) : ?>selected<?php endif; ?> value="<?= $sit ?>"><?= $sit ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                        <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Número</th>
                        <th>Solicitante</th>
                        <th>Data Solicitação</th>
                        <th>Situação</th>
                        <th width="20px">Operações</th>
                    </tr>
                </thead>
                <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
                        <?php
                        foreach ($this->registros as $registro) {
                            $registro = (object) $registro->toView();
                        ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->id)); ?>">
                                        <?php echo $registro->numero; ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->id)); ?>">
                                        <?php echo $registro->pessoa; ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->id)); ?>">
                                        <?php echo $registro->data_criacao; ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->id)); ?>">
                                        <?php echo $registro->situacao; ?>
                                    </a>
                                </td>
                                <td width="20px">
                                    <div class="btn-group">
                                        <a href="<?php echo $this->url(array(
                                                        "controller" => $this->getRequest()->getControllerName(),
                                                        "action" => "view",
                                                        "id" => $registro->id
                                                    )); ?>" class="btn" title="Visualizar" data-toogle="tooltip">
                                            <i class="icon-search"></i>
                                        </a>
                                        <a href="<?php echo $this->url(array(
                                                        "controller" => $this->getRequest()->getControllerName(),
                                                        "action" => "editar",
                                                        "id" => $registro->id
                                                    )); ?>" class="btn" title="Editar" data-toogle="tooltip">
                                            <i class="icon-cog"></i>
                                        </a>
                                        <a href="<?php echo $this->url(array(
                                                        "controller" => $this->getRequest()->getControllerName(),
                                                        "action" => "excluir",
                                                        "id" => $registro->id
                                                    )); ?>" class="btn link_excluir" title="Excluir" data-toogle="tooltip">
                                            <i class="icon-trash"></i>
                                        </a>
                                        <a href="<?php echo $this->url(array(
                                                        "controller" => $this->getRequest()->getControllerName(),
                                                        "action" => "analise",
                                                        "id" => $registro->id
                                                    )); ?>" class="btn" title="Analisar" data-toogle="tooltip">
                                            <i class="icon-edit"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                <?php } ?>
            </table>
            <?php
            if ($this->registros) {
                echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
            }
            ?>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#idLimparPesquisa").click(function(event) {
            $(".filtro").val('');
            $("#form-pesquisa").submit();
        })
    });
</script>