<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario">
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Informação:</dt>
                        <dd><?php echo $this->info->toString(); ?></dd>
                    </dl>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Envio</th>
                            <th>Tipo</th>
                            <th>Legenda</th>
                            <th>Tamanho</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) {
                    $arquivo = $registro->pegaObjeto();
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewanexo", "id_info_ref" => $registro->getId())); ?>">
                                <?php echo Escola_Util::formatData($arquivo->data_upload); ?> <?php echo $arquivo->hora_upload; ?>
                                </a>
                            </td>				
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewanexo", "id_info_ref" => $registro->getId())); ?>">
                                    <?php echo $arquivo->miniatura(50, "left"); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewanexo", "id_info_ref" => $registro->getId())); ?>">
                                <?php echo $arquivo->legenda; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "viewanexo", "id_info_ref" => $registro->getId())); ?>">
                                <?php echo $arquivo->tamanho; ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "viewanexo",
                                                                         "id_info_ref" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editaranexo",
                                                                         "id_info_ref" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluiranexo",
                                                                         "id_info_ref" => $registro->getId())); ?>" class="btn link_excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            </form>
        </div>
    </div>
</div>