<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "editaranexo")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?php echo $this->info->getId(); ?>" />
                <input type="hidden" name="id_info_ref" id="id_info_ref" value="<?php echo $this->registro->getId(); ?>" />
                <div class="well">
                    <fieldset class="fieldset">
                        <legend>ALTERANDO ANEXO: </legend>
                        <dl class="dl-horizontal">
                            <dt>Informação:</dt>
                            <dd><?php echo $this->info->toString(); ?></dd>
                        </dl>
                        <div class="control-group">
                            <label for="legenda" class="control-label">Legenda:</label>
                            <div class="controls">
                                <input type="text" name="legenda" id="legenda" size="50" maxlength="50" value="<?php echo $this->arquivo->legenda; ?>" class="span5" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="arquivo" class="control-label">Arquivo:</label>
                            <div class="controls">
                                <input type="file" name="arquivo" id="arquivo" class="span5" />
                            </div>
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>