<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
            <div class="well well-small" id="idPesquisa">
                <fieldset>
                    <legend>Opções de Pesquisa</legend>
            <?php
            $ctrl = new Escola_Form_Element_Select_Table("filtro_id_info_tipo");
            $ctrl->setModel("TbInfoTipo");
            $ctrl->setPkName("id_info_tipo");
            $ctrl->setValue($this->dados["filtro_id_info_tipo"]);
            $ctrl->setAttrib("class", "filtro");
            $ctrl->setLabel("Tipo: ");
            echo $ctrl->render($this);
            ?>        
                    <div class="control-group">
                        <label for="filtro_titulo" class="control-label">Título:</label>
                        <div class="controls">
                            <input type="text" class="filtro span5" name="filtro_titulo" id="filtro_titulo" value="<?php echo $this->dados["filtro_titulo"]; ?>" />
                        </div>
                    </div>
            <?php
            $ctrl = new Escola_Form_Element_Select_Table("filtro_id_info_status");
            $ctrl->setModel("TbInfoStatus");
            $ctrl->setPkName("id_info_status");
            $ctrl->setValue($this->dados["filtro_id_info_status"]);
            $ctrl->setAttrib("class", "filtro");
            $ctrl->setLabel("Status:");
            echo $ctrl->render($this);
            ?>  
                    <div class="control-group">
                        <div class="controls">
                            <input type="submit" value="Pesquisar" class="btn btn-primary" />
                            <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />                
                        </div>
                    </div>
                </fieldset>
            </div>                
            <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Data Cadastro</th>
                            <th>Tipo</th>
                            <th>Título</th>
                            <th>Autor</th>
                            <th>Destaque</th>
                            <th>Comentários</th>
                            <th>Status</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) { 
            ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo Escola_Util::formatData($registro->data); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->findParentRow("TbInfoTipo")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                    <?php echo $registro->titulo; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->autor; ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarDestaque(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->mostrarComentario(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url(array("action" => "view", "id" => $registro->getId())); ?>">
                                <?php echo $registro->findParentRow("TbInfoStatus")->toString(); ?>
                                </a>
                            </td>
                            <td>
                                <div class="btn-group">	
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "view",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                        <i class="icon-search"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editar",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Editar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluir",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "anexo",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Anexos">
                                        <i class="icon-paper-clip"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "referencia",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Referências">
                                        <i class="icon-random"></i>
                                    </a>
                                </div>
                            </td>				
                        </tr>
            <?php } ?>
                    </tbody>
            <?php } ?>
                </table>
            <?php
            if ($this->registros) { 
                echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml");
            }
            ?>
            </form>
        </div>
    </div>
</div>