<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal">
                <input type="hidden" name="operacao" id="operacao" />
                <input type="hidden" name="jan_id_info" id="jan_id_info" />
                <div id="janela_add" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel">Adicionar Informação</h3>
                    </div>
                    <div class="modal-body">
                        <div class="well well-small">
<?php
$ctrl = new Escola_Form_Element_Select_Table("jan_filtro_id_info_tipo");
$ctrl->setModel("TbInfoTipo");
$ctrl->setPkName("id_info_tipo");
$ctrl->setLabel("Tipo:");
echo $ctrl->render($this);
?>                            
                            <div class="control-group">
                                <label for="filtro_titulo" class="control-label">Título:</label>
                                <div class="controls">
                                    <input type="text" name="filtro_titulo" id="filtro_titulo" size="50" class="span6" />
                                </div>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered" id="tabela_lista">
                            <thead>
                                <tr>
                                    <th>Data</th>
                                    <th>Tipo</th>
                                    <th>Título</th>
                                </tr>
                            </thead>
                        </table>                        
                    </div>
                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                        <input type="button" value="Limpar Filtro" id="jan_filtro_limpar" class="btn" />
                        <input type="submit" value="Procurar" class="btn btn-primary" />
                    </div>
                </div>
                <div class="well well-small">
                    <dl class="dl-horizontal">
                        <dt>Informação:</dt>
                        <dd><?php echo $this->info->toString(); ?></dd>
                    </dl>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Tipo</th>
                            <th>Título</th>
                            <th width="20px">Operações</th>
                        </tr>
                    </thead>
            <?php if ($this->registros && count($this->registros)) { ?>
                    <tbody>
            <?php 
                foreach ($this->registros as $registro) {
                    $info = $registro->pegaObjeto();
                    if ($info) {
            ?>
                        <tr>
                            <td>
                                <?php echo Escola_Util::formatData($info->data); ?>
                            </td>				
                            <td>
                                <?php echo $info->findParentRow("TbInfoTipo")->toString(); ?>
                            </td>
                            <td>
                                <?php echo $info->titulo; ?>
                            </td>
                            <td width="20px">
                                <div align="center">
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluirreferencia",
                                                                         "id_info_ref" => $registro->getId())); ?>" class="btn btn-primary link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                <?php }} ?>
                    </tbody>
            <?php } ?>
                </table>
            </form>
        </div>
    </div>
</div>