<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->arquivo->miniatura(array("width" => 90, "align" => "right", "link" => true)); ?>
            <div class="well">
                <div class="page-header">
                    <h4>Anexo</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Código:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Informação:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbInfo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Envio:</dt>
                    <dd><?php echo Escola_Util::formatData($this->arquivo->data_upload); ?> <?php echo $this->arquivo->hora_upload; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->arquivo->findParentRow("TbArquivoTipo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Legenda:</dt>
                    <dd><?php echo $this->arquivo->legenda; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tamanho:</dt>
                    <dd><?php echo $this->arquivo->tamanho; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>