<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <div class="well well-small">
        <dl class="dl-horizontal">
            <dt>Vínculo:</dt>
            <dd><?php echo $this->vinculo->toString(); ?></dd>
        </dl>
                        <dl class="dl-horizontal">
                            <dt>Data Vigência:</dt>
                            <dd><?php echo $this->vinculo->mostrar_data_final(); ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Valor Contrato:</dt>
                            <dd><?php echo $this->vinculo->mostrar_saldo(); ?></dd>
                        </dl>
    </div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
                            <th>Tipo</th>
				<th>Número</th>
				<th>Data</th>
				<th>Data Alterada</th>
                                <th>Valor Alterado</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
            $url_view = $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "viewaditivo", "id" => $registro->getId()));
            $txt_tipo = $txt_data = $txt_numero = $txt_data_alterada = $txt_valor_alterado = "--";
            $at = $registro->findParentRow("TbAditivoTipo");
            if ($at) {
                $txt_tipo = $at->toString();
            }
            $txt_numero = $registro->mostrar_numero();
            $txt_data = Escola_Util::formatData($registro->data);
            $at = $registro->findParentRow("TbAditivoTipo");
            if ($at) {
                if ($at->data()) {
                    $txt_data_alterada = Escola_Util::formatData($registro->data_aditivo);
                } elseif ($at->valor()) {
                    $valor = $registro->pega_valor();
                    if ($valor) {
                        $txt_valor_alterado = $valor->toString();
                    }
                }
            }
?>
			<tr>
                            <td>
                                <a href="<?php echo $url_view; ?>" title="Visualizar">
                                    <?php echo $txt_tipo; ?>
                                </a>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $url_view; ?>" title="Visualizar">
                                            <?php echo $txt_numero; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $url_view; ?>" title="Visualizar">
					<?php echo $txt_data; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $url_view; ?>" title="Visualizar">
					<?php echo $txt_data_alterada; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="text-center">
                                    <a href="<?php echo $url_view; ?>" title="Visualizar">
					<?php echo $txt_valor_alterado; ?>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?php echo $url_view; ?>" class="btn" data-toggle="tooltip" title="Visualizar">
                                        <i class="icon-zoom-in"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "editaraditivo",
                                                                         "id" => $registro->getId())); ?>" class="btn" title="Alterar">
                                        <i class="icon-cog"></i>
                                    </a>
                                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                         "action" => "excluiraditivo",
                                                                         "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
                                        <i class="icon-trash"></i>
                                    </a>
                                </div>
                            </td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>