<div id="janela_confirma" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="titulo">Modal header</h3>
    </div>
    <div class="modal-body">
        <p id="mensagem">One fine body?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <button id="btn_confirmar" class="btn btn-primary">Confirmar</button>
    </div>
</div>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "bolsista")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <div class="well well-small">
        <dl class="dl-horizontal">
            <dt>Vínculo:</dt>
            <dd><?php echo $this->vinculo->toString(); ?></dd>
        </dl>
    </div>
<div class="well well-small" id="idPesquisa">
        <div class="page-header">
            <h4>Opções de Pesquisa</h4>
        </div>
        <div class="control-group">
            <label for="chave" class="control-label">Tipo:</label>
            <div class="controls">
                <select name="filtro_id_bolsa_tipo" id="filtro_id_bolsa_tipo" class="filtro">
                    <option value="">==> SELECIONE <==</option>
<?php foreach ($this->bts as $bt) { ?>
                    <option value="<?php echo $bt->getId(); ?>" <?php echo ($bt->getId() == $this->dados["filtro_id_bolsa_tipo"])?"selected":""; ?>><?php echo $bt->toString(); ?> - <?php echo $bt->mostrar_valor(); ?></option>
<?php } ?>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label for="filtro_nome" class="control-label">Nome:</label>
            <div class="controls">
                <input type="text" class="filtro span5" name="filtro_nome" id="filtro_nome" value="<?php echo $this->dados["filtro_nome"]; ?>" />
            </div>
        </div>
<?php
	$ctrl = new Escola_Form_Element_Select_Table("filtro_id_bolsista_status");
	$ctrl->setPkName("id_bolsista_status");
	$ctrl->setModel("TbBolsistaStatus");
	$ctrl->setValue($this->dados["filtro_id_bolsista_status"]);
	$ctrl->setLabel("Situação: ");
    $ctrl->setAttrib("class", "filtro");
	echo $ctrl->render($this);
?>
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
            </div>
        </div>
    </div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Tipo de Bolsa</th>
				<th>Pessoa Física</th>
                <th>Info. Bancárias</th>
				<th>Situação</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
        $ib = $registro->pega_info_bancaria();
?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsista",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbBolsaTipo")->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsista",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbPessoaFisica")->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsista",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $ib->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsista",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbBolsistaStatus")->toString(); ?>
                    </a>
				</td>
				
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsista",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
									 "action" => "editarbolsista",
									 "id" => $registro->getId())); ?>" class="btn" title="Alterar">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluirbolsista",
															 "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
							<i class="icon-trash"></i>
						</a>
                                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                                     "action" => "bolsistaarquivo",
                                                                                     "id" => $registro->getId())); ?>" class="btn" title="Arquivos">
                                                    <i class="icon-folder-open-alt"></i>
                                                </a>
<?php if ($registro->ativo()) { ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "desativar",
															 "id" => $registro->getId())); ?>" class="btn link_desativar" title="Desativar">
							<i class="icon-thumbs-down"></i>
						</a>
<?php } else { ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "ativar",
															 "id" => $registro->getId())); ?>" class="btn link_ativar" title="Ativar">
							<i class="icon-thumbs-up"></i>
						</a>
<?php } ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
									 "action" => "bolsistapagamento",
									 "id" => $registro->getId())); ?>" class="btn" title="Pagamentos">
							<i class="icon-suitcase"></i>
						</a>
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>