<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <div class="well well-small">
        <dl class="dl-horizontal">
            <dt>Tipo de Bolsa:</dt>
            <dd><?php echo $this->bolsista->findParentRow("TbBolsaTipo")->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Bolsista:</dt>
            <dd><?php echo $this->bolsista->toString(); ?></dd>
        </dl>
    </div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Ano</th>
				<th>Mês</th>
				<th>Valor</th>
				<th>Situação</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
        $vl = $registro->findParentRow("TbVinculoLote");
?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsistapagamento",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $vl->ano; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsistapagamento",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo Escola_Util::pegaMes($vl->mes); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsistapagamento",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbValor")->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewbolsistapagamento",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbVinculoLoteItemStatus")->toString(); ?>
                    </a>
				</td>
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>