<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => $this->getRequest()->getActionName())); ?>" method="post" id="formulario" class="formulario form-horizontal">
<?php if ($this->registro->getId()) { ?>
                <input type="hidden" name="id" id="id" value="<?php echo $this->registro->getId(); ?>" />
<?php } ?>
                <div class="well">
                    <fieldset>
                        <legend>CADASTRO DE TERMO ADITIVO: </legend>
                        <dl class="dl-horizontal">
                            <dt>Vínculo:</dt>
                            <dd><?php echo $this->vinculo->toString(); ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Data Vigência:</dt>
                            <dd><?php echo $this->vinculo->mostrar_data_final(); ?></dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Valor Contrato:</dt>
                            <dd><?php echo $this->vinculo->mostrar_saldo(); ?></dd>
                        </dl>
<?php if ($this->registro->getId()) { ?>
                        <dl class="dl-horizontal">
                            <dt>ID:</dt>
                            <dd><?php echo $this->registro->getId(); ?></dd>
                        </dl>
<?php } ?>
<?php
$ctrl = new Escola_Form_Element_Select_Table("id_aditivo_tipo");
$ctrl->setPkName("id_aditivo_tipo");
$ctrl->setModel("TbAditivoTipo");
$ctrl->setValue($this->registro->id_aditivo_tipo);
$ctrl->setLabel("Tipo: ");
echo $ctrl->render($this);
?>
                        <div class="control-group">
                            <label for="data" class="control-label">Data:</label>
                            <div class="controls">
                                <input type="text" name="data" id="data" class="span2 data" value="<?php echo Escola_Util::formatData($this->registro->data); ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="numero" class="control-label">Número / Ano:</label>
                            <div class="controls">
                                <input type="text" name="numero" id="numero" class="span2" maxlength="20" value="<?php echo $this->registro->numero; ?>" /> / <input type="text" name="ano" id="ano" class="span1" maxlength="4" value="<?php echo $this->registro->ano; ?>" />
                            </div>
                        </div>
                        <div class="control-group linha_aditivo_data hide">
                            <label for="data_aditivo" class="control-label">Nova Data Final:</label>
                            <div class="controls">
                                <input type="text" name="data_aditivo" id="data_aditivo" class="span2 data" value="<?php echo Escola_Util::formatData($this->registro->data_aditivo); ?>" />
                            </div>
                        </div>
                        <div class="linha_aditivo_valor hide">
<?php echo $this->registro->pega_valor()->render($this, array("label" => "Valor Adicionado")); ?>
                        </div>
                        <div class="control-group">
                            <label for="observacoes" class="control-label">Observações:</label>
                            <div class="controls">
                                <textarea name="observacoes" id="observacoes" class="span6" rows="5"><?php echo $this->registro->observacoes; ?></textarea>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>