<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
<div class="well well-small" id="idPesquisa">
        <div class="page-header">
            <h4>Opções de Pesquisa</h4>
        </div>
<?php 
	$ctrl = new Escola_Form_Element_Select_Table("filtro_id_vinculo_tipo");
	$ctrl->setAttrib("class", "filtro");
	$ctrl->setPkName("id_vinculo_tipo");
	$ctrl->setModel("TbVinculoTipo");
	$ctrl->setValue($this->dados["filtro_id_vinculo_tipo"]);
	$ctrl->setLabel("Tipo do Vínculo:");
	echo $ctrl->render($this);
?>
        <div class="control-group">
            <label for="filtro_codigo" class="control-label">Código:</label>
            <div class="controls">
                <input type="text" class="filtro span1" name="filtro_codigo" id="filtro_codigo" value="<?php echo $this->dados["filtro_codigo"]; ?>" />
            </div>
        </div>
        <div class="control-group">
            <label for="filtro_ano" class="control-label">Ano:</label>
            <div class="controls">
                <input type="text" class="filtro span1" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" />
            </div>
        </div>
        <div class="control-group">
            <label for="filtro_descricao" class="control-label">Descrição:</label>
            <div class="controls">
                <input type="text" class="filtro span5" name="filtro_descricao" id="filtro_descricao" value="<?php echo $this->dados["filtro_descricao"]; ?>" />
            </div>
        </div>
<?php 
	$ctrl = new Escola_Form_Element_Select_Table("filtro_id_vinculo_status");
	$ctrl->setAttrib("class", "filtro");
	$ctrl->setPkName("id_vinculo_status");
	$ctrl->setModel("TbVinculoStatus");
	$ctrl->setValue($this->dados["filtro_id_vinculo_status"]);
	$ctrl->setLabel("Situação do Vínculo:");
	echo $ctrl->render($this);
?>
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
            </div>
        </div>
    </div>
    
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Tipo</th>
				<th>Código</th>
				<th>Ano</th>
				<th>Descrição</th>
                <th>Pessoa Jurídica</th>
				<th>Situação</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbVinculoTipo")->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->codigo; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->ano; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->descricao; ?>
                    </a>
				</td>
                <td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->mostrar_pj(); ?>
                    </a>
				</td>
                <td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbVinculoStatus")->toString(); ?>
                    </a>
				</td>
				
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
									 "action" => "editar",
									 "id" => $registro->getId())); ?>" class="btn" title="Alterar">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluir",
															 "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
							<i class="icon-trash"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                            "action" => "aditivo",
                                                             "id" => $registro->getId())); ?>" class="btn" title="Termos Aditivos">
							<i class="icon-plus-sign"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "movimento",
                                                             "id" => $registro->getId())); ?>" class="btn" title="Movimento Bancário">
							<i class="icon-bar-chart"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "bolsatipo",
                                                             "id_vinculo" => $registro->getId(),
															 "id" => "0")); ?>" class="btn" title="Tipos de Despesa">
							<i class="icon-tags"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "previsao",
                                                             "id_vinculo" => $registro->getId(),
															 "id" => "0")); ?>" class="btn" title="Previsão">
							<i class="icon-pushpin"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "bolsista",
                                                             "id_vinculo" => $registro->getId(),
															 "id" => "0")); ?>" class="btn" title="Bolsistas">
							<i class="icon-user"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "lote",
                                                             "id_vinculo" => $registro->getId(),
															 "id" => "0")); ?>" class="btn" title="Lotes">
							<i class="icon-briefcase"></i>
						</a>
                        <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "resumo",
                                                             "id" => $registro->getId())); ?>" class="btn" title="Resumo">
							<i class="icon-table"></i>
						</a>
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>