<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "lote")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
<div id="janela_add_lote" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="titulo">Adicionar Lote</h3>
    </div>
    <div class="modal-body">
        <fieldset>
            <div class="control-group">
                <label for="jan_ano" class="control-label">Ano:</label>
                <div class="controls">
                    <input type="text" name="jan_ano" id="jan_ano" class="span3" />
                </div>
            </div>
            <div class="control-group">
                <label for="jan_mes" class="control-label">Mês:</label>
                <div class="controls">
                    <select name="jan_mes" id="jan_mes">
                        <option value="">==> SELECIONE <==</option>
    <?php foreach ($this->meses as $k => $mes) { ?>
                        <option value="<?php echo $k; ?>"><?php echo $mes; ?></option>
    <?php } ?>
                    </select>
                </div>
            </div>
        </fieldset>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
</div>

    <div class="well well-small">
        <dl class="dl-horizontal">
            <dt>Vínculo:</dt>
            <dd><?php echo $this->vinculo->toString(); ?></dd>
        </dl>
    </div>
<div class="well well-small" id="idPesquisa">
        <div class="page-header">
            <h4>Opções de Pesquisa</h4>
        </div>
        <div class="control-group">
            <label for="filtro_nome" class="control-label">Ano:</label>
            <div class="controls">
                <input type="text" class="filtro span1" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" />
            </div>
        </div>
        <div class="control-group">
            <label for="mes" class="control-label">Mês:</label>
            <div class="controls">
                <select name="filtro_mes" id="filtro_mes" class="filtro">
                    <option value="">==> SELECIONE <==</option>
<?php foreach ($this->meses as $k => $mes) { ?>
                    <option value="<?php echo $k; ?>" <?php echo ($k == $this->dados["filtro_mes"])?"selected":""; ?>><?php echo $mes; ?></option>
<?php } ?>
                </select>
            </div>
        </div>
<?php
	$ctrl = new Escola_Form_Element_Select_Table("filtro_id_vinculo_lote_status");
	$ctrl->setPkName("id_vinculo_lote_status");
	$ctrl->setModel("TbVinculoLoteStatus");
	$ctrl->setValue($this->dados["filtro_id_vinculo_lote_status"]);
	$ctrl->setLabel("Situação: ");
    $ctrl->setAttrib("class", "filtro");
	echo $ctrl->render($this);
?>
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
            </div>
        </div>
    </div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Ano</th>
                <th>Mês</th>
				<th>Status</th>
                <th>Valor Total</th>
                <th>Valor Previsão</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
        $status = $registro->findParentRow("TbVinculoLoteStatus");
?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewlote",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->ano; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewlote",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo Escola_Util::pegaMes($registro->mes); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewlote",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $status->toString(); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewlote",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo Escola_Util::number_format($registro->pega_valor_total()); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewlote",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo Escola_Util::number_format($registro->pega_valor_previsao()); ?>
                    </a>
				</td>
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewlote",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluirlote",
															 "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
							<i class="icon-trash"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "loteitem",
															 "id" => $registro->getId())); ?>" class="btn" title="Gerenciar Lote">
							<i class="icon-cogs"></i>
						</a>
<?php if ($status->aguardando_liberacao()) { ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "liberar",
															 "id" => $registro->getId())); ?>" class="btn link_confirma" title="Liberar para Aprovação">
							<i class="icon-thumbs-up"></i>
						</a>
<?php } elseif ($status->aguardando_aprovacao()) {  ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "aprovar",
															 "id" => $registro->getId())); ?>" class="btn link_confirma" title="Aprovar Lote">
							<i class="icon-thumbs-up"></i>
						</a>
<?php } elseif ($status->aprovado() || $status->nf() || $status->recurso()) {  /*?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "gerarnf",
															 "id" => $registro->getId())); ?>" class="btn link_confirma" title="Gerar Nota Fiscal">
							<i class="icon-print"></i>
						</a>
<?php } elseif ($status->nf()) {  ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "recurso",
															 "id" => $registro->getId())); ?>" class="btn link_confirma" title="Registra Recebimento de Recurso">
							<i class="icon-download-alt"></i>
						</a>
<?php } elseif ($status->recurso()) { */ ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "pagar",
															 "id" => $registro->getId())); ?>" class="btn" title="Confirma Pagamento">
							<i class="icon-money"></i>
						</a>
<?php } elseif ($status->aguardando_pc()) {  ?>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "confirmarpc",
															 "id" => $registro->getId())); ?>" class="btn link_confirma" title="Confirma Prestação de Contas">
							<i class="icon-check"></i>
						</a>
<?php } ?>
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>