<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "previsao")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <div class="well well-small">
        <dl class="dl-horizontal">
            <dt>Vínculo:</dt>
            <dd><?php echo $this->vinculo->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Valor do Convênio:</dt>
            <dd><?php echo $this->vinculo->pega_valor()->toString(); ?></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Valor Previsão:</dt>
            <dd><?php echo Escola_Util::number_format($this->vinculo->pega_valor_previsao()); ?></dd>
        </dl>
    </div>
<div class="well well-small" id="idPesquisa">
        <div class="page-header">
            <h4>Opções de Pesquisa</h4>
        </div>
<?php
    $ctrl = new Escola_Form_Element_Select_Table("filtro_id_previsao_tipo");
    $ctrl->setPkName("id_previsao_tipo");
    $ctrl->setModel("TbPrevisaoTipo");
    $ctrl->setValue($this->dados["filtro_id_previsao_tipo"]);
    $ctrl->setLabel("Tipo de Previsão: ");
    $ctrl->setAttrib("class", "filtro");
    echo $ctrl->render($this);
?>
        <div class="control-group" id="linha_filtro_id_bolsa_tipo">
            <label for="chave" class="control-label">Tipo de Despesa:</label>
            <div class="controls">
                <select name="filtro_id_bolsa_tipo" id="filtro_id_bolsa_tipo" class="filtro span5">
                    <option value="">==> SELECIONE <==</option>
<?php /* foreach ($this->bts as $bt) { ?>
                    <option value="<?php echo $bt->getId(); ?>" <?php echo ($bt->getId() == $this->dados["filtro_id_bolsa_tipo"])?"selected":""; ?>><?php echo $bt->toString(); ?> - <?php echo $bt->mostrar_valor(); ?></option>
<?php } */ ?>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label for="filtro_nome" class="control-label">Ano:</label>
            <div class="controls">
                <input type="text" class="filtro span1" name="filtro_ano" id="filtro_ano" value="<?php echo $this->dados["filtro_ano"]; ?>" />
            </div>
        </div>
        <div class="control-group">
            <label for="mes" class="control-label">Mês:</label>
            <div class="controls">
                <select name="filtro_mes" id="filtro_mes" class="filtro">
                    <option value="">==> SELECIONE <==</option>
<?php foreach ($this->meses as $k => $mes) { ?>
                    <option value="<?php echo $k; ?>" <?php echo ($k == $this->dados["filtro_mes"])?"selected":""; ?>><?php echo $mes; ?></option>
<?php } ?>
                </select>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Pesquisar" class="acao btn btn-primary" />
                <input type="button" value="Limpar Filtro" id="idLimparPesquisa" class="btn" />
            </div>
        </div>
</div>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
                <th>Tipo de Previsão</th>
				<th>Tipo de Despesa</th>
				<th>Ano</th>
                <th>Mês</th>
				<th>Valor</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros && count($this->registros)) { ?>
		<tbody>
<?php
	foreach ($this->registros as $registro) {
        $bolsa_tipo = "";
        $bt = $registro->findParentRow("TbBolsaTipo");
        if ($bt) {
            $bolsa_tipo = $bt->toString();
        }
?>
			<tr>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewprevisao",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->findParentRow("TbPrevisaoTipo")->toString(); ?>
                    </a>
				</td>                
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewprevisao",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $bolsa_tipo; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewprevisao",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->ano; ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewprevisao",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo Escola_Util::pegaMes($registro->mes); ?>
                    </a>
				</td>
				<td>
                    <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewprevisao",
															 "id" => $registro->getId())); ?>" title="Visualizar">
					<?php echo $registro->mostrar_valor(); ?>
                    </a>
				</td>
				
				<td>
                    <div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "viewprevisao",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
									 "action" => "editarprevisao",
									 "id" => $registro->getId())); ?>" class="btn" title="Alterar">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluirprevisao",
															 "id" => $registro->getId())); ?>" class="btn link_excluir" title="Excluir">
							<i class="icon-trash"></i>
						</a>
                    </div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</form>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
        </div>
    </div>
</div>