<form action="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(), "action" => "index")); ?>" method="post" id="formulario" class="formulario form-horizontal" enctype="multipart/form-data">
    <div class="conteudo_controller">
        <div class="row-fluid">
            <div class="span12">
                <div class="well well-small">
                    <div class="page-header">
                        <h4>Informações do Vínculo</h4>
                    </div>
                    <dl class="dl-horizontal">
                        <dt>Vínculo:</dt>
                        <dd><?php echo $this->registro->toString(); ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Valor Total Convênio:</dt>
                        <dd><?php echo $this->registro->pega_valor()->toString(); ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Valor Previsão:</dt>
                        <dd><?php echo Escola_Util::number_format($this->registro->pega_valor_previsao()); ?></dd>
                    </dl>
                </div>
            </div>
        </div>
<?php foreach ($this->anos as $ano) { ?>
        <div class="row-fluid">
            <div class="well well-small">
                <div class="page-header">
                    <h4><?php echo $ano; ?></h4>
                </div>
                <div class="row-fluid">
                <div class="span4">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Meses</th>
                            </tr>
                        </thead>
                        <tbody>
    <?php 
    foreach ($this->meses as $mes => $desc_mes) { 
    ?>
                            <tr>
                                <td><?php echo $desc_mes; ?></td>
                            </tr>
    <?php } ?>
                        </tbody>
                    </table>
                </div>
                <div class="span4">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Previsão</th>
                            </tr>
                        </thead>
                        <tbody>
    <?php 
    foreach ($this->meses as $mes => $desc_mes) { 
        $valor = $this->registro->pega_valor_previsao(array("ano" => $ano, "mes" => $mes));
    ?>
                            <tr>
                                <td><div align="center"><?php echo Escola_Util::number_format($valor); ?></div></td>
                            </tr>
    <?php } ?>
                        </tbody>
                    </table>
                </div>
                <div class="span4">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Utilizado</th>
                            </tr>
                        </thead>
                        <tbody>
    <?php 
    foreach ($this->meses as $mes => $desc_mes) { 
        $valor = $this->registro->pega_valor_utilizado(array("ano" => $ano, "mes" => $mes));
    ?>
                            <tr>
                                <td><div align="center"><?php echo Escola_Util::number_format($valor); ?></div></td>
                            </tr>
    <?php } ?>
                        </tbody>
                    </table>
                </div>   
                    </div>
            </div>
        </div>
<?php } ?>
    </div>
</form>