<?php
$pt = $this->registro->findParentRow("TbPrevisaoTipo");
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Tipo de Despesa</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Vínculo:</dt>
                    <dd><?php echo $this->vinculo->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
<?php if ($pt) { ?>
                <dl class="dl-horizontal">
                    <dt>Chave:</dt>
                    <dd><?php echo $pt->toString();; ?></dd>
                </dl>
<?php } ?>
                <dl class="dl-horizontal">
                    <dt>Chave:</dt>
                    <dd><?php echo $this->registro->chave; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Descrição:</dt>
                    <dd><?php echo $this->registro->descricao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor:</dt>
                    <dd><?php echo $this->registro->mostrar_valor(); ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>