<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Informações de Pagamento de Bolsista</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Vínculo:</dt>
                    <dd><?php echo $this->bolsista->findParentRow("TbVinculo")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Bolsista:</dt>
                    <dd><?php echo $this->bolsista->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ano:</dt>
                    <dd><?php echo $this->vinculo_lote->ano; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Mês:</dt>
                    <dd><?php echo Escola_Util::pegaMes($this->vinculo_lote->mes); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbValor")->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Situação:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbVinculoLoteItemStatus")->toString(); ?></dd>
                </dl>
            </div>
<?php if ($this->ocorrencias) { ?>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th colspan="4">Ocorrências</th>
                    </tr>
                    <tr>
                        <th>Data / Hora</th>
                        <th>Usuário</th>
                        <th>Tipo</th>
                        <th>Descrição</th>
                    </tr>
                </thead>
                <tbody>
<?php 
foreach ($this->ocorrencias as $ocor) {
    $usuario = $ocor->findParentRow("TbUsuario");
?>
                    <tr>
                        <td><?php echo Escola_Util::formatData($ocor->data); ?> <?php echo $ocor->hora; ?></td>
                        <td><?php echo $usuario->toString(); ?></td>
                        <td><?php echo $ocor->findParentRow("TbVinculoLoteOcorrenciaTipo")->toString(); ?></td>
                        <td><?php echo $ocor->mostrar_observacoes(); ?></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
<?php } ?>
        </div>
    </div>
</div>