<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Previsão</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Vínculo:</dt>
                    <dd><?php echo $this->vinculo->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo de Previsão:</dt>
                    <dd><?php echo $this->pt->toString(); ?></dd>
                </dl>
<?php if ($this->bt) { ?>
                <dl class="dl-horizontal">
                    <dt>Tipo de Despesa:</dt>
                    <dd><?php echo $this->bt->toString(); ?></dd>
                </dl>
<?php } ?>
                <dl class="dl-horizontal">
                    <dt>Ano:</dt>
                    <dd><?php echo $this->registro->ano; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Mês:</dt>
                    <dd><?php echo Escola_Util::pegaMes($this->registro->mes); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor:</dt>
                    <dd><?php echo $this->registro->pega_valor()->toString(); ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>