<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Lotes</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Vínculo:</dt>
                    <dd><?php echo $this->vinculo->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ano:</dt>
                    <dd><?php echo $this->registro->ano; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Mês:</dt>
                    <dd><?php echo Escola_Util::pegaMes($this->registro->mes); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Status:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbVinculoLoteStatus"); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor Total:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->pega_valor_total()); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor Previsão:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->pega_valor_previsao()); ?></dd>
                </dl>
<?php if ($this->arquivo_pc) { ?>
                <dl class="dl-horizontal">
                    <dt>Prestação de Contas:</dt>
                    <dd><a href="<?php echo $this->arquivo_pc->getLink(); ?>">Clique Aqui para Abrir o Arquivo.</a></dd>
                </dl>
<?php } ?>
            </div>
<?php if ($this->ocorrencias) { ?>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th colspan="4">Ocorrências</th>
                    </tr>
                    <tr>
                        <th>Data / Hora</th>
                        <th>Usuário</th>
                        <th>Tipo</th>
                        <th>Descrição</th>
                    </tr>
                </thead>
                <tbody>
<?php 
foreach ($this->ocorrencias as $ocor) {
    $usuario = $ocor->findParentRow("TbUsuario");
?>
                    <tr>
                        <td><?php echo Escola_Util::formatData($ocor->data); ?> <?php echo $ocor->hora; ?></td>
                        <td><?php echo $usuario->toString(); ?></td>
                        <td><?php echo $ocor->findParentRow("TbVinculoLoteOcorrenciaTipo")->toString(); ?></td>
                        <td><?php echo $ocor->mostrar_observacoes(); ?></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
<?php } ?>            
        </div>
    </div>
</div>