<?php
$at = $this->registro->findParentRow("TbAditivoTipo");
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Termo Aditivo</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Vínculo:</dt>
                    <dd><?php echo $this->vinculo->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $at->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Data:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Número / Ano:</dt>
                    <dd><?php echo $this->registro->mostrar_numero(); ?></dd>
                </dl>
<?php if ($at->data()) { ?>
                <dl class="dl-horizontal">
                    <dt>Data Adicionada:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_aditivo); ?></dd>
                </dl>
<?php } elseif ($at->valor()) { ?>
                <dl class="dl-horizontal">
                    <dt>Valor Adicionado:</dt>
                    <dd><?php echo $this->registro->pega_valor()->toString(); ?></dd>
                </dl>
<?php } ?>
                <dl class="dl-horizontal">
                    <dt>Observações:</dt>
                    <dd><?php echo $this->registro->observacoes; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>