<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Ítem de Lote</h4>
                </div>
                <dl class="dl-horizontal">
                    <dt>Vínculo:</dt>
                    <dd><?php echo $this->vinculo->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Lote:</dt>
                    <dd><?php echo $this->lote->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->registro->getId(); ?></dd>
                </dl>
<?php 
$obj = $this->registro->getReferencia();
if ($obj) {
    $registro = $obj;
} else {
    $registro = $this->registro;
}
echo $obj->toHTML($this);
?>
<!--
                <dl class="dl-horizontal">
                    <dt>Tipo:</dt>
                    <dd><?php echo $this->registro->des_tipo(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Referência:</dt>
                    <dd><?php echo $this->registro->mostrar_referencia(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor:</dt>
                    <dd><?php echo $this->registro->pega_valor()->toString(); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Status:</dt>
                    <dd><?php echo $this->registro->findParentRow("TbVinculoLoteItemStatus")->toString(); ?></dd>
                </dl>
-->
            </div>
<?php if ($this->ocorrencias) { ?>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th colspan="4">Ocorrências</th>
                    </tr>
                    <tr>
                        <th>Data</th>
                        <th>Usuário</th>
                        <th>Descrição</th>
                        <th>Pagamento</th>
                    </tr>
                </thead>
                <tbody>
<?php 
foreach ($this->ocorrencias as $ocor) {
    $usuario = $ocor->findParentRow("TbUsuario");
    $txt_pgto = "";
    $pgto = $ocor->findParentRow("TbVinculoLoteItem");
    if ($pgto) { 
        $txt_pgto = $pgto->toString();
    }
?>
                    <tr>
                        <td><?php echo Escola_Util::formatData($ocor->data); ?></td>
                        <td><?php echo $usuario->toString(); ?></td>
                        <td><?php echo $ocor->descricao; ?></td>
                        <td><?php echo $txt_pgto; ?></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
<?php } ?>            
        </div>
    </div>
</div>