<div class="conteudo_controller">
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Sigla</th>
				<th>Descrição</th>
				<th>Resumo</th>
				<th>Ícone</th>
                                <th>Status</th>
                <th>Ordem</th>
				<th width="20px">Operações</th>
			</tr>
		</thead>
<?php if ($this->registros) { ?>
		<tbody>
<?php 
	foreach ($this->registros as $registro) { 
?>
			<tr>
				<td>
					<?php echo $registro->sigla; ?>
				</td>
				<td>
					<?php echo $registro->descricao; ?>
				</td>
				<td>
					<?php echo $registro->resumo; ?>
				</td>
				<td width="40px">
                                    <div class="text-center">
<?php if ($registro->icone) { ?>
					<i class="<?php echo $registro->icone; ?> icon-large"></i>
<?php } ?>
                                    </div>
				</td>
				<td><div class="text-center"><?php echo $registro->mostrar_status(); ?></div></td>
				<td>
					<?php echo $registro->ordem; ?>
				</td>
				<td width="50px">
					<div class="btn-group">
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "view",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Visualizar">
							<i class="icon-zoom-in"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "editar",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Alterar">
							<i class="icon-cog"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "excluir",
															 "id" => $registro->getId())); ?>" class="btn link_excluir" id="ExcluirModulo" data-toggle="tooltip" title="Excluir">
							<i class="icon-trash"></i>
						</a>
						<a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
															 "action" => "modulo",
															 "id" => $registro->getId())); ?>" class="btn" data-toggle="tooltip" title="Módulos">
							<i class="icon-sitemap"></i>
						</a>
					</div>
				</td>
			</tr>
<?php } ?>
		</tbody>
<?php } ?>
	</table>
</div>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>