<div class="conteudo_controller">
	<div class="row-fluid">
		<div class="span7">
			<div class="well">
				<dl class="dl-horizontal">
					<dt>Pacote: </dt>
					<dd><?php echo $this->pacote->toString(); ?></dd>
				</dl>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
				<form action="<?php echo $this->url(); ?>" method="post" id="formulario">
					<input type="hidden" name="id_pacote" id="id_pacote" value="<?php echo $this->pacote->getId(); ?>" />
					<table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th width="20px"><input type="checkbox" name="ck" class="ck-marca-todos" rel="lista_modulos" /></th>
                                <th width="20px"></th>
                                <th>Módulo</th>
                            </tr>
                        </thead>
	<?php 
	foreach ($this->modulos as $modu) {
		$checked = "";
		if ($this->pacote->possuiModulo($modu)) {
			$checked = "checked";
		} 
	?>	
						<tr>
							<td>
								<input type="checkbox" name="lista_modulos[]" id="lista_modulos" class="lista_modulos" rel="lista_modulos" <?php echo $checked; ?> value="<?php echo $modu->getId(); ?>" />
							</td>
							<td>
								<a href="#" class="link_modulo" id="<?php echo $modu->getId(); ?>">
									<?php echo $modu->mostrarIcone(); ?>
								</a>
							</td>
							<td>
								<a href="#" class="link_modulo" id="<?php echo $modu->getId(); ?>">
									<?php echo $modu->toString(); ?>
								</a>
							</td>
						</tr>
	<?php } ?>
					</table>
				</form>
		</div>
	</div>
</div>