<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well">
                <div class="page-header">
                    <h4>Notificação de Auto de Infração</h4>
                </div>
<?php echo $this->registro->view($this); ?>
        </div>
    </div>
<?php if ($this->rjs) { ?>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th colspan="4">Requerimento(s) JARI</th>
                    </tr>
                    <tr>
                        <th>Data / Hora</th>
                        <th>Documento</th>
                        <th>Resumo Doc</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
<?php foreach ($this->rjs as $rj) { 
    $txt_data_hora = $txt_documento = $txt_resumo = $txt_status = "--";
    $txt_data_hora = Escola_Util::formatData($rj->data_jari) . " - " . $rj->hora_jari;
    $doc = $rj->findParentRow("TbDocumento");
    if ($doc && $doc->getId()) {
        $txt_documento = $doc->toString();
        $txt_resumo = $doc->resumo;
    }
    $rjs = $rj->findParentRow("TbRequerimentoJariStatus");
    if ($rjs) {
        $txt_status = $rjs->toString();
    }
?>
                    <tr>
                        <td><div class="text-center"><?php echo $txt_data_hora; ?></div></td>
                        <td><?php echo $txt_documento; ?></td>
                        <td><?php echo $txt_resumo; ?></td>
                        <td><div class="text-center"><?php echo $txt_status; ?></div></td>
                    </tr>
<?php } ?>
                </tbody>
            </table>
        </div>
    </div>
<?php } ?>
</div>