<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
                <div class="well">
                    <div class="page-header">
                        <h4>Cadastro de Setor</h4>
                    </div>
                    <dl class="dl-horizontal">
                        <dt>Código:</dt>
                        <dd><?php echo $this->registro->getId(); ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Sigla:</dt>
                        <dd><?php echo $this->registro->sigla; ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Descrição:</dt>
                        <dd><?php echo $this->registro->descricao; ?></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Nível:</dt>
                        <dd><?php echo $this->registro->findParentRow("TbSetorNivel")->toString(); ?></dd>
                    </dl>
            <?php
            $obj = $this->registro->findParentRow("TbFuncionarioFuncaoTipo");
            if ($obj) {
            ?>
                    <dl class="dl-horizontal">
                        <dt>Tipo de Função Vinculada:</dt>
                        <dd><?php echo $obj->toString(); ?></dd>
                    </dl>
            <?php } ?>
            <?php
            $obj = $this->registro->findParentRow("TbSetor");
            if ($obj) {
            ?>
                    <dl class="dl-horizontal">
                        <dt>Setor Superior:</dt>
                        <dd><?php echo $obj->toString(); ?></dd>
                    </dl>
            <?php } ?>
            </div>
        </div>
    </div>
</div>