<?php
$convenio = $arquivo = $tamanho = $items = $valor_total_pago = "--";
$ar = $this->registro->pegaArquivo();
if ($ar) {
    $arr = array();
    $arr[] = $ar->toString();
    $arr[] = $ar->nome_fisico;
    $arquivo = implode(" - ", $arr);
    $tamanho = Escola_Util::mostrarTamanho($ar->tamanho);
}
if ($this->registro->convenio) {
    $convenio = $this->registro->convenio;
    if ($convenio) {
        $tb = new TbBancoConvenio();
        $bc = $tb->pegaPorConvenio($convenio);
        if ($bc) {
            $convenio = $bc->toString();
        }
    }
}
$items = $this->registro->pegaQtdItems();
$valor_total = $this->registro->pegaValorTotal();
if ($valor_total) {
    $valor_total_pago = Escola_Util::number_format($valor_total);
}
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well well-small">
                <dl class="dl-horizontal">
                    <dt>Data / Hora da Importação:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_importacao); ?> <?php echo $this->registro->hora_importacao; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Convênio:</dt>
                    <dd><?php echo $convenio; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Arquivo:</dt>
                    <dd><?php echo $arquivo; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Tamanho:</dt>
                    <dd><?php echo $tamanho; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Ítens:</dt>
                    <dd><?php echo $items; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor Total Pago:</dt>
                    <dd><?php echo $valor_total_pago; ?></dd>
                </dl>
            </div>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Nosso Número</th>
                        <th>Documento Cedente</th>
                        <th>Cedente</th>
                        <th>Convênio</th>
                        <th>Data Pagamento</th>
                        <th>Valor Pago</th>
                        <th width="20px">Operações</th>
                    </tr>
                </thead>
        <?php if ($this->registros && count($this->registros)) { ?>
                <tbody>
        <?php 
            foreach ($this->registros as $registro) { 
                $documento = $cedente = $convenio = "--";
                $boleto = $registro->findParentRow("TbBoleto");
                if ($boleto) {
                    $pessoa = $boleto->findParentRow("TbPessoa");
                    if ($pessoa) {
                        $cedente = $pessoa->toString();
                        $documento = $pessoa->mostrar_documento();
                    }
                    $bc = $boleto->findParentRow("TbBancoConvenio");
                    if ($bc) {
                        $convenio = $bc->toString();
                    }
                }    
        ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "viewboleto", "id_retorno_item" => $registro->getId())); ?>">
                                <?php echo $registro->nosso_numero; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "viewboleto", "id_retorno_item" => $registro->getId())); ?>">
                                <?php echo $documento; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "viewboleto", "id_retorno_item" => $registro->getId())); ?>">
                                <?php echo $cedente; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "viewboleto", "id_retorno_item" => $registro->getId())); ?>">
                                <?php echo $convenio; ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "viewboleto", "id_retorno_item" => $registro->getId())); ?>">
                            <?php echo Escola_Util::formatData($registro->data_pagamento); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array("action" => "viewboleto", "id_retorno_item" => $registro->getId())); ?>">
                                <?php echo Escola_Util::number_format($registro->valor_pago); ?>
                            </a>
                        </td>
                        <td>
                            <div class="btn-group">	
                                <a href="<?php echo $this->url(array("controller" => $this->getRequest()->getControllerName(),
                                                                     "action" => "viewboleto",
                                                                     "id_retorno_item" => $registro->getId())); ?>" class="btn" title="Visualizar">
                                    <i class="icon-search"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
        <?php } ?>
                </tbody>
        <?php } ?>
            </table>
<?php if ($this->registros && count($this->registros)) { ?>
<?php echo $this->paginationControl($this->registros, "sliding", "minha_paginacao_control.phtml"); ?>
<?php } ?>
        </div>
    </div>
</div>