<?php
$documento = $cedente = $convenio = "--";
if ($this->boleto) {
    $pessoa = $this->boleto->findParentRow("TbPessoa");
    if ($pessoa) {
        $cedente = $pessoa->toString();
        $documento = $pessoa->mostrar_documento();
    }
    $bc = $this->boleto->findParentRow("TbBancoConvenio");
    if ($bc) {
        $convenio = $bc->toString();
    }
}    
?>
<div class="conteudo_controller">
    <div class="row-fluid">
        <div class="span12">
            <div class="well well-small">
                <dl class="dl-horizontal">
                    <dt>Nosso Número:</dt>
                    <dd><?php echo $this->registro->nosso_numero; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Documento Cedente:</dt>
                    <dd><?php echo $documento; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Cedente:</dt>
                    <dd><?php echo $cedente; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Convênio:</dt>
                    <dd><?php echo $convenio; ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Data Pagamento:</dt>
                    <dd><?php echo Escola_Util::formatData($this->registro->data_pagamento); ?></dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Valor Pago:</dt>
                    <dd><?php echo Escola_Util::number_format($this->registro->valor_pago); ?></dd>
                </dl>
            </div>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th width="30px">#</th>
                        <th>Tipo</th>
                        <th>Referência</th>
                        <th>Valor</th>
                        <th>Confirmado</th>
                        <th>Mensagem</th>
                    </tr>
                </thead>
        <?php if ($this->items && count($this->items)) { ?>
                <tbody>
        <?php 
            $contador = 0;
            foreach ($this->items as $item) {
                $contador++;
                $tipo = $referencia = $valor = $confirmado = $mensagem = "--";
                $bit = $item->findParentRow("TbBoletoItemTipo");
                if ($bit) {
                    $tipo = $bit->toString();
                }
                $obj = $item->pegaReferencia();
                if ($obj) {
                    $referencia = $obj->toString();
                }
                if ($item->valor) {
                    $valor = Escola_Util::number_format($item->valor);
                }
                $rir = $this->registro->pegaRelatorio($item);
                if ($rir) {
                    $confirmado = "Não";
                    if ($rir->confirmado()) {
                        $confirmado = "Sim";
                    }
                    $txt = $rir->mensagem;
                    if ($txt) {
                        $mensagem = $txt;
                    }
                }
        ?>
                    <tr>
                        <td><div class="text-center"><?php echo $contador; ?></div></td>
                        <td><?php echo $tipo; ?></td>
                        <td><?php echo $referencia; ?></td>
                        <td><div class="text-center"><?php echo $valor; ?></div></td>
                        <td><div class="text-center"><?php echo $confirmado; ?></div></td>
                        <td><div class="text-center"><?php echo $mensagem; ?></div></td>
                    </tr>
        <?php } ?>
                </tbody>
        <?php } ?>
            </table>
        </div>
    </div>
</div>